"""Private Chemistry review, normalized records 681–720. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][680:720]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==2000:return 59
 if q['year']==2002:return 62
 return 60 if q['num']<=16 else 61

def yes(i,a,e,urls,*,question=None,options=None,year=None,num=None,audit='',check=None):
 q=qs[i-681];u=copy.deepcopy(q)
 if year:u['year']=year
 if num:u['num']=num
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['has_diagram']=False;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-681];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})
ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
CARB='https://edu.rsc.org/resources/carbonyl-chemistry-16-18/4010284.article'
ACID='https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'
CAT='https://openstax.org/books/chemistry-2e/pages/12-7-catalysis'

yes(681,'C','Potassium produces a characteristic lilac or violet flame. Heating excites electrons, and their return to lower energy levels emits characteristic wavelengths of light.',[REB],question='Potassium vapour burns with a',options=['Blue flame','Brick-red flame','Violet flame','Golden-yellow flame'])
yes(682,'C','Haematite is iron(III) oxide, Fe₂O₃, and is an important ore used to obtain iron.',[REB],question='Haematite is an ore of',options=['Zinc','Lead','Iron','Copper'],audit='PDF59 fourthoptionprintedE restoredcontiguousD; format4not5.')
yes(683,'C','Zinc has a less negative standard reduction potential than aluminium, sodium or calcium, so it has the lowest thermodynamic tendency to be oxidised among these metals. Aluminium surface passivation affects reaction rate but does not place it below zinc in the reactivity series.',[EL,'https://openstax.org/books/chemistry/pages/17-3-standard-reduction-potentials?modal=MH'],question='According to the standard electrochemical reactivity series, which metal is least readily oxidised?',options=['Ca','Na','Zn','Al'],audit='CorrectedD→C; separated electrochemical oxidation tendency from aluminium protectivefilm kinetics.',check='metal-potential-order')
yes(684,'B','Natural rubber consists mainly of cis-1,4-polyisoprene. Its chain units are derived from isoprene, 2-methylbuta-1,3-diene; polymerisation changes the monomer bonding while retaining the C₅H₈ composition per unit.',[ORG,REB],question='The repeating units of natural rubber are derived from which monomer?',options=['Alkynes','Isoprene','n-Propane','Neoprene'],audit='Distinguished monomer from polymerrepeatbondstructure; retained intendedisopreneconcept.')
no(685,'Both bromine water plus acidified permanganate and bromine water plus alkaline permanganate can react with unsaturation, so B and D overlap. OptionC silverbromine also chemically undefined. Need original specificconditions/testcriterion; no unique key as supplied.')
no(686,'Removingwaterfromtwoethanol molecules gives ether, requiring lower≈140°Cconditions rather than oldCethene≈170°C explanation. But lower/higher and less/excessacid have no quantitative or comparative reference. Hold for explicit sourceconditions instead of inventingtemperaturesandquantities.')
no(687,'Tetrachloromethane historically was a degreasing solvent, but dichloromethane and trichloromethane also dissolvegrease; industrialuse scope/time unspecified. OldexplanationcallingCCl₄thestandardcurrentindustrialsolvent is misleading. Need unique historicalprocesscontext rather thanchooseAbytradition.')
no(688,'PDF59 has duplicateethaneB/C, missingcarbideidentity and mergedcarbonylOfromnextquestion. Calciumcarbidegivesethyne but othercarbidesgiveotherproducts(e.g.Al₄C₃methane). Cannot silentlysupplycalciumorcreatea distinctoption.')
yes(689,'B','CH₃CH₂C(=O)OCH₂CH₃ contains the ester linkage –C(=O)–O– between carbon groups. It is ethyl propanoate, an ester.',[ORG,REB],question='CH₃CH₂C(=O)OCH₂CH₃ is an',options=['Ether','Ester','Alkanal','Alkanol'],audit='PDF59carbonylOabovechain anddoublebondvisually recovered; completecondensedformula.',check='ester-functional-group')
yes(690,'B','Oxidation of a secondary alcohol removes the O–H hydrogen and the hydrogen on the carbon bearing OH, producing a ketone carbonyl. For example, propan-2-ol forms propanone.',[ORG,REB],question='Alkanones are generally obtained by controlled oxidation of',options=['Primary alkanols','Secondary alkanols','Tertiary alkanols','Alkanoic acids'])
yes(691,'B','Sucrose is a disaccharide containing one glucose unit and one fructose unit joined by a glycosidic bond. Hydrolysis releases glucose and fructose.',[REB],question='Sucrose is made up of units of',options=['Glucose and glucose','Glucose and fructose','Fructose and fructose','Galactose and glucose'],audit='Removednextyearheader/pageartifact.')
yes(692,'A','Ethanoic acid has molecular formula C₂H₄O₂. Dividing all subscripts by two gives the simplest whole-number ratio CH₂O, its empirical formula.',[RX],question='The formula CH₂O for ethanoic acid is its',options=['Empirical formula','Molecular formula','Structural formula','General formula'],year=2002,audit='Actual2002Q1PDF62; recoveredB/C/D fromfirstcolumnbelowheader rather than2002Q3chromatographyoptions. Stable1999/2001importIDpreserved.',check='empirical-acid')
yes(693,'A','The equation 2H₂ + O₂ → 2H₂O gives one mole of water per mole of hydrogen. There are 8.0/2 = 4.0 mol H₂, giving 4.0 × 18 = 72.0 g H₂O.',[RX],question='What mass of water forms when 8.0 g hydrogen reacts completely with excess oxygen? [H = 1, O = 16]',options=['72.0 g','36.0 g','16.0 g','8.0 g'],audit='Removedgraphinstruction; correctedcontradictory0.25molexplanationwhilekeepingA.',check='water-stoichiometry')
yes(694,'A','Count moles of atoms: argon gives 7 × 1 = 7; chlorine gives 4 × 2 = 8; ozone gives 3 × 3 = 9; butane gives 1 × (4 + 10) = 14. The argon sample therefore contains the fewest atoms.',[RX],question='Which gas sample contains the fewest atoms at standard temperature and pressure?',options=['7 mol argon','4 mol chlorine','3 mol ozone','1 mol butane'],year=2002,audit='Actual2002Q2PDF62; correctedoldD→Aandmolesversusindividualatomconfusion.',check='atom-count')
no(695,'PDF60 heatingcurve recovered: initialwarming~0–1min, meltingplateau~1–2.5min, liquidwarming~2.5–3min. Endpointfromheatingstart2.5minC but actualmeltingduration1.5minabsent. Originalhowlongambiguouslyasksduration; holduntilintendedtimeoriginconfirmed, notoldguessed6min.')
yes(696,'B','Ink components have different affinities for the stationary phase and the moving solvent. They therefore travel at different rates and separate into bands; chemical reaction between the components is not required.',[REB],question='Chromatographic separation of ink is based on the ability of its components to',options=['Dissolve in each other in the column','Move at different speeds in the column','React with the solvent','React with each other'],year=2002,audit='Actual2002Q3PDF62; restoredquestionendingandalloptionsfromrightcolumn, removed2001Q42sulfuricacidfunctionoptions.')
yes(697,'D','At the liquid–vapour phase change, temperature remains at the boiling point while latent heat is supplied. Cooling the vapour at the same pressure causes condensation at that same temperature, 150 °C.',[REB],question='A heating curve shows a solid warming, a melting plateau, liquid warming to 150 °C, a liquid–vapour plateau at 150 °C, then further warming of the vapour. If this vapour is cooled at the same pressure, at what temperature does condensation begin?',options=['175 °C','250 °C','125 °C','150 °C'],audit='PDF60phasecurvevisuallyinspected; preservedallphasesequenceand150°Cplateauinaccessibletext. Noestimateduniversalcondensationtemperature.')
yes(698,'B','Atomic numbers 2, 6, 16 and 20 identify helium, carbon, sulfur and calcium respectively. Calcium, labelled Z, is the metal; the others are non-metals.',[REB],question='Elements W, X, Y and Z have atomic numbers 2, 6, 16 and 20 respectively. Which is a metal?',options=['X','Z','W','Y'],audit='Repairedmeal→metal andpunctuation.')
yes(699,'B','Each atom supplies an electron to a shared pair. Sharing an electron pair forms an ordinary covalent bond. A coordinate covalent bond would have both shared electrons supplied initially by one atom.',[REB],question='Two identical atoms, each with one unpaired outer-shell electron, approach and form overlapping outer shells containing a shared pair, with one electron contributed by each atom. Which bond is formed?',options=['A metallic bond','A covalent bond','An electrovalent bond','A coordinate covalent bond'],audit='PDF60twoidenticalthree-shellatomswithsharedouterpairvisuallyinspected; restoredseparateDfrommergedC. CorrectedD→Bwithfullbondingcontext.')
no(700,'X-rays and gamma rays are both used in radiotherapy; sourcequestiondoesnotselecta treatment modality. NCISEERhttps://training.seer.cancer.gov/treatment/radiation/ confirmsboth. Curedbyexposure is also a falseguarantee. Holdmultiplecorrectoptions rather thanaddcobalt60premise.')
yes(701,'B','For an ideal gas, average translational kinetic energy per molecule is 3kT/2. It increases with absolute temperature. Pressure or volume changes alone do not imply a change in that average energy.',[GAS,REB],question='Which statement about the average kinetic energy of ideal-gas molecules is correct?',options=['It increases whenever pressure increases','It increases as absolute temperature increases','It increases whenever volume increases','It necessarily increases at constant pressure'],audit='Madeideal-gasmodelandunqualifiedwhenever alternatives explicit.',check='kinetic-temperature')
yes(702,'D','Millikan’s oil-drop experiment measured the elementary electric charge. The charge-to-mass ratio of the electron had been measured earlier using cathode rays.',[REB,'https://www.nobelprize.org/prizes/physics/1923/millikan/facts/'],question='Millikan’s contribution to atomic theory was determining the',options=['Positive rays','Cathode rays','Charge-to-mass ratio of the electron','Charge on the electron'],audit='Nobelprimaryindexedfactsconfirmcharge;directfactsURL403recorded rather thanclaimingfullpagerecovery. SuppliedPDF60complete.')
yes(703,'C','Aluminium sulfate is a coagulant. In suitable water conditions it forms aluminium hydroxide flocs that gather fine suspended material so it can be removed by settling and filtration.',[REB],question='Which chemical is used for coagulation during water purification?',options=['Copper(II) sulfate','Sodium sulfate','Aluminium sulfate','Calcium sulfate'])
no(704,'Both heavymetals (historically leadedfuel) and smoke/particulates worsenpollution, so AandC are plausible. Bwater vapour and Dsteamduplicatephaseconcept. No unique sourcecriterion; do not inventleadedpetrolpremise.')
yes(705,'C','White phosphorus can ignite in air. Storing it under water limits contact with oxygen and prevents ignition; this storage precaution refers to white phosphorus rather than all phosphorus allotropes.',[REB],question='White phosphorus is stored under water to prevent it from',options=['Smelling','Dehydrating','Catching fire','Becoming inert'],audit='Specifiedwhiteallotrope thatactuallyrequiresthe statedstorage.')
yes(706,'D','Distillation vaporises a solvent and then condenses the vapour into a separate receiver. Non-volatile dissolved substances remain behind, allowing recovery of the solvent.',[REB],question='Which separation process recovers a pure solvent from a solution containing a non-volatile solute?',options=['Evaporation','Extraction','Condensation','Distillation'],audit='Restoredsolventrecoverycontext distinguishingcompleteprocessfromcondensationstep; removedpageartifact.')
no(707,'PDF61curvesarepresentbutintersectionnear80–85°Ccannotbe confidentlyreadtoexact82fromthe low-qualitysource. Old90isunsupported. Needclearoriginalgraphoractualcoordinateevidence; no nearestchoicefromblurredintersection.')
no(708,'PDF61L/Kcurve labelsandverticalgridreadingsareblurred/inconsistent. MatchingMyschool31592alsohasdocumentedscaleambiguityanddifferentoptionorder; noindependentexact0.75versus0.50basis. Holdforclearcoordinatesandvolumeconvention; do notcopyanswerkey.')
yes(709,'A','Deliquescent substances absorb enough moisture from air to dissolve in the absorbed water. Suitable examples such as calcium chloride can remove water vapour and serve as drying agents.',[REB],question='Suitable deliquescent substances are used for',options=['Drying','Melting','Wetting','Cooling'],audit='RemovedoldconcentratedH₂SO₄deliquescentexample; it ishygroscopicliquid, notsolidundergoingdeliquescence.')
yes(710,'D','Alkaline pyrogallol absorbs oxygen. Taking dry air as 21% oxygen by volume, the removed volume is 0.21 × 30.00 = 6.30 cm³, with temperature and pressure unchanged.',[REB],question='What decrease in volume occurs when excess alkaline pyrogallol completely absorbs oxygen from 30.00 cm³ dry air containing 21% oxygen by volume, at unchanged temperature and pressure?',options=['0.63 cm³','0.06 cm³','15.00 cm³','6.30 cm³'],audit='Madeconventionalalkalinesolution, oxygenfractionandexcess/constantconditions explicit.',check='air-oxygen')
no(711,'Evaporationdoesnotdisperseallpetroleum; detergentscanemulsifybutbestspillresponseis site/ecosystemdependentandpouringhouseholddetergentscanworsenharm. Needaquestionaboutemulsificationmechanismorwell-definedresponseconditions, notabroadbestenvironmentalrecommendation.')
yes(712,'C','Copper changes from oxidation state 0 to +2, losing electrons. It supplies the electrons that reduce nitrogen from +5 in nitrate to +2 in NO, so copper is the reducing agent.',[RX],question='In 3Cu(s) + 8HNO₃(aq) → 3Cu(NO₃)₂(aq) + 4H₂O(l) + 2NO(g), copper acts as',options=['A base','An oxidising agent','A reducing agent','An electron acceptor'],audit='Restoredarrow,subscriptsandwaterstate.',check='copper-nitrate')
yes(713,'D','Two gaseous reactants form a crystalline solid. The loss of gas-particle freedom gives a decrease in the system’s entropy, so ΔS is negative.',[REB],question='For NH₃(g) + HCl(g) → NH₄Cl(s), the entropy change of the system is',options=['Zero','Indeterminate','Positive','Negative'],audit='RestoredClratherthanCIandarrow; specifiedsystemratherthansurroundings.')
no(714,'ForwardSO₂oxidationtoSO₃isexothermic. RaisingtemperaturedecreasesK; pressure,surfaceareaandcatalystdonotraiseK atfixedT. NoneoflistedoptionsincreasesK. Needoriginaldecreasingtemperatureoptionorchangedinstead ofincreased wording; cannotrewritejusttoforceB.')
yes(715,'A','In a dilute electrolyte, reducing concentration lowers the number of mobile charge carriers per unit volume, so electrical conductivity decreases at fixed temperature. Molar conductivity is a different quantity and can increase on dilution.',[REB],question='For a dilute electrolyte at fixed temperature, reducing concentration generally makes its electrical conductivity',options=['Decrease','Increase','Become exactly zero','Remain unchanged'],audit='Distinguishedspecificconductivityfrommolarconductivityandlimitedtodilu te regime.'.replace('dilu te','dilute'))
no(716,'PositiveΔH89wouldindicateheatabsorption, but sourceC(s)+2S(g)→CS₂hasincorrect/incompletephysicalstates for statedformationenthalpy. Atomicsulfur gasreactantdoesnotmatchusual+89kJmol−1CS₂(g)formationfromstandardstates. Holdforcorrectstates/source; donotpublishfalsechemicalpremise.')
no(717,'NitrogeninNOis+2; NOBr andNOClhaveN+3, andNO₂N+4. ThusA,CandDallincreaseNoxidationnumber. No uniqueanswer; oldDexplanationdoesnotexcludeA/C. Holduntildifferent originalreactionoptionsarefound.')
yes(718,'A','Removing gaseous product S lowers the reaction quotient and drives the equilibrium forward, forming more R. Increasing vessel volume favours the side with more gas molecules, which is the reactant side; a catalyst does not change equilibrium yield.',[REB],question='For P(g) + Q(g) ⇌ 3R(s) + S(g), which change necessarily increases the equilibrium yield of R under otherwise unchanged conditions?',options=['Removing some S','Using a larger closed vessel','Adding a catalyst','Increasing the temperature'],audit='RemovedmergedEthanoicacidnextquestion; necessarily distinguishesunknownheat-effectfromguaranteedproductremoval.',check='equilibrium-quotient')
yes(719,'C','Reduction is electron gain. Hydrogen ions gain two electrons to form H₂, reducing hydrogen’s oxidation number from +1 to 0. The other half-equations release electrons and represent oxidation.',[RX],question='Which half-equation represents reduction?',options=['2O²⁻ → O₂ + 4e⁻','Fe²⁺ → Fe³⁺ + e⁻','2H⁺ + 2e⁻ → H₂','Cr → Cr²⁺ + 2e⁻'],audit='RestoredmissingC2electronsandrewroteB/Dsubtractionnotationasbalancedrightsideelectrons; PDF61originalionspreserved.',check='redox-half-equations')
yes(720,'B','A negative enthalpy change means the products have lower enthalpy than the reactants and heat is released to the surroundings. Such a reaction is exothermic.',[RX],question='When ΔH is negative, a reaction is described as',options=['Endothermic','Exothermic','Reversible','Ionic'],audit='RestoredΔandremovednextpagefragment.',check='negative-enthalpy')
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-018','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry681–720; source2000–2002. PDF59–62 visually inspected; correctedyear/groupedcontext and explicit held defects.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-018.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
