"""Private Chemistry review batch; normalized records 81–120 only."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][80:120]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
PHASE='https://openstax.org/books/chemistry-2e/pages/10-3-phase-transitions'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
ORG='https://openstax.org/books/chemistry-2e/pages/20-3-aldehydes-ketones-carboxylic-acids-and-esters'
rows=[]
def page(q):
 if q['year']==1984:return 9
 if q['year']==1986:return 13
 return 10 if q['num']<=12 else 11 if q['num']<=27 else 12 if q['num']<=39 else 13
def yes(i,a,e,urls,*,question=None,options=None,num=None,year=None,audit='',check=None):
 q=qs[i-81];u=copy.deepcopy(q)
 if num:u['num']=num
 if year:u['year']=year
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Complete question and options compared with supplied PDF; independently answered and teaching explanation written.','calculation_check':check})
def no(i,why,*,num=None,year=None,answer=None):
 q=qs[i-81];temp={**q,'num':num or q['num'],'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})

yes(81,'D','Zn + H₂SO₄ → ZnSO₄ + H₂. The acid amount is 0.5×500/1000 = 0.25 mol, producing 0.25 mol H₂ because zinc is in excess. At the given molar volume, 0.25×22.4 = 5.6 dm³ of hydrogen is formed.',[RX],question='At STP, what volume of hydrogen is formed when 500 cm³ of 0.5 mol dm⁻³ H₂SO₄ reacts completely with excess zinc? Use a molar gas volume of 22.4 dm³ mol⁻¹.',options=['22.4 dm³','11.2 dm³','6.5 dm³','5.6 dm³','0.00 dm³'],audit='Removed following1985 heading/periodic-table question from optionE; restored complete acid/excess-zinc wording and moved gas-volume premise into stem.',check='hydrogen-volume')
yes(82,'C','Iron(III) oxide is Fe₂O₃, with formula mass 2×56 + 3×16 = 160. One kilogram is 1000 g, so the amount is 1000/160 = 6.25 mol.',[RX],num=7,question='How many moles of iron(III) oxide are present in 1.00 kg of the compound? [Fe = 56, O = 16]',audit='Supplied page10 prints this betweenQ6 andQ8 as1; restored actual sequence number7 and atomic-mass terminology, preserving stableID.',check='iron-oxide-moles')
yes(83,'C','Evaporation occurs when molecules escape from a liquid surface into the gas phase. Condensation is the reverse change, from gas to liquid.',[PHASE],year=1986,question='The movement of molecules from the surface of a liquid into the gas phase above it is called',audit='Page13 Chemistry1986 heading confirms actual source year; changed year1985 to1986, retained stableID and four options.')
yes(84,'B','In graphite, each carbon atom bonds to three others and contributes an electron to a delocalised system. These mobile electrons carry electrical charge through the layers.',['https://edu.rsc.org/cpd/how-to-teach-structure-and-bonding-of-carbon-at-14-16/4020312.article'])
no(85,'Actual1986Q2. Stated22cm³ H₂ gives22/22400×40=0.0392857g metal, absent from all options. Old explanation incorrectly changed0.04g to0.4g. Alternate Wordpress transcription repeats22cm³, so it does not repair the missing decimal/volume. No nearest-choice answer.',year=1986)
no(86,'Independent empirical formula is C₆H₁₂O (D), but optionE is malformed C₃CH₁₀ in the suppliedPDF. A full accurate distractor transcription is needed before complete-item approval; do not invent missing O/subscripts.',answer='D')
no(87,'0.499g initial and0.346g anhydrous CuSO₄ give x=(0.153/18)/(0.346/159.5)=3.9183526, not5. Values do not support an integer within stated0.001g rounding. D≈4 is plausible experimentally, but no uncertainty stated. Myschool44471 repeats the same numbers; retainheld rather than round a flawed source into a key.',answer='D approximately; source inconsistent')
no(88,'OptionC is incomplete in PDF: begins to melt until648K, lacking starting temperature or statement that melting spans a range. Mixture inference requires actual range; cannot invent omitted temperature.',answer='C intended')
yes(89,'E','Graham’s law gives rate ∝ 1/√molar mass. For H₂ and O₂, rate(H₂)/rate(O₂) = √(32/2) = 4. Hydrogen therefore passes through the porous plug four times as fast under the same conditions.',['https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'],question='Under the same conditions, hydrogen diffuses through a porous plug',options=['at the same rate as oxygen','more slowly than oxygen','twice as fast as oxygen','three times as fast as oxygen','four times as fast as oxygen'],check='graham-ratio')
no(90,'Shared solubility graph on PDFpage10 absent from normalized record. Visual graph suggests Y≈2X at300K, not oldD. Need accurate accessible owned graph, clear curve labels, and reading uncertainty; no current complete candidate.',answer='A provisional')
no(91,'Shared graph essential. At353K, steepX curve appearsabove80g whileY≈64g, suggesting only16gY undissolved (B), notC. Need checkedgraph and fully restored optionA; prior X=70g was not supported.',answer='B provisional')
no(92,'Graph appearsX≈72g/100g water at343K, giving72/36=2mol (D), not oldB0.7. Graph and100g-water context must be restored before release; no owned graph yet.',answer='D provisional')
yes(93,'C','Sour taste and pH below7 describe acidic behaviour. A typical alkali has pH above7, can release ammonia from ammonium salts, and turns phenolphthalein pink. Thus (i) and(iv) are not typical alkali properties.',['https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'],question='Which listed properties are not typical of alkalis?\n(i) Sour taste\n(ii) Slippery feel\n(iii) Release of an alkaline gas from ammonium salts\n(iv) pH below7\n(v) Turning phenolphthalein pink',options=['(i), (iv) and(v)','(iv) and(v)','(i) and(iv)','(ii) and(v)','(ii), (iii) and(v)'],audit='Restored sour from solar, alkalis from alkaline, full cross-page options and spacing. Text describes properties, not instructions to taste or touch chemicals.')
no(94,'B is conventional school explanation, but oxidation of nascent hydrogen is not the actual general mechanism; nitric acid reduction products depend on concentration. Source gives no conditions. Avoidteaching the previous mechanistic claim as established fact.',answer='B intended')
yes(95,'C','For these liquids, ethanol has the highest vapour pressure at323K. Its lower normal boiling point indicates greater volatility in this comparison. Vapour-pressure data confirm that its pressure at323K exceeds those of water, toluene and butan-2-ol.',[f'https://webbook.nist.gov/cgi/cbook.cgi?ID={cas}&Mask=4' for cas in ['C64175','C7732185','C108883','C78922']],question='The normal boiling points of water, ethanol, toluene and butan-2-ol are373.0K,351.3K,383.6K and372.5K respectively. Which has the highest vapour pressure at323.0K?',options=['Water','Toluene','Ethanol','Butan-2-ol','None'],audit='Corrected butan-2-ol spelling. Checked actualNIST vapour-pressure fits: no universal claim that boiling-point ordering guarantees pressure ordering. Butan-2-ol calculation integrates in-rangeNIST vaporization-enthalpy correlation from372K to323K, anchored at372KAntoine fit.',check='nist-vapour-pressure')
yes(96,'B','Removing oxygen and carbon dioxide from air leaves nitrogen mixed with noble gases, especially argon. Argon is heavier than nitrogen molecules, so this sample is slightly denser than chemically prepared pure nitrogen at the same temperature and pressure.',['https://periodic-table.rsc.org/element/18/Argon'],question='Two dry nitrogen samples are compared at the same temperature and pressure. Sample1 is prepared by completely removing CO₂ and O₂ from air; sample2 by passing purified nitrogen(I) oxide over heated copper. Sample1 is',options=['purer than sample2','slightly denser than sample2','identical in all respects to sample2','colourless whereas sample2 is light brown','slightly less reactive than sample2'],audit='Changed wrongA toB; atmospheric argon remains afterO₂/CO₂ removal. Added sameT/P comparison and completed grammar ofD. Did not claim residual nitrogen morepure.')
yes(97,'A','Charge passed is Q=It=0.193×(2×3600)=1389.6C. Cu²⁺ needs two electrons per copper atom, so molesCu=1389.6/(2×96500)=0.0072mol. The deposited mass is0.0072×63.5=0.4572g, which is0.457g to three significant figures.',[EL],question='Copper(II) sulfate solution is electrolysed using platinum electrodes. A current of0.193A flows for2hours. Assuming100%current efficiency for copper deposition, what mass of copper is deposited? [Cu=63.5; F=96500Cmol⁻¹]',options=['0.457g','0.500g','0.882g','0.914g','1.00g'],audit='Corrected oldD toA. Oldcharge1387.6 was arithmeticerror and oldmoles doubled the actualFaraday result. Movedconstants out ofE.',check='copper-deposition')
no(98,'At leastB,C,D can describe rateeffects beforeequilibrium, whileD remains true forforwardrate; netconcentrationchange at equilibrium iszero. Aalsointroduces undefinedW. Source lacks single-answer qualifier; no uniquecompletequestion.')
yes(99,'D','A neutral formula must balance charges. Na contributes+1 and Ga contributes+3. Four hydroxide groups contribute−4, so Na[Ga(OH)₄] is neutral. The other listed formulas do not balance with Ga in oxidation state+3.',[RX],question='Which sodium gallate formula is consistent with gallium in oxidation state+3?',options=['NaGaO₃','Na₂Ga(OH)₂','NaGa(OH)₃','NaGa(OH)₄','NaGaO'],audit='Restored missing a in Ga in optionB. Verified charge neutrality for allfive formulae, not guessed fromname.',check='gallate-charge')
no(100,'A is historical intendedsourcepattern (leadedvehicle exhaust plusdecomposition), but only/must infer sources from pollutants is not justified: lead andNOx/CO have multiplesources and methane neednotbe biological. Requires explicit historicalscenario and probabilisticwording beforeuse; no current emissionsclaim.',answer='A intended historical')
yes(101,'D','MnO₄⁻ is reduced: manganese changes from+7 to+2, gaining electrons. The reactant that accepts electrons oxidises the other species and is the oxidising agent. Chloride instead loses electrons to form chlorine.',[RX],question='In2MnO₄⁻+10Cl⁻+16H⁺→2Mn²⁺+5Cl₂+8H₂O, which species is the oxidising agent?',options=['Mn²⁺','Cl⁻','H₂O','MnO₄⁻','Cl₂'],audit='Restored fullcharges, equationarrow and optionD charge; checkedatoms,charge and oxidationstates.',check='permanganate-redox')
no(102,'Argon has no equilibrium effect at constantvolume, but can shift unequal-gasmoleequilibrium at constantpressure. Source omits constraint and has nonsensicalnegativewaterdecompositionenthalpy−2436000kJ². CannotapproveA unconditionally.',answer='A only at constant volume')
yes(103,'D','Zinc is above iron in the reactivity series and more readily loses electrons. It displaces iron from iron(II) sulfate: Zn+Fe²⁺→Zn²⁺+Fe. Copper, mercury, silver and gold are below iron.',['https://edu.rsc.org/experiments/displacement-reactions-between-metals-and-their-salts/720.article'],question='Which metal displaces iron from aqueous iron(II) sulfate?')
yes(104,'E','Complete hydrogenation adds two H₂ molecules across the carbon–carbon triple bond: C₂H₂+2H₂→C₂H₆. The carbon skeleton still has two atoms, so the product is ethane.',['https://openstax.org/books/organic-chemistry/pages/9-5-reduction-of-alkynes'],audit='Changed false methaneB toethaneE; carbon and hydrogen conserved.',check='ethyne-hydrogenation')
yes(105,'B','Chlorine reacts with calcium hydroxide (slakedlime) to produce bleachingpowder containing hypochlorite. The hypochlorite provides its oxidising and bleaching action.',['https://m.cameochemicals.noaa.gov/chemical/10643'],options=['Sulfur dioxide','Chlorine','Sulfuric acid','Hydrogen sulfide','Nitrogen dioxide'],audit='Expanded incomplete hydrogentetraoxosulphate distractor into sulfuricacid; retainedB based onchlorination oflime.')
yes(106,'E','Water molecules move randomly and continually collide with the pollen grains. The uneven impacts from different directions produce the grains’ irregular Brownianmotion.',['https://openstax.org/books/chemistry-2e/pages/11-5-colloids'])
no(107,'Givenformationenthalpies−393 and−110.4 implyΔH=−282.6kJ, absent fromchoices. A−503.7 is sign/arithmeticerror; C−282.9 would require−393.3forCO₂. Corroboratingtranscription repeats−393, so noauthority to silentlychangedatum.',answer='−282.6kJ from printed data')
yes(108,'A','Nitrogen dioxide disproportionates in alkali: 2NO₂+2NaOH→NaNO₂+NaNO₃+H₂O. Nitrogen starts at+4 and becomes+3 in nitrite and+5 in nitrate, so both salts form.',[RX,'https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'],question='The reaction of NO₂ with aqueous NaOH produces water and',options=['NaNO₂ and NaNO₃','NaNO₃ and HNO₃','NaNO₂ only','NaNO₃ only','NaN₂O₃'],audit='Removed followingstructuralformulaCH₃fromE; restoredchemicalsubscripts and explicitonly alternativesC/D.',check='nitrogen-disproportionation')
no(109,'PDFstructure has fourcarbons withincompletevalencies and terminalC–O–H, suggestingbutan-1-ol ratherthan oldthreecarbonaldehydeexplanation. Oxidationcouldstopatbutanal orcontinuebutanoicacid dependingconditions, which areabsent. Fullcorrectstructure/oxidantneeded.',answer='D only for complete oxidation')
no(110,'AcidifiedBaCl₂ isthestandardconfirmatorytest(B), but acidifiedleadnitrate(E)canalso precipitatePbSO₄. The suppliedfinallytested wordingdoesnotestablishwhyE isexcluded. Need original qualifierorvalidatedspecificitybeforeuniquekey.',answer='B conventional; E also precipitates sulfate')
no(111,'PDFshows six-carbonbackbone with methylbranch while allnamesusepentene/pentane, someinvalidlocants. AlternateSchoolNGRlistscorrected4-methylpent-2-ene(D)but requires correspondingfive-carbonstructureverification. Do notmixthatnamewithsuppliedsixcarbonstem.')
yes(112,'E','Ba²⁺ combines with CO₃²⁻ to form insoluble white BaCO₃. Sodiumions remain in solution: Ba(OH)₂+Na₂CO₃→BaCO₃+2NaOH.',[RX],question='Mixing aqueous bariumhydroxide and sodiumcarbonate produces a whiteprecipitate of',options=['Bariumoxide','Sodiumcarbonate','Sodiumoxide','Sodiumhydroxide','Bariumcarbonate'],audit='Corrected false tetraoxocarbonatenames tocarbonate; independentionandatombalance supportsE.',check='carbonate-precipitation')
no(113,'Cfitsanalkene, butinternalalkynesalsodecolorisepermanganate anddonotform silveracetylides. FailurewithammoniacalAgNO₃onlyrulesoutterminalalkynes, notallalkynes. SourcecannotuniquelydistinguishC/D.',answer='C or internal alkyneD')
no(114,'NaOHinitiallyformsNa₂CO₃(C)withCO₂, butultimatelywithoutCO₂/humidityextent canleadtoNaHCO₃(D), alsoalkaline. Needsstatedreactionextentbeforeuniqueformula; donotturnambiguousultimateproductintocertainty.',answer='C initial carbonate stage')
yes(115,'D','The carboxylgroup is−C(=O)OH: a carbon atom bonded to both a carbonyl oxygen and a hydroxyl group. This combination distinguishes carboxylic acids from alcohols and ketones.',[ORG],question='Which is the functionalgroup of carboxylicacids?',options=['−OH','>C=O','>C−OH','−C(=O)OH','−C=N'],audit='VisuallytranscribedD carbonyl/OHbondsfromPDFpage12 intoexplicitcondensednotation; nofiguredependency remains. Retainedotherprintedfunctionalgroupchoices.')
yes(116,'E','Hydrogen is the most abundant chemicalelement in the universe. Much of its ordinary matter consists of hydrogen and helium, with heavier elements present in smaller proportions.',['https://science.nasa.gov/universe/glossary/'],question='Which listed substance is most abundant in the universe?',options=['Carbon','Air','Water','Oxygen','Hydrogen'],audit='RemovedQ41–42sharedpassagefromoptionE and restoredstandaloneitem; no unsupportednumericalpercentageclaim.')
passage='A colourless organiccompound X burns completely in excessair to give two colourless, odourless products,Y andZ. X doesnot decolourise bromine underordinary conditions. Y turns limewater milky; Z turns white anhydrous copper(II)sulfate blue.\n\n'
yes(117,'B','An alkane burns completely to give CO₂ and water. It doesnot rapidly decolourise bromine without light-induced substitution. Alkenes and alkynes decolourise bromine by addition; the chlorinated alternatives would also produce chlorine-containing products.',['https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons',RX],question=passage+'Which listed class contains compoundX?',options=['Analkene','Analkane','Analkyne','Tetrachloromethane','Dichloromethane'],audit='RestoredsharedpassagefromPDFpage13; clarifiedanhydrousCuSO₄testandordinarybromineconditions. Correctedgas/grammarerrorswithoutpublishinghistory.')
yes(118,'D','Carbon dioxide turns limewater milky by forming calciumcarbonate. Water turns white anhydrous CuSO₄ blue as it becomes hydrated. ThereforeY isCO₂ andZ isH₂O.',[RX,'https://edu.rsc.org/experiments/reversible-reactions/1708.article'],question=passage+'What areY andZ respectively?',options=['CO₂ andNH₃','CO andNH₃','SO₂ andH₂O','CO₂ andH₂O','SO₂ andNH₃'],audit='Recoveredsharedcombustion/testpassage andanhydrouscoppersulfatespecification; retainedD afterindependenttests.')
no(119,'B is conventionalintended because sodiumburns toperoxideNa₂O₂ inexcessoxygen, while limitedoxygen canyieldNa₂O. Sourceheatedinairlacksconditions andactualmetalproductsdependtemperature/oxygenavailability. OldC isunsupportedbecauseCuOisvalid. Needclarifiedburning/excessaircontext.',answer='B intended in excess oxygen')
yes(120,'E','Marble is mainly CaCO₃. Strongheating decomposes it to CaO andCO₂. The CaO reacts with water to form calciumhydroxide: CaO+H₂O→Ca(OH)₂, giving an alkalinesolution.',[RX],question='Marble heated to1473K gives a whitesolid that reacts vigorously with water to form an alkalinesolution. Which compound is in the solution?',options=['NaOH','KOH','Mg(OH)₂','Zn(OH)₂','Ca(OH)₂'],check='lime-cycle')
assert len(rows)==40
# Keep learner copy naturally spaced; chemical formulae remain compact.
replacements={
 'at323K':'at 323 K','pressure at323K':'pressure at 323 K','373.0K,351.3K,383.6K and372.5K':'373.0 K, 351.3 K, 383.6 K and 372.5 K',
 'are373.0':'are 373.0','at323.0K':'at 323.0 K','below7':'below 7','above7':'above 7','and(iv)':'and (iv)',
 'and(v)':'and (v)','sample1':'sample 1','Sample1':'Sample 1','sample2':'sample 2','Sample2':'Sample 2',
 'Q=It=0.193×(2×3600)=1389.6C':'Q = It = 0.193 × (2 × 3600) = 1389.6 C',
 'molesCu=1389.6/(2×96500)=0.0072mol':'moles of Cu = 1389.6/(2 × 96500) = 0.0072 mol',
 'is0.0072×63.5=0.4572g':'is 0.0072 × 63.5 = 0.4572 g','is0.457g':'is 0.457 g',
 'of0.193A':'of 0.193 A','for2hours':'for 2 hours','Assuming100%current':'Assuming 100% current',
 'Cu=63.5; F=96500Cmol⁻¹':'Cu = 63.5; F = 96500 C mol⁻¹',
 'state+3':'state +3','contributes+1':'contributes +1','contributes+3':'contributes +3',
 'contribute−4':'contribute −4','from+7 to+2':'from +7 to +2','In2Mn':'In 2Mn',
 'slakedlime':'slaked lime','bleachingpowder':'bleaching powder','Brownianmotion':'Brownian motion',
 'at+4':'at +4','becomes+3':'becomes +3','and+5':'and +5',
 'bariumhydroxide':'barium hydroxide','sodiumcarbonate':'sodium carbonate','whiteprecipitate':'white precipitate',
 'Bariumoxide':'Barium oxide','Sodiumcarbonate':'Sodium carbonate','Sodiumoxide':'Sodium oxide','Sodiumhydroxide':'Sodium hydroxide','Bariumcarbonate':'Barium carbonate',
 'carboxylgroup':'carboxyl group','is−C':'is −C','functionalgroup':'functional group','carboxylicacids':'carboxylic acids','chemicalelement':'chemical element',
 'organiccompound':'organic compound','excessair':'excess air','products,Y andZ':'products, Y and Z','doesnot':'does not','underordinary':'under ordinary',
 'copper(II)sulfate':'copper(II) sulfate','compoundX':'compound X','Analkene':'An alkene','Analkane':'An alkane','Analkyne':'An alkyne',
 'calciumcarbonate':'calcium carbonate','ThereforeY isCO₂ andZ isH₂O':'Therefore Y is CO₂ and Z is H₂O','areY andZ':'are Y and Z',
 'andNH₃':'and NH₃','andH₂O':'and H₂O','Strongheating':'Strong heating','andCO₂':'and CO₂','calciumhydroxide':'calcium hydroxide',
 'alkalinesolution':'alkaline solution','to1473K':'to 1473 K','whitesolid':'white solid','Sodiumions':'Sodium ions',
}
for row in rows:
 if row['publication_candidate']:
  u=row['update']
  for field in ('question','ai_explanation'):
   for old,new in replacements.items():u[field]=u[field].replace(old,new)
  for k,val in u['options'].items():
   for old,new in replacements.items():val=val.replace(old,new)
   u['options'][k]=val
  row['independent_reasoning']=u['ai_explanation']
  if row['calculation_check']=='nist-vapour-pressure':
   row['calculation_evidence']={
    'temperature_K':323,'equation':'log10(P/bar) = A - B/(T/K + C)',
    'ethanol':{'A':5.24677,'B':1598.673,'C':-46.424,'range_K':[292.77,366.63]},
    'water':{'A':5.20389,'B':1733.926,'C':-39.485,'range_K':[304,333]},
    'toluene':{'A':4.08245,'B':1346.382,'C':-53.508,'range_K':[303,343]},
    'butan_2_ol_anchor':{'A':4.32943,'B':1158.672,'C':-104.683,'range_K':[345.54,380.30],'anchor_K':372},
    'butan_2_ol_enthalpy':{'equation':'DeltaHvap/kJmol = A exp(-alpha Tr) (1-Tr)^beta; Tr=T/Tc','A':52.6,'alpha':-1.462,'beta':1.0701,'Tc_K':536,'range_K':[298,372]},
    'method':'Three in-range Antoine evaluations; butan-2-ol pressure estimated by integrating dlnP/dT=DeltaHvap/(RT²) from372K to323K using the in-range NIST enthalpy correlation. This is a vapour-pressure approximation; the ranking has a large margin, not an exact pressure claim.'}
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-003','reviewed_at':'2026-09-12','reviewer':'Codex(AI),independentchemistryreview','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalizedrecords81–120:one1984record,37labelled1985andtwoactual1986records. PDFpages9–13visuallyinspected. Ironoxidequestionsequence7confirmedbetween6and8. No omittedquestionscounted.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-003.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
