"""Private Chemistry review, normalized records 561–600. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][560:600]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==1995:return 46
 if q['year']==1997:return 49
 if q['year']==1999:return 53
 return 50 if q['num']<=9 else 51 if q['num']<=24 else 52 if q['num']<=39 else 53

def yes(i,a,e,urls,*,question=None,options=None,year=None,num=None,audit='',check=None):
 q=qs[i-561];u=copy.deepcopy(q)
 if year:u['year']=year
 if num:u['num']=num
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['has_diagram']=False;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-561];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})
ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
CARB='https://edu.rsc.org/resources/carbonyl-chemistry-16-18/4010284.article'
ACID='https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'
CAT='https://openstax.org/books/chemistry-2e/pages/12-7-catalysis'

no(561,'Neoprene is independently polychloroprene, but the printed sodium polymerisation condition needs verification; primary ACS history describes chloroprene polymerisation without establishing sodium as this initiator. Hold this exact process claim rather than silently delete the condition.',answer='D polymer identity')
no(562,'Actual1995Q47 on PDF46. Carbonyl CHO end is visible, but printed backbone CH₃CH₂=CH₂ has impossible valence and lacks a carbonyl bond. Need intact matching structure rather than reconstruct a plausible aldehyde from the key.',year=1995,answer='B intended aldehyde')
yes(563,'C','KOH provides 0.025 × 0.02 = 0.00050 mol OH⁻. A monobasic acid reacts with it in a 1:1 ratio, giving molar mass 0.030/0.00050 = 60 g mol⁻¹. CH₃COOH has this molar mass: 2(12) + 4(1) + 2(16) = 60.',[RX],question='25 cm³ of 0.02 mol dm⁻³ KOH neutralises 0.030 g of a monobasic organic acid of general formula CₙH₂ₙ₊₁COOH. Which formula represents the acid? [C = 12, H = 1, O = 16]',options=['HCOOH','C₂H₅COOH','CH₃COOH','C₃H₇COOH'],audit='Corrected old D to C, removed following Fehling question. General molar mass is14n+46, so n=1, not old14n+45 and n=3.',check='organic-acid-mass')
no(564,'Actual1995Q48 on PDF46. Atom balance gives C₃H₄, not oldC₃H₆. Propyne is consistent, but propadiene and cyclopropene also share that combustion formula. Source asks identity without a triple-bond premise; hold rather than assert propyne uniquely.',year=1995,answer='C consistent listed compound, C₃H₄ established')
yes(565,'B','Dibutylamine has two butyl groups bonded to nitrogen and one N–H bond, so it is a secondary amine. Methylamine is primary, trimethylamine is tertiary and propylene is a hydrocarbon.',[CARB,REB],year=1995,options=['Propylene','Dibutylamine','Methylamine','Trimethylamine'],audit='Actual1995Q49 on PDF46; stable ID retained. Restored C boundary and amine name spelling.')
yes(566,'D','Alcohol molecules form intermolecular hydrogen bonds through their O–H groups. More energy is needed to separate the molecules, giving relatively high boiling points compared with similar-sized molecules without this hydrogen bonding.',[REB],year=1995,question='The relatively high boiling points of alkanols are mainly due to',options=['Ionic bonding','Aromatic character','Covalent bonding','Hydrogen bonding'],audit='Actual1995Q50 on PDF46; stable ID retained.')
yes(567,'B','Calcium oxide reacts with water to form calcium hydroxide: CaO + H₂O → Ca(OH)₂. Formation of a new substance makes it a chemical change. The reaction releases heat.',[RX],check='lime-hydration')
yes(568,'A','Each solution contains 0.200 × 0.100 = 0.0200 mol solute. Pb²⁺ + 2Cl⁻ → PbCl₂ requires two chloride ions per lead ion, so chloride limits the precipitate to 0.0100 mol. M(PbCl₂) = 207 + 2(35.5) = 278 g mol⁻¹, giving 2.78 g.',[RX],year=1999,question='200 cm³ each of 0.1 mol dm⁻³ lead(II) nitrate and hydrochloric acid are mixed. Assuming lead(II) chloride is completely insoluble, what mass precipitates? [Pb = 207, Cl = 35.5]',options=['2.78 g','5.56 g','8.34 g','11.12 g'],audit='Actual1999Q1 on PDF53. Preserved explicitly stated complete-insolubility model; corrected old B to A by limiting reagent.',check='lead-precipitate')
yes(569,'B','The amount of gas is 0.05600/22.4 = 0.00250 mol. Its molar mass is 0.11/0.00250 = 44 g mol⁻¹. Vapour density relative to hydrogen is half the relative molecular mass, so it is 22.00.',[GAS],year=1999,question='56.00 cm³ of a gas at STP weighs 0.11 g. What is its vapour density relative to hydrogen? [Molar gas volume at STP = 22.4 dm³ mol⁻¹]',options=['11.00','22.00','33.00','44.00'],audit='Actual1999Q2 on PDF53. Corrected old A to B and false density units; standard hydrogen reference explicit.',check='vapour-density')
no(570,'X atomic mass or identity is missing, so masses only determine equivalent mass, not X valence. Several options also lose sulfate subscripts or Cu coefficients. Cannot inferX48/Cd from old key or substitute a plausible element; require complete source premise/options.')
yes(571,'A','The equation shows one mole, or one gas volume at equal conditions, of propane requires five of oxygen. Therefore 50 cm³ propane needs 5 × 50 = 250 cm³ oxygen.',[GAS,RX],question='C₃H₈(g) + 5O₂(g) → 4H₂O(g) + 3CO₂(g). What volume of oxygen at STP is needed to burn 50 cm³ of propane measured at STP?',options=['250 cm³','150 cm³','100 cm³','50 cm³'],check='propane-volume')
yes(572,'C','The initial hydrogen partial pressure is 780 − 10 = 770 mmHg. Use absolute temperatures 300 K and 280 K: V₂ = 30 × (770/760) × (280/300) = 28.37 cm³, or 28.4 cm³.',[GAS],question='30 cm³ of hydrogen is collected over water at 27 °C and total pressure 780 mmHg. Taking the given water-vapour pressure as 10 mmHg, calculate the dry hydrogen volume at 760 mmHg and 7 °C. Use T(K) = t(°C) + 273.',options=['40.0 cm³','35.7 cm³','28.4 cm³','25.2 cm³'],audit='PDF50 visually shows7 with superscriptdegree, not70°C. Corrected old D to C; retained stipulated vapour pressure as problem datum without asserting it is actual saturated water vapour at27°C.',check='wet-gas-correction')
yes(573,'C','M(SO₂) = 32 + 2(16) = 64 g mol⁻¹ and M(CH₄) = 12 + 4 = 16 g mol⁻¹. Graham’s law gives R(SO₂)/R(CH₄) = √(16/64) = 1/2. Thus the rate ratio is 1:2.',[GAS],question='Sulfur dioxide and methane are released simultaneously at opposite ends of a narrow tube under the same conditions. What is the ratio R(SO₂):R(CH₄)? [S = 32, O = 16, C = 12, H = 1]',options=['4:1','2:1','1:2','1:4'],check='diffusion-ratio')
yes(574,'B','The two outer electrons can be transferred to two chlorine atoms. This produces a metal cation and chloride anions, held together by electrostatic attraction: an ionic, or electrovalent, bond.',[REB],question='An atom is shown with four occupied electron shells and two electrons in the outermost shell. When it combines with chlorine, which type of bond is formed?',options=['Covalent bond','Electrovalent bond','Hydrogen bond','Coordinate bond'],audit='PDF50 atom image visually inspected. Four concentric occupied shells and two diametrically opposite outer electrons provide complete relevant context; replaced missing diagram with accessible description.')
no(575,'D=2,8,8,7 is not a normal ground-state shell configuration; it sums25 and cannot represent chlorine as old explanation claims. A=chlorine is independently strongest among unambiguous A-C, but D needs an intact original (possibly2,8,18,7). Do not invent that repair.',answer='A among standard configurations')
yes(576,'C','An electron moving from a higher to a lower energy level emits a photon with energy equal to the level difference. Hydrogen’s discrete energy levels produce separate spectral lines.',[REB],question='The lines in the hydrogen emission spectrum result from emission of',options=['Electrons from the atom','Energy during proton transitions','Energy during electron transitions','Neutrons from the atom'],audit='Removed unrelated next nuclear-equation question.')
yes(577,'A','Fractional distillation of liquid air separates nitrogen and oxygen because they have different boiling points. The more volatile nitrogen boils off before oxygen.',[REB],question='Which property is used to separate nitrogen and oxygen by industrial fractional distillation of liquid air?',options=['Boiling point','Density','Rate of diffusion','Solubility'],audit='Specified the distillation method already implied by the source industrial separation question; other industrial methods need not use boiling point.')
yes(578,'C','Burning excess phosphorus removes oxygen from the air. Potassium hydroxide absorbs carbon dioxide and other acidic oxides, and concentrated sulfuric acid removes water vapour. Nitrogen and the noble gases remain.',[REB],question='Excess phosphorus is burned in a gas jar of air. The residual gas passes through concentrated KOH solution and then concentrated H₂SO₄. Which gases are collected?',options=['Carbon dioxide, nitrogen and noble gases','Nitrogen dioxide and noble gases','Nitrogen and noble gases','Carbon dioxide, nitrogen dioxide and noble gases'],audit='Made ordinary air-filled gas-jar context explicit; restored oxide names and complete option boundaries.')
no(579,'Reduce organic impurities can mean decrease their amount rather than redox reduction, and permanganate also oxidises organic contaminants. C is a known effect but source does not distinguish chemical-reduction meaning from ordinary removal meaning. Hold ambiguous A/C rather than teach that organic-impurity removal cannot occur.')
no(580,'Battery technology is unspecified. The intended Pb answer assumes lead-acid manufacture, while other battery chemistries have different materials. A factory alone does not imply contaminated soil. Hold for an original lead-battery/pollution premise rather than add one.',answer='B if lead-acid contamination is specified')
no(581,'Solubility in mol dm⁻³ refers to solution volume, but50cm³ is solvent water. At8M the volume-change approximation is not justified.52g follows an unstated50cm³ final-solution assumption; hold rather than equate solvent and solution volume.',answer='A under unstated constant-volume approximation')
yes(582,'C','Soap lather is a foam: bubbles of gas are dispersed through a liquid film. Thus its dispersed phase is gas and its continuous phase is liquid.',[REB],question='Soap lather is a colloid in which',options=['Liquid is dispersed in gas','Solid is dispersed in liquid','Gas is dispersed in liquid','Liquid is dispersed in liquid'],audit='Corrected leather→lather and old B→C by foam definition; matching Myschool1998 listing also spells lather.')
yes(583,'D','Initial amounts are 0.010 mol HCl and 0.020 mol NaOH. After neutralisation, 0.010 mol OH⁻ remains in 0.200 dm³, so [OH⁻] = 0.050 mol dm⁻³. pOH = 1.30 and pH = 14.00 − 1.30 = 12.70.',[ACID],question='At 25 °C, what is the pH after mixing 100 cm³ of 0.1 mol dm⁻³ HCl with 100 cm³ of 0.2 mol dm⁻³ NaOH, assuming additive volumes?',check='mixed-ph')
no(584,'Hydrated ions are ions, so optionsA andC both describe the charge carriers. Need a distinguishing bare-ions option or most-specific criterion from original source; sulfate Roman numeral also wrong. Do not present the general term ions as scientifically false.')
yes(585,'D','M(Na₂CO₃·10H₂O) = 106 + 180 = 286 g mol⁻¹. The sample contains 2.86/286 = 0.0100 mol carbonate. H₂SO₄ reacts with carbonate in a 1:1 ratio, so the required volume is 0.0100/0.100 = 0.100 dm³ = 100 cm³.',[RX],question='What volume of 0.1 mol dm⁻³ sulfuric acid is needed to react completely with 2.86 g of sodium carbonate decahydrate, Na₂CO₃·10H₂O? [Na = 23, C = 12, H = 1, O = 16]',options=['20 cm³','40 cm³','80 cm³','100 cm³'],audit='Corrected old B/nearest40 claim to exact D. Repaired sulfuric acid name and made intended complete acid-carbonate reaction explicit rather than simple physical dissolution.',check='carbonate-titration')
no(586,'Charge unit missing after1.2 in supplied PDF51; separate copies indicateF but full matching readable examination source not yet inspected. Metal deposition also requires suitable nonaqueous/molten conditions forNa/Al. Hold exact record pending unit/source recovery; B follows1.2F and full current efficiency.',answer='B under stated missing conditions')
yes(587,'A','The charge is Q = It = 15 × 193 = 2895 C, equivalent to 0.0300 mol electrons. Gold(III) needs three electrons per atom, so 0.0100 mol gold is deposited. Its mass is 0.0100 × 197 = 1.97 g.',[EL,'https://periodic-table.rsc.org/element/79/gold'],question='What mass of gold is deposited from gold(III) sulfate when 15 A passes for 193 s, assuming full current efficiency? [Au = 197; F = 96,500 C mol⁻¹]',options=['1.97 g','3.94 g','5.91 g','19.70 g'],audit='Corrected printed universal constants Au97→197 using RSC atomic weight196.967, F965000→96500 using standard electrolysis reference; no experimental datum changed. Corrected old C→A by charge and3-electron requirement.',check='gold-electrolysis')
yes(588,'D','Cu²⁺ gains two electrons to form copper, so it is reduced. The substance that accepts electrons and causes the other substance to be oxidised is the oxidising agent.',[RX],question='Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Which statement follows?',options=['Fe is the oxidising agent','Fe is reduced','Cu²⁺ loses electrons','Cu²⁺ is the oxidising agent'],check='iron-copper-redox')
yes(589,'A','Iron changes from +2 in FeCl₂ to +3 in FeCl₃. FeCl₂ is therefore oxidised and supplies the electrons that reduce chlorine, making it the reducing agent.',[RX],question='In 2FeCl₂(s) + Cl₂(g) → 2FeCl₃(s), which is the reducing agent?',options=['FeCl₂','Cl₂','FeCl₃','Fe'],check='iron-chloride-redox')
no(590,'Several phase labels missing and optionD has2N₂H₄ yielding3N₂+4H₂O with no oxygen source. B is expected gas-mole decrease, but a full accurate option set requires matching reactionD rather than an invented oxidant or omitted species.',answer='B intended')
no(591,'Dissolution releases13kJ per0.2mol, so thermodynamic heat of solution is−65kJmol⁻¹. All choices are positive. Need matching signed option or explicit magnitude wording; do not remove the minus sign or invent a magnitude-only question.',answer='−65kJmol⁻¹, no signed option')
no(592,'Mg product is missing and source Cu²⁺/Cu potential is+0.403V instead of standard approximately+0.340V. Matching copies repairCu but corrupt Mg/Cd signs. Hold until complete coherent source table verified; oldD is independently suggested by Mg most negative value.',answer='D')
yes(593,'C','For the backward reaction, the starting energy is the product level, 15 kJ. The peak is 40 kJ, so the backward activation energy is 40 − 15 = 25 kJ.',[CAT],question='An energy diagram for P₂ + Q₂ → 2PQ places reactants at 10 kJ, products at 15 kJ and the peak at 40 kJ. What is the activation energy for the backward reaction?',options=['+5 kJ','+15 kJ','+25 kJ','+30 kJ'],audit='PDF52 graph visually transcribed: reactants10, products15, peak40. Corrected guessed oldD to C; no missing-figure dependency.',check='reverse-activation')
yes(594,'D','Independence from [Y] means order zero in Y. Doubling [X] multiplies the rate by four, so 2ⁿ = 4 and n = 2. Therefore R = k[X]²[Y]⁰ = k[X]².',[REB,'https://myschool.ng/classroom/chemistry/13911?exam_type=jamb&page=195'],question='For 2X(g) + Y(g) → Z(g), the rate of formation of Z is independent of [Y] and quadruples when [X] doubles. Which rate law agrees?',options=['R = k[X][Y]','R = k[X]²[Y]','R = k[X]²[Y]²','R = k[X]²[Y]⁰'],audit='Readable matching Myschool13911 restores missing when[X]doubles premise. Distractor exponents taken from visually complete PDF52, not malformed web notation.',check='rate-orders')
yes(595,'A','The positive ΔH means the forward reaction absorbs heat. Cooling favours the exothermic reverse direction, shifting the equilibrium towards chlorine and water vapour.',['https://openstax.org/books/chemistry-2e/pages/13-3-shifting-equilibria-le-chateliers-principle'],question='2Cl₂(g) + 2H₂O(g) ⇌ 4HCl(g) + O₂(g), ΔH° = +115 kJ mol⁻¹. How does decreasing temperature affect the equilibrium?',options=['Favours the reverse reaction','Favours the forward reaction','Has no effect on equilibrium','Doubles the rate of the reverse reaction'])
yes(596,'C','Nitrogen in NH₃ has oxidation number −3 and becomes 0 in N₂ in each equation. Ammonia is oxidised while the other reactant is reduced, demonstrating that ammonia acts as a reducing agent.',[RX,'https://myschool.ng/classroom/chemistry/13915?exam_year=1998&page=5'],question='Consider: (i) 3CuO(s) + 2NH₃(g) → 3Cu(s) + 3H₂O(l) + N₂(g); (ii) 2NH₃(g) + 3Cl₂(g) → 6HCl(g) + N₂(g); (iii) 4NH₃(g) + 3O₂(g) → 6H₂O(l) + 2N₂(g). Which property of ammonia do these reactions demonstrate?',options=['Basic properties','Acidic properties','Reducing properties','Oxidising properties'],audit='Full readable Myschool13915 confirms complete equations including O₂ iniii, N₂ and no spurious HCl/H₂O additions. Not an inferred replacement ofCl₂ byO₂. Independently atom-balanced allthree.',check='ammonia-redox')
no(597,'PDF52 gas collection image explicitly labels N₂, so old A/NO explanation is wrong. B is intended sodium nitrite with NH₄Cl, but its name prints trioxonitrate(III). Matching Myschool31559 repeats that malformed name; need readable complete chemical identification rather than infer a nitrate-to-nitrite replacement solely from desired gas.',answer='B intended NaNO₂/NH₄Cl nitrogen preparation')
no(598,'Unqualified remains unchanged when heated in hydrogen lacks temperature/pressure conditions; ZnO can be reduced by hydrogen under sufficiently strong conditions. Old explanation incorrectly uses Zn above hydrogen to exclude reduction even while allowing Fe₂O₃. Hold for bounded original laboratory condition.',answer='D school laboratory comparison')
no(599,'PDF52 itself has metal names as options to a precipitation-observation question, apparently borrowed from another question. Independent result is reddish-brown Fe(OH)₃, which is absent. Need correct original option set; cannot turn iron into a precipitate observation.',answer='Reddish-brown Fe(OH)₃ precipitate')
yes(600,'C','Alloying can improve properties needed for a use, such as hardness, strength or corrosion resistance. This is why a suitable alloy may be chosen over a pure metal; the improvement depends on the alloy and application.',['https://edu.rsc.org/resources/iron-and-steel/23.article'],question='Why are alloys often preferred to pure metals for practical applications?',options=['Pure metals are too hard','Pure metals are ductile','Useful metallic properties can be improved by alloying','All alloys are mixtures only of metals'],audit='Removed next-structure spillover and qualified improvement by application; retained D as false universal metal-only definition.')
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-015','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry records561–600. Actual1995,1997,1998 and1999 source years, stable IDs preserved. PDF46,49–53 visually inspected.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-015.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
