"""Private Chemistry review, normalized records 801–840. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][800:840]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==2003:return 67 if q['num']==41 else 68
 return 68 if q['num']<=11 else 69 if q['num']<=32 else 70

def yes(i,a,e,urls,*,question=None,options=None,year=None,num=None,audit='',check=None):
 q=qs[i-801];u=copy.deepcopy(q)
 if year:u['year']=year
 if num:u['num']=num
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['has_diagram']=False;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-801];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})
ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
CARB='https://edu.rsc.org/resources/carbonyl-chemistry-16-18/4010284.article'
ACID='https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'
CAT='https://openstax.org/books/chemistry-2e/pages/12-7-catalysis'

yes(801,'C','Simple monosaccharides such as glucose have the general formula (CH₂O)ₙ, giving C:H:O = 1:2:1. This ratio is not universal for every carbohydrate; polysaccharide formation removes water.',[ORG],question='For a simple monosaccharide represented by (CH₂O)ₙ, what is the C:H:O atom ratio?',options=['3:1:1','2:1:1','1:2:1','1:1:1'],audit='Restricted overgeneralised carbohydrate claim; removed merged pentane question.',check='carbohydrate-ratio')
yes(802,'A','Butanoate contributes CH₃CH₂CH₂COO–, written C₃H₇COO–. The ethyl group attached through oxygen is C₂H₅, so ethyl butanoate is C₃H₇COOC₂H₅.',[ORG],question='The condensed structural formula of ethyl butanoate is',options=['C₃H₇COOC₂H₅','C₂H₅COOC₃H₇','C₄H₉COOC₂H₅','C₂H₅COOC₄H₉'],audit='Corrected C→A: carbonyl carbon counts within four-carbon butanoate.',check='ester-carbon-count')
yes(803,'D','Benzene characteristically undergoes electrophilic substitution, replacing a ring hydrogen while restoring its aromatic electron system. Addition is possible under more forcing conditions but is not its characteristic reaction.',[ORG],question='Which reaction type is characteristic of benzene?',options=['Addition','Hydrolysis','Polymerisation','Substitution'])
yes(804,'D','Excess acidified dichromate oxidises ethanol through ethanal to ethanoic acid. Heating under reflux retains volatile material and allows oxidation to the carboxylic acid.',[ORG],question='On heating under reflux with excess acidified K₂Cr₂O₇, ethanol forms',options=['Ethanedioic acid','Ethanol','Ethyl ethanoate','Ethanoic acid'],audit='Completed missing product-directed stem and standard reflux condition.')
no(805,'Both platinum and carbon can serve as inert anodes for brine electrolysis. No specified industrial or laboratory cell distinguishes them. Cannot make carbon uniquely correct without inserting new cell premise.')
yes(806,'A','The product side has two moles of gas for each mole of N₂O₄. Decreasing pressure by expansion at fixed temperature favours the side with more gas molecules, producing more NO₂.',[REB],question='For N₂O₄(g) ⇌ 2NO₂(g), which change at fixed temperature favours more product?',options=['A decrease in pressure by expansion','A decrease in volume','An increase in pressure by compression','Keeping volume constant'],check='equilibrium-gas-moles')
yes(807,'C','In neutral HClO₄, hydrogen is +1 and four oxygen atoms total −8. Therefore 1 + x − 8 = 0, so chlorine is +7.',[RX],question='What is chlorine’s oxidation state in HClO₄?',options=['−1','−5','+7','+1'],check='chlorine-oxidation')
yes(808,'C','At 298.15 K, standard molar gas entropies are approximately HF 173.8, HCl 186.9, HBr 198.7 and HI 206.6 J mol⁻¹ K⁻¹. HI has the largest value in this series.',['https://openstax.org/books/chemistry/pages/g-standard-thermodynamic-properties-for-selected-substances'],question='Which hydrogen halide has the highest standard molar entropy as a gas at 298.15 K?',options=['HBr','HF','HI','HCl'],audit='Specified standard gaseous comparison; verified all four primary table entries, not mass trend alone.',check='entropy-ranking')
yes(809,'A','For Ag⁺ + e⁻ → Ag, one mole of electrons deposits one mole of silver. Q = It = 10 × 4830 = 48,300 C. Mass = 48,300/96,500 × 108 = 54.055 g, or 54.1 g to one decimal place.',[EL],question='What mass of silver is deposited by a 10 A current through an Ag⁺ solution for 4830 s, at 100% current efficiency? [Ag = 108 g mol⁻¹; F = 96,500 C mol⁻¹]',options=['54.1 g','27.0 g','13.5 g','108.0 g'],audit='Source A54.0 updated54.1 for supplied4830s/F96500; retained all numerical inputs and explained correct rounding.',check='silver-faraday')
no(810,'SO2 acts as both agents, but H2 does too: oxidised toH+ with nonmetals and reduced toH− in metal hydrides. Broad stem has multiple valid answers; no specified reaction context.')
yes(811,'B','H₂ + I₂ ⇌ 2HI has two moles of gas on each side. Compression at fixed temperature scales numerator and denominator of its pressure quotient equally, so it causes no equilibrium shift in the ideal-gas approximation.',[REB],question='Which ideal-gas equilibrium does not shift when volume decreases at fixed temperature?',options=['2O₃(g) ⇌ 3O₂(g)','H₂(g) + I₂(g) ⇌ 2HI(g)','2NO₂(g) ⇌ N₂O₄(g)','PCl₅(g) ⇌ PCl₃(g) + Cl₂(g)'],audit='Restored all gas states/equilibrium arrows; removed following CO question from D.',check='equal-gas-moles')
no(812,'Source equation2CO+O2→2CO2 gives2(-393)-2(-110.4)=−565.2kJ. A−282.6 is per moleCO, not equation as stated. No explicit per-mole basis; do not halve equation or assume missing normalisation.')
yes(813,'C','Zinc is +2 in ZnO and 0 in elemental Zn. The decrease in oxidation number means zinc is reduced; carbon monoxide is oxidised to carbon dioxide.',[RX],question='In ZnO + CO → Zn + CO₂, zinc has been',options=['Displaced','Oxidised','Reduced','Decomposed'],audit='Restored complete reaction from PDF68 preceding equation.',check='zinc-reduction')
yes(814,'D','CaCO₃ + 2HCl → CaCl₂ + CO₂ + H₂O. The carbonate molar mass is 100 g mol⁻¹, so 2 g gives 0.020 mol CO₂. Volume = 0.020 × 22.4 = 0.448 dm³ = 448 cm³.',[RX],question='What volume of CO₂ at s.t.p. is formed when 2 g of CaCO₃ reacts completely with excess HCl? [Ca = 40, C = 12, O = 16; molar gas volume = 22.4 dm³ mol⁻¹]',options=['224 cm³','112 cm³','2240 cm³','448 cm³'],audit='Corrected B→D independently; made complete reaction/excess condition explicit.',check='carbonate-gas')
yes(815,'A','Sublimation is the direct change from solid to gas without passing through the liquid state. Evaporation begins with a liquid, while crystallisation forms a solid.',[REB],question='A solid changes directly into gas on heating without becoming liquid. This process is',options=['Sublimation','Crystallisation','Distillation','Evaporation'])
yes(816,'D','CuO + H₂SO₄ → CuSO₄ + H₂O is a 1:1 reaction. The acid amount is 4.9/98 = 0.050 mol. The required CuO mass is 0.050 × 80 = 4.0 g.',[RX],question='What mass of CuO reacts completely with 4.9 g of H₂SO₄? [Cu = 64, O = 16, S = 32, H = 1]',options=['40.0 g','80.0 g','0.8 g','4.0 g'],check='copper-oxide-acid')
no(817,'Vulcanisation forms crosslinks; removal of a double bond is not a universal accurate mechanism, with allylic sulfur links and rearrangements possible. No crosslink option; cannot teach simplistic bond-removal as general definition.')
yes(818,'C','An acyclic saturated alkyl group is formed by removing one hydrogen from an alkane, CₙH₂ₙ₊₂. Its formula is therefore CₙH₂ₙ₊₁–.',[ORG],question='The general formula of an acyclic saturated alkyl group is',options=['CₙH₂ₙ','CₙH₂ₙ₋₂','CₙH₂ₙ₊₁','CₙH₂ₙ₊₂'],check='alkyl-formula')
yes(819,'D','Concentrated sulfuric acid at about 180 °C dehydrates ethanol: C₂H₅OH → C₂H₄ + H₂O. The product is ethene.',[ORG],question='Ethanol is heated with concentrated H₂SO₄ at 180 °C. Which organic product forms?',options=['C₂H₅COOH','CH₄','CH₃OCH₃','C₂H₄'],audit='Restored temperature and reagent from complete PDF69 reaction.',check='ethanol-dehydration')
yes(820,'C','Concentrated sodium chloride lowers the solubility of sodium soaps in the aqueous mixture, allowing soap to separate. This separation is called salting out.',[REB],question='During soap production, concentrated NaCl solution is added to',options=['Saponify the soap','Emulsify the soap','Decrease the soap’s solubility','Increase the soap’s solubility'])
yes(821,'A','Acetylene burns in oxygen with a concentrated, high-temperature flame. The heat can melt the metal locally so a weld can form.',[ORG],question='An oxyacetylene flame is useful for welding iron because it',options=['Releases a large amount of heat during combustion','Dissociates to produce carbon dioxide and oxygen','Makes the metal solidify very quickly','Combines with oxygen to give a pop sound'],audit='PDF69 unlettered fourth option separated from C; spelling lot restored. No source text missing.',check='acetylene-combustion')
no(822,'AmmoniacalCuCl detects terminal alkynes, not every triple bond. Bromine and permanganate also react with alkenes. Stem omits terminal condition and reagent medium; cannot change general claim into terminal-specific original question.')
no(823,'PDF69 branch/bond positions visually displaced: printed CH2 bears vertical bonds while adjacent C lacks them; extracted text suggests2,3 but cannot infer from answer. MatchingMyschool31618 page present but image tool failed; requires legible structure recovery.')
yes(824,'C','2-Methylbutane has five carbon atoms and molecular formula C₅H₁₂. Butane and 2-methylpropane have only four carbons; the structure labelled 2-ethylbutane has six.',[ORG],question='Which listed structure has molecular formula C₅H₁₂?',options=['2-Ethylbutane','Butane','2-Methylbutane','2-Methylpropane'],audit='Separated unlettered fourth option from C using PDF69 line boundary.',check='pentane-isomer')
yes(825,'B','In the reverse direction, an ester reacts with water to form an alcohol and a carboxylic acid. This is ester hydrolysis. Alkaline hydrolysis producing a carboxylate salt is called saponification.',[ORG],question='Alcohol + carboxylic acid ⇌ ester + water. What is the reverse reaction called?',options=['Saponification','Hydrolysis','Fermentation','Hydration'])
yes(826,'C','The products contain carbon dioxide and a hydrocarbon with one fewer carbon atom than the acid. Removal of the carboxyl group as CO₂ is decarboxylation.',[ORG],question='The transformation CH₃COOH(g) → CH₄(g) + CO₂(g) is classified as',options=['Acidification','Esterification','Decarboxylation','Carboxylation'],audit='Separated D from C; classifies displayed net transformation without claiming spontaneous ambient conversion.',check='decarboxylation')
yes(827,'C','Acidic conditions often increase dissolution and mobility of metal-containing minerals. This can allow metal ions to leach through soil and contaminate groundwater.',[REB],question='Which soil condition commonly increases the leaching of many metal ions into groundwater?',options=['High alkalinity','High nitrate content','High acidity','High chloride content'],audit='Qualified many metals to avoid universal mobility claim.')
no(828,'20g CuSO4 in100g water gives moles but not solution volume for molarity; source180°C also requires pressure/density context. Cannot equate100g water to100cm³ solution or claim saturation without evidence.')
yes(829,'A','A normal salt contains no replaceable acidic hydrogen from incomplete neutralisation. Na₂CO₃ is the fully neutralised sodium salt of carbonic acid; NaHCO₃, NaHSO₄ and NaHS are acid salts. Normal salt does not mean its solution has neutral pH.',[ACID],question='Which compound is a normal salt rather than an acid salt?',options=['Na₂CO₃','NaHCO₃','NaHSO₄','NaHS'])
yes(830,'D','H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. NaOH amount = 0.020 × 0.1 = 0.0020 mol, requiring 0.0010 mol acid. Volume = 0.0010/0.5 = 0.0020 dm³ = 2.0 cm³.',[RX],question='What volume of 0.5 mol dm⁻³ H₂SO₄ exactly neutralises 20 cm³ of 0.1 mol dm⁻³ NaOH?',options=['5.0 cm³','6.8 cm³','8.3 cm³','2.0 cm³'],audit='Restored positive cubic volume units.',check='sulfuric-titration')
yes(831,'B','The dissolved portion of calcium sulfate exists as dispersed ions, forming a true solution. Its low solubility limits how much dissolves; it does not make the dissolved portion a colloid.',[REB],question='The small amount of calcium sulfate that dissolves in water forms a',options=['Colloid','Solution','Suspension','Precipitate'],audit='Corrected A→B; removed following hardness question from D and clarified dissolved portion.')
yes(832,'C','In a dilute gas, intermolecular attractions are weak compared with molecular kinetic energy. The molecules move freely and do not maintain the regular fixed arrangement found in a crystal.',[GAS],question='Gas molecules do not maintain a regular fixed arrangement chiefly because they',options=['Can collide with one another','Are too small','Have weak attractions relative to their kinetic energy','Have no definite shape'],audit='Removed page artifact; clarified gas regime and energetic comparison.')
yes(833,'D','An s orbital has spherical symmetry: its probability density at a given distance from the nucleus is independent of direction.',[REB],question='The symmetry of an s orbital is',options=['Elliptical','Spiral','Circular','Spherical'])
yes(834,'C','Hydrogen is combustible and can react with oxygen supplied by air. Neon is inert and acts as a diluent. The other listed mixtures contain no readily combustible gas.',[RX],question='Which mixture contains a gas that can burn when supplied with air and ignited?',options=['Helium and neon','Neon and nitrogen','Neon and hydrogen','Nitrogen and helium'],audit='Made external oxidant explicit; no claim sealed hydrogen/neon burns alone.')
yes(835,'A','Chlorine attracts bonding electrons more strongly than hydrogen, making H–Cl polar. In Cl–Cl the identical atoms share equally. The relevant property is electronegativity; molecular HCl is polar covalent.',[REB],question='Which property difference explains why H–Cl has greater bond polarity than Cl–Cl?',options=['Electronegativity','Electropositivity','Electron affinity','Electrovalency'],audit='Replaced misleading ionic-molecule claim with precise bond polarity.')
no(836,'PDF70 shows unrelated atomic-shell drawing instead of required gas experiment. X and removal stages absent. Matching web page has image link but image read failed; cannot infer inert gas from answer.')
yes(837,'A','A halogen atom has seven valence electrons. Gaining one electron forms a halide ion with a completed outer-shell octet.',[REB],question='A halogen atom gains one electron to form a halide ion with',options=['8 valence electrons','7 valence electrons','2 valence electrons','3 valence electrons'],check='halide-octet')
yes(838,'B','Extrapolating the ideal-gas Charles-law line gives zero volume at 0 K, approximately −273 °C. Real gases condense before reaching this extrapolated limit, so it is not a claim that a real gas physically occupies zero volume.',[GAS],question='Extrapolating Charles’ law for an ideal gas gives zero volume at approximately',options=['−100 °C','−273 °C','−373 °C','0 °C'],audit='Stated ideal extrapolation, not impossible real-gas volume claim.',check='absolute-zero')
yes(839,'A','Steam reacts with red-hot carbon: C + H₂O(g) → CO + H₂. The mixture of carbon monoxide and hydrogen is called water gas.',[RX],question='The principal products when steam passes over red-hot carbon are',options=['Hydrogen and carbon monoxide','Hydrogen and carbon dioxide','Hydrogen and carbonic acid','Hydrogen, oxygen and carbon dioxide'],check='water-gas')
yes(840,'D','A mordant helps fix a dye to a fibre. Aluminium hydroxide can bind dye molecules and support their attachment to the material.',[REB],question='Aluminium hydroxide is used in dyeing as a',options=['Dye','Dispersant','Salt','Mordant'])
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-021','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry801–840; source2003–2004. PDF67–70 visually inspected; full source context and independently solved answers.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-021.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
