"""Private Chemistry review, normalized records 641–680. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][640:680]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==1999:return 55 if q['num']<=36 else 56
 return 57 if q['num']<=18 else 58 if q['num']<=30 else 59

def yes(i,a,e,urls,*,question=None,options=None,year=None,num=None,audit='',check=None):
 q=qs[i-641];u=copy.deepcopy(q)
 if year:u['year']=year
 if num:u['num']=num
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['has_diagram']=False;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-641];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})
ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
CARB='https://edu.rsc.org/resources/carbonyl-chemistry-16-18/4010284.article'
ACID='https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'
CAT='https://openstax.org/books/chemistry-2e/pages/12-7-catalysis'

yes(641,'B','The enthalpy change is H(products) − H(reactants). A negative value of −65.7 kJ mol⁻¹ means that the products have lower enthalpy and heat is released. It does not determine the reaction speed.',[RX],question='RS(aq) + HF(aq) → RF(s) + HS(aq), ΔH = −65.7 kJ mol⁻¹. What can be deduced?',options=['The reactants have lower enthalpy than the products','The reactants have higher enthalpy than the products','The reaction is slow','A large amount of heat is absorbed'],audit='Restored arrow/Δ and repaired duplicated reactant/product wording in optionA.',check='enthalpy-sign')
no(642,'Direction down the electrochemical series is not defined; tables can be ordered by increasing or decreasing reduction potential. Several non-metal statements also depend on the chosen series convention. Need the actual ordered series or explicit convention, not an invented orientation.')
yes(643,'D','Hydrogen chloride dissolves to supply chloride ions. These react with silver ions to form white silver chloride: Ag⁺ + Cl⁻ → AgCl(s). Nitric-acid acidification suppresses interference from carbonate and sulfite precipitates.',[RX],question='Which gas forms a white precipitate when passed into aqueous silver nitrate acidified with nitric acid?',options=['NH₃','SO₂','CO₂','HCl'],audit='Standardized silver nitrate name and made acidification reagent explicit for the conventional halide test.')
yes(644,'A','All three halogens react with aqueous alkalis. For example, chlorine disproportionates in cold dilute alkali to chloride and hypochlorite. They are not all liquids, and halogen displacement works in the direction of decreasing oxidising strength rather than mutually in both directions.',[REB],question='Chlorine, bromine and iodine resemble one another in that they',options=['Dissolve in alkalis','React violently with hydrogen without heating','Are liquids','Displace one another from solutions of their salts'],audit='Corrected oldD→A; mutual displacement claim is false.')
yes(645,'B','Sodium sulfite reacts with acid to release sulfur dioxide: Na₂SO₃ + 2HCl → 2NaCl + H₂O + SO₂. Its pungent gas reduces purple permanganate to Mn²⁺. Sodium sulfide instead gives hydrogen sulfide, characterised by a rotten-egg smell.',[RX,'https://myschool.ng/classroom/chemistry/1465?page=15'],question='Which salt reacts with dilute hydrochloric acid to produce a pungent-smelling gas that decolourises acidified purple potassium permanganate solution?',options=['Na₂SO₄','Na₂SO₃','Na₂S','Na₂CO₃'],audit='Recovered complete pungent-smelling premise from fully opened matching Myschool1465, all four options checked.',check='sulfite-acid')
yes(646,'A','Hydrogen combustion in oxygen releases substantial energy: 2H₂ + O₂ → 2H₂O. The resulting high-temperature flame provides heat for melting metals; low gas density is not the reason.',[RX],question='Hydrogen is used in oxyhydrogen flames for melting metals because it',options=['Evolves a lot of heat when burnt','Combines explosively with oxygen','Is a very light gas','Is a rocket fuel'])
yes(647,'A','Heating ammonium chloride with calcium hydroxide releases ammonia: 2NH₄Cl + Ca(OH)₂ → CaCl₂ + 2NH₃ + 2H₂O. Calcium oxide dries the ammonia without reacting with it as an acidic drying agent would.',[REB,'https://myschool.ng/classroom/chemistry/31569?filter=oldest','https://www.elearning.rtb.gov.rw/mod/book/tool/print/index.php?id=1026'],question='A heated flask contains mixture Y. Gas passes from the flask through a drying vessel containing calcium oxide, then into an inverted gas jar labelled ammonia. What is mixture Y?',options=['Calcium hydroxide and ammonium chloride','Calcium hydroxide and sodium chloride','Sodium chloride and ammonium nitrate','Sodium nitrite and ammonium chloride'],audit='PDF56 visually inspected: heatedYflask, CaOdryer, inverted ammoniajar fully described. Readable Myschool31569 restores optionB sodiumchloride without false(V). Removed old unsupported endothermic claim.',check='ammonia-preparation')
yes(648,'C','Duralumin is an aluminium alloy that combines low density with greater strength than pure aluminium. That strength-to-weight advantage makes it useful for structures where mass matters.',[REB],question='Which properties make duralumin especially useful compared with its constituent metals?',options=['Heavy with a high melting point','Malleable with high density','Strong and light','Hard and ductile'])
yes(649,'B','Magnesium and calcium are highly reactive metals for which electrolysis of molten compounds is an established extraction route. Zinc, copper and lead can be obtained by chemical reduction routes instead.',[EL,REB],question='Which listed pair of reactive metals is extracted by electrolysis of suitable molten compounds?',options=['Magnesium and zinc','Magnesium and calcium','Copper and zinc','Lead and calcium'],audit='Clarified ores require suitable molten compounds rather than direct electrolysis of raw rock; no claim electrolysis is the only modern industrial route.')
yes(650,'A','Concentrated nitric acid can make iron passive by producing a protective surface film that greatly slows further attack. This is the standard iron passivation example.',[REB,'https://www.sciencedirect.com/science/article/pii/B9780444422521500540'],question='Which listed metal becomes passive in concentrated nitric acid?',options=['Iron','Tin','Copper','Zinc'],audit='Standardized acidname. Independent passivation support in indexed primary1983symposium abstract; publisherfullpage403 so not claimed fully accessible.')
no(651,'PDF56 has identical C₆H₆ optionsAandD; no unique label can be keyed. Also soot formation depends on combustion conditions. Need distinct original option formulas; do not fabricate a replacement saturated hydrocarbon.')
no(652,'PDF56 optionC is incomplete 2-methylbut-ene, overlapping possible optionD2-methylbut-1-ene. Correct A has C₄H₈, but option context remains defective. Found2019 repeat with different order, not evidence for original1999 missing locant.')
yes(653,'C','At about 140–145 °C with excess ethanol and concentrated sulfuric acid, intermolecular dehydration produces diethyl ether: 2C₂H₅OH → C₂H₅OC₂H₅ + H₂O. Higher temperatures favour ethene formation.',[ORG,REB],question='When excess ethanol is heated to 145 °C in the presence of concentrated H₂SO₄, the main organic product is',options=['Ethyne','Diethyl sulfate','Diethyl ether','Acetone'],check='ether-dehydration')
yes(654,'B','But-1-en-3-yne is CH₂=CH–C≡CH, with formula C₄H₄ and molar mass 52 g mol⁻¹. One C=C bond consumes one Br₂ and one C≡C consumes two Br₂ on full addition. Thus 5.2/52 × 3 × 160 = 48.0 g bromine is required.',[ORG],question='How many grams of bromine are required for complete addition to 5.2 g of but-1-en-3-yne? [C = 12, H = 1, Br = 80]',options=['64.0 g','48.0 g','32.0 g','16.0 g'],audit='Corrected oldD→B; original explanation had wrongformula/mass, counted triplebond incorrectly and usedBr insteadBr₂.',check='enyne-bromination')
yes(655,'D','Polyvinyl chloride is a durable thermoplastic widely used for pipes. Its long polymer chains and material properties suit this use.',[REB],question='Polyvinyl chloride is commonly used to produce',options=['Bread','Pencils','Ink','Pipes'])
no(656,'Both alkenes and alkanoic acids lack the normal aldehyde/ketone cyanohydrin and oxime reactions under standard carbonyl-test conditions. Wording does not distinguish AfromD and hydroxylamine can undergo other reactions under different conditions. Hold rather than add a carbonyl-class premise.')
yes(657,'C','Ethyl ethanoate is CH₃–C(=O)–O–C₂H₅. Swapping the terminal methyl and ethyl groups gives C₂H₅–C(=O)–O–CH₃. The alcohol-derived group is methyl and the acid-derived part has three carbons, so the ester is methyl propanoate.',[ORG,'https://myschool.ng/classroom/chemistry/1480?c_page=1&filter=oldest&page=27'],question='When the two terminal alkyl groups of ethyl ethanoate are interchanged, the compound formed is',options=['Methyl ethanoate','Ethyl propanoate','Methyl propanoate','Propyl ethanoate'],audit='Full matching Myschool1480 confirms allfour names, including garbledC. Corrected B→C without changing totalcarboncount.',check='ester-swap')
no(658,'PDF56 structures recovered: ICH₂=CHCHO, IIOHCOCOOH, IIIOHC-C≡CH. BIIIonly follows C–C addition-only model, but bromination conditions unspecified and aldehyde oxidation by bromine water changes stoichiometry (Icanconsume2Br₂). Hold for condition-specific source rather than add an invented solvent/reaction restriction.')
no(659,'Titanium22 Ti²⁺ ground state is [Ar]3d² with20electrons; PDF57 has no such option. C[Ar]only has18; D[Ar]4p² is not ground state. Alternate TestDriller showsD[Ar]4s², also wrong forTi²⁺. Cannot replace an option with an invented correct configuration.',answer='[Ar]3d²')
no(660,'Bonding type alone cannot determine whether a new substance forms: covalent bonding also occurs within elemental substances and metallic bonding can occur in new phases/alloys. No chemically sound unique distinction in the complete supplied question.')
yes(661,'B','A radioactive isotope has a characteristic half-life. Measuring decay and comparing it with known data can help identify or detect a radionuclide; knowing its half-life does not itself create, split or irradiate atoms.',[REB],question='Knowledge of radioactive half-life can help to',options=['Create an element','Detect an element','Split an element','Irradiate an element'],audit='Clarified explanatory isotope scope without claiming half-life alone uniquely identifies all elements.')
yes(662,'C','CO₂ has two electron-domain directions around carbon and is linear. H₂O has two bonds and two lone pairs around oxygen, giving a bent molecular shape. CH₄ has four bonding domains and is tetrahedral.',[REB],question='The molecular shapes of CO₂, H₂O and CH₄, respectively, are',options=['Bent, linear and tetrahedral','Bent, tetrahedral and linear','Linear, bent and tetrahedral','Tetrahedral, linear and bent'])
no(663,'PDF57 prints internuclear0.914nm, so half is0.457nm, absent. A0.097wouldrequire0.194nm; CandDduplicate2.388nm. Matching original corrected numerical options not recovered; do not invent0.194tofitA.',answer='0.457nm from supplied datum only')
no(664,'Argon shields electric arc welding, including welding steel and some brass processes. OptionsA,B,D overlap real uses, and steel is misspelled. No source condition makes exactly one unique answer; hold instead of changing other options.')
yes(665,'D','DDT is a manufactured organochlorine pesticide. Nitric oxide, carbon monoxide and formaldehyde can be produced by natural processes, whereas DDT contamination originates from its human manufacture and use.',[REB],question='Which listed pollutant is a synthetic pesticide rather than a product of natural environmental processes?',options=['NO','CO','HCHO','DDT'],audit='Rephrased unknown-in-nature distinction precisely; removedpageartifact.')
no(666,'AgCl equilibrium concentration is√(2e−10)=1.414e−5mol/dm³, but10dm³washwater loses1.414e−4mol silver at saturation, not any listed concentration-valued quantity. Silvermass≈0.01527g. Need original question/units/options; do not answerDconcentration to a total-loss question.')
yes(667,'D','When gaseous ions become surrounded by water molecules, favourable ion–dipole attractions form and energy is released. Hydration itself is exothermic, although dissolving an entire solid also requires energy to separate its lattice.',[REB],question='Hydration of ions is associated with',options=['Absorption of heat','Reduction of heat','Conduction of heat','Liberation of heat'])
no(668,'PDF58 curve visually recovered but resolution/scale does not justify exact offered amounts: near60°C≈6mol/dm³and20≈4 suggests≈1mol in0.5dm³, unlike2.375. Initial saturation and constantvolume convention also absent. Need clearer original curve and premise; no nearest-choice selection.')
yes(669,'C','HCl donates a proton to water. The species left after that donation, Cl⁻, is the conjugate base of HCl; H₃O⁺ is the conjugate acid of water.',[ACID,REB],question='In HCl(aq) + H₂O(l) → H₃O⁺(aq) + Cl⁻(aq), what is Cl⁻ in relation to HCl?',options=['Conjugate acid','Acid','Conjugate base','Base'],audit='Restored reaction and relational wording so specific conjugate role is asked.')
no(670,'Unqualified light sensitivity depends on wavelength, crystal/emulsion preparation and sensitisation. SourceoldA explanation is unsupported; primaryphotographictrainingmaterial suggests bromide faster, iodide slow alone, but fullPDFfetchfailed and no specified comparisonconditions. Hold for precise original teaching context and accessible primary support.')
yes(671,'B','For fully dissociated HCl, [H⁺] = 0.25 mol dm⁻³. Thus pH = −log₁₀(0.25) = 0.602 and, at 25 °C in the ideal dilute-solution model, pOH = 14.00 − 0.602 = 13.40.',[ACID],question='Using the ideal concentration model at 25 °C, what is the pOH of 0.25 mol dm⁻³ hydrochloric acid?',options=['12.40','13.40','14.40','14.60'],audit='Made standardpKw14andidealmodel explicit.',check='poh')
yes(672,'C','Manganese changes from +7 in MnO₄⁻ to +2, gaining five electrons. The balanced half-equation is MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O, with equal charge and atoms on both sides.',[RX],question='Complete the reduction half-equation: MnO₄⁻(aq) + 8H⁺(aq) + Y → Mn²⁺(aq) + 4H₂O(l). What is Y?',options=['2e⁻','3e⁻','5e⁻','7e⁻'],audit='Restored permanganatecharge and missingYslot by exact half-equation balance.',check='permanganate-balance')
yes(673,'C','The half-equation uses one mole of electrons for half a mole of Zn. Its charge is therefore one Faraday: Q = 1 × 96,500 = 9.650 × 10⁴ C.',[EL],question='For the stoichiometric amounts in ½Zn²⁺(aq) + e⁻ → ½Zn(s), what charge is required to deposit ½ mol Zn? [F = 96,500 C mol⁻¹]',options=['0.965 × 10⁴ C','4.820 × 10⁴ C','9.650 × 10⁴ C','48.200 × 10⁴ C'],audit='Explicitly connected equationcoefficients to amount, preservinghalfZn andoneelectron.',check='half-mole-zinc')
yes(674,'D','Faraday’s first law states that deposited mass is proportional to charge. The electrochemical equivalent Z is mass deposited per unit charge, so M = ZQ. Its units give (g C⁻¹) × C = g.',[EL],question='If M is deposited mass, Q is charge passed and Z is the electrochemical equivalent, how is Faraday’s first law written?',options=['M = Z/Q','M = Q/Z','M = Z/(2Q)','M = QZ'],audit='PDF58 fractionbars visually recovered. Finaloption printedE relabelledD contiguously; removedentiremergedQ28ethanolquestion. OldAwasflattenedZ/Q, notZQ.',check='faraday-proportionality')
yes(675,'C','For the same mass, powder exposes a larger surface area to the acid than granules. More reacting surface is available at once, increasing the reaction rate.',[CAT],question='For equal masses under the same conditions, powdered marble reacts faster with hydrochloric acid than granular marble because the powder has',options=['More molecules','More atoms','A larger exposed surface area','A relatively larger mass'],audit='Restoredmissingfaster andequalmasscomparativecondition.')
yes(676,'B','A zero-order reaction has rate = k, independent of reactant concentration over the range where that rate law applies. Its rate-versus-concentration plot is therefore horizontal.',[CAT],question='Which rate-versus-concentration plot represents a zero-order reaction?',options=['A straight-line rise followed by a straight-line fall','A horizontal line at a positive rate','A straight line rising from the origin','A curved rise that reaches a maximum and then falls'],audit='AllfourPDF58plots visually transcribed. CorrectedoldA→B; originalgraphA triangular, B horizontal,Clinear,Dcurved.',check='zero-order')
yes(677,'D','In the usual concentration or pressure equilibrium expression, gaseous and dissolved species contribute variable terms. Pure solids and pure liquids have effectively constant activities and are absorbed into the equilibrium constant.',[REB],question='In the usual equilibrium-constant expression, which species contribute variable concentration or partial-pressure terms?',options=['Gaseous and solid species','Liquid and solid species','Solid and dissolved species','Gaseous and dissolved species'],audit='Clarified variableterms rather thanclaimpurephases have noactivity.')
yes(678,'C','Sulfur creates cross-links between rubber polymer chains during vulcanisation. These links improve elasticity, strength and resistance to permanent deformation.',[REB],question='Which substance is commonly used for vulcanisation of rubber?',options=['Chlorine','Hydrogen peroxide','Sulfur','Sulfuric acid'])
yes(679,'A','Dissolved carbon dioxide produces the fizz and carbonic-acid contribution to the sharp taste of carbonated water. Carbon monoxide is not used for carbonation.',[REB],question='The characteristic fizz and sharp taste of soda water result from dissolved',options=['Carbon(IV) oxide','Carbon(II) oxide','Soda','Glucose'])
yes(680,'D','Synthesis gas, or syngas, is a mixture principally of carbon monoxide and hydrogen. It is a feedstock for making fuels and chemicals such as methanol.',[REB],question='Synthesis gas is principally a mixture of',options=['CH₄ and H₂O','CH₄ and H₂','CO₂ and H₂','CO and H₂'])
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-017','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry641–680, source1999–2000. PDF55–59 visually inspected; source-complete candidates and explicit held defects.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-017.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
