"""Private Chemistry review, normalized records 281–320. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][280:320]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==1989:return 26 if q['num']<50 else 27
 return 27 if q['num']<=11 else 28 if q['num']<=29 else 29
def yes(i,a,e,urls,*,question=None,options=None,year=None,audit='',check=None):
 q=qs[i-281];u=copy.deepcopy(q)
 if year:u['year']=year
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-281];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})

ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
IMF='https://openstax.org/books/chemistry-2e/pages/10-1-intermolecular-forces'
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
yes(281,'D','Under controlled, gentle heating, ammonium nitrate decomposes to nitrous oxide and water: NH₄NO₃ → N₂O + 2H₂O. The nitrogen atoms total two on each side, and hydrogen and oxygen are also conserved.',['https://openstax.org/books/chemistry-2e/pages/18-7-occurrence-preparation-and-properties-of-nitrogen'],question='What are the products of the usual thermal decomposition of ammonium nitrate under gentle heating?',options=['NO₂ and oxygen','NH₃ and oxygen','Nitrogen and water','N₂O and water'],audit='Corrected nitrate spelling and the old explanation coefficient2 before NH₄NO₃. Stated gentle-heating convention; no procedure or operating temperature provided.',check='ammonium-nitrate')
no(282,'The general corrosion-resistance argument is valid for an intact coating, but source B and C both appear to say copper is less susceptible than iron after spelling recovery. No trustworthy original establishes distinct alternatives. Hold rather than select B over duplicate C; damaged copper coating can accelerate galvanic iron corrosion.',answer='B/C duplicated intended statement')
no(283,'Source has four options labelled A,B,D,E and gives no mortar type. Air-lime mortar hardens mainly by carbonation, not simple evaporation, whereas hydraulic mortars can set underwater. The blanket premise and existing explanation are false. Need original material specification and alternatives before publication.')
no(284,'Oxidation is involved in roasting sulfide ores and other extraction stages, so D is not generally absent from metal extraction. It is absent only from the final reduction of metal ions to metal. Do not silently narrow the question to create the intended answer; hold the overbroad stem.',answer='D only for final metal-ion reduction step')
yes(285,'A','Chlorine adds across the carbon–carbon double bond of ethene. Each carbon receives one chlorine atom, forming CH₂Cl–CH₂Cl, or 1,2-dichloroethane. The carbon chain stays two atoms long.',['https://openstax.org/books/organic-chemistry/pages/8-2-halogenation-of-alkenes-addition-of-x2'],question='When chlorine reacts with ethene at room temperature by addition, which product forms?',options=['1,2-Dichloroethane','1,2-Dichloroethene','1,1-Dichloroethane','1,1-Dichloroethene'],audit='Standardised nomenclature and identified the addition reaction described by the room-temperature ethene/chlorine context.',check='ethene-chlorination')
yes(286,'C','In sulfur vulcanisation, sulfur forms cross-links between rubber polymer chains. These links limit chain slippage and improve elastic recovery and mechanical strength. Joining isoprene monomers is polymerisation, which occurs before this treatment.',['https://openstax.org/books/organic-chemistry/pages/14-6-diene-polymers-natural-and-synthetic-rubbers'],question='In the conventional sulfur vulcanisation of rubber,',options=['Isoprene units are joined to produce rubber','Rubber latex is coagulated','Sulfur is chemically combined with the rubber','Water is removed from the rubber'],audit='Specified conventional sulfur process because other curing agents exist; retained source transformation.')
yes(287,'B','Ethanoic acid reacts with sodium hydroxide to form sodium ethanoate and water: CH₃COOH + NaOH → CH₃COONa + H₂O. An acid reacting with a base in this way is neutralisation.',[RX,'https://myschool.ng/classroom/chemistry/27596?qtid=824921'],question='The reaction between ethanoic acid and sodium hydroxide is an example of',options=['Esterification','Neutralisation','Hydroxylation','Hydrolysis'],audit='Recovered hydroxylation in C from matching Myschool27596; source had hydrosylation.',check='ethanoic-neutralization')
yes(288,'D','The O–H hydrogen of one ethanoic acid molecule can be attracted to an oxygen lone pair on another molecule. This intermolecular attraction is a hydrogen bond. The covalent bonds are within each acid molecule.',[IMF],question='Which type of intermolecular bond joins ethanoic acid molecules in the liquid state?',options=['A covalent bond','An ionic bond','A dative covalent bond','A hydrogen bond'])
yes(289,'D','Fats and oils are esters of glycerol. Alkaline hydrolysis breaks their ester links to give fatty-acid salts, which are soaps, and glycerol. Glycerol has an OH group on each of its three carbons, so its name is propane-1,2,3-triol.',['https://edu.rsc.org/exhibition-chemistry/soap-from-bacon-the-dangers-of-alkaline-solutions/2020068.article'],question='Alkaline hydrolysis of fats and oils produces soap and',options=['Propane-1,1,3-triol','Propane-1,3,3-triol','Propane-1,2,2-triol','Propane-1,2,3-triol'],audit='Standardised punctuation of source names without changing positional distractors.')
yes(290,'C','The longest chain containing the double bond has three carbons and is numbered to give that bond position 1. The methyl group is on carbon 2 and chlorine is on carbon 3. The name is therefore 3-chloro-2-methylprop-1-ene.',[ORG],question='What is the IUPAC name of CH₂=C(CH₃)CH₂Cl?',options=['1-Chloro-2-methylprop-2,3-ene','1-Chloro-2-methylprop-2-ene','3-Chloro-2-methylprop-1-ene','3-Chloro-2-methylprop-1,2-ene'],audit='Visually transcribed full branched structure from PDFpage26 to unambiguous condensed notation, retaining every atom and bond. Corrected methyl spelling in B/D; retained incorrect bond locants as distractors. Old explanation added an extra CH₃CH₂ group not in the diagram.',check='alkene-naming')
yes(291,'D','Methane can escape from coal seams and accumulate in mine air. A methane–air mixture can ignite and explode if an ignition source is present. Methane is therefore a major gas-explosion hazard in coal mines.',['https://www.cdc.gov/niosh/mining/topics/fires-explosions.html'],question='Which listed gas is a major cause of gas explosions in coal mines?',options=['Butane','Ethene','Ethane','Methane'],audit='Removed page marker and unsupported most-fatal-explosions statistic; retained gas identification.')
yes(292,'C','X burns with a sooty flame but does not readily decolourise bromine water, behaviour characteristic of an aromatic hydrocarbon such as benzene. Y decolourises bromine water, indicating a reactive multiple bond, while Z has the cleaner flame expected of a saturated hydrocarbon.',[ORG],question='Three hydrocarbon liquids X, Y and Z are compared. X and Y burn with sooty flames, while Z does not. Y decolourises bromine water, but X and Z do not. Which is most consistent with an aromatic hydrocarbon?',options=['X and Z','Y','X','Z'],audit='Corrected old D to C. Replaced false explanation calling a saturated non-sooty hydrocarbon aromatic. Used most-consistent language because these observations are screening evidence rather than exhaustive structural proof.')
no(293,'Stem omits what order is requested and option A introduces different gases CO₂/NO. Molar masses28,34,46,64 give decreasing diffusion rates CO,H₂S,NO₂,SO₂ (D), while reverse order could describe density. Need actual directional phrase and full alternatives; cannot infer it from the intended Graham-law topic.',answer='D for decreasing diffusion rate, B for decreasing molar mass')
yes(294,'D','S has 19 protons and 20 neutrons, so its mass number is 39. Atomic number 19 is odd and identifies potassium, which commonly loses one electron to form K⁺. The other atoms do not satisfy all three conditions.',[RX,'https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism'],question='The proton, electron and neutron counts are: P = (13, 13, 14); Q = (16, 16, 16); R = (17, 17, 35); S = (19, 19, 20). Which atom has mass number greater than 30 but less than 40, an odd atomic number, and forms a singly positive ion in solution?',options=['P','Q','R','S'],audit='Restored complete table from visually inspected PDFpage27 as explicitly labelled tuples. Preserved unusual R neutron35 rather than infer isotope change. Corrected old C to D and relative atomic mass to the integer mass number appropriate to the given nucleon counts.',check='atomic-table')
yes(295,'B','Valence, or valency, describes an atom’s combining capacity, commonly expressed as the number of bonds it forms in simple compounds. Atomic number counts protons, oxidation number is a formal electron-accounting value, and electronegativity describes attraction for bonding electrons.',['https://openstax.org/books/chemistry-2e/pages/7-summary'],question='Which term describes the combining capacity of an atom in terms of the number of bonds it can form?',options=['Oxidation number','Valence','Atomic number','Electronegativity'])
no(296,'PDFpage27 prints X(g)→X(g) with no charge or electron, so no energy transformation is defined. Ionisation and electron affinity require different missing charges. Old explanation openly assumes X⁺; preserve held until a legible original establishes the species.',answer='A only if product is X⁺ plus electron')
yes(297,'C','Pb(NO₃)₂ + H₂S → PbS + 2HNO₃ gives one mole of PbS per mole of H₂S. The PbS molar mass is 207 + 32 = 239 g mol⁻¹, so the H₂S amount is 5.02/239 mol. Its STP volume is about 0.470 dm³, giving (0.470/10.0)×100 = 4.70% by volume.',[RX,'https://myschool.ng/storage/materials/12563824733235_futminna.pdf'],question='A 10.0 dm³ air sample at STP contains H₂S. Passing it through excess Pb(NO₃)₂ solution gives 5.02 g of PbS. Using Pb(NO₃)₂ + H₂S → PbS + 2HNO₃, calculate the percentage by volume of H₂S. [Pb = 207, S = 32; molar gas volume at STP = 22.4 dm³ mol⁻¹]',options=['50.2%','47.0%','4.70%','0.47%'],audit='Matching Myschool FUTMINNA PDF solution item71 has the same10.0dm³/5.02g problem and corroborates H₂S reactant and S32, replacing PDF H₂O/S23. Made supplied STP molar-volume condition explicit; source year remains compilation1990.',check='h2s-percentage')
yes(298,'C','Mercury used as a cathode can enter process wastes. Some is oxidised to mercury chloride compounds, including mercury(II) chloride. This makes mercury compounds a characteristic contamination risk of the mercury-cell chlor-alkali process.',['https://19january2017snapshot.epa.gov/sites/production/files/2015-10/documents/mercury-rpt-to-congress-export-ban.pdf'],question='Which listed contaminant is particularly associated with effluent from a brine-electrolysis plant using a flowing mercury cathode?',options=['Oxygen','Hydrogen','Mercury(II) chloride','Hydrogen chloride'],audit='Corrected old D to C using EPA process-waste evidence. Clarified characteristic contaminant rather than imply that a waste stream can contain only one species.')
no(299,'Molarity needs final solution volume, not100g solvent. Source also prints180°C without pressure, where water is not an ordinary liquid at1atm. C1.25 assumes100gwater≈0.1dm³solution and a different temperature. Neither assumption is given; hold until source provides volume/density and valid state conditions.',answer='C only under unsupported0.1dm³solution assumption')
yes(300,'B','Smoke is an aerosol: small solid particles and often liquid droplets are suspended in a gas. Soot particles and condensed droplets are dispersed through air, which acts as the continuous phase.',['https://openstax.org/books/chemistry-2e/pages/11-5-colloids'],question='Smoke consists of',options=['Solid particles dispersed in liquid','Solid or liquid particles dispersed in gas','Gas or liquid particles dispersed in liquid','Liquid particles dispersed in liquid'])
no(301,'Source has NaC₂O₄/CaCl and calls the0.1M reagent calcium oxalate. Nuffield1970 topic text has an exact1.9g sodium-oxalate/50gwater problem using calcium chloride, supporting intended reagent, but the exam version remains defective. Correct stoichiometry gives0.14179dm³=141.79cm³, near B140 rather than old C0.014dm³. Need sound exam transcription and stated rounding before approval.',answer='B only after reagent/formula/rounding reconciliation')
yes(302,'C','The 25.00 cm³ aliquot contains 0.02000×0.1 = 0.00200 mol of acid because the acid is monobasic. The full 250 cm³ contains ten times as much, or 0.0200 mol. Its molar mass is 2.0/0.0200 = 100 g mol⁻¹.',[RX],question='A 2.0 g sample of a monobasic acid is made up to 250 cm³ with water. A 25.00 cm³ portion requires 20.00 cm³ of 0.1 mol dm⁻³ NaOH for complete neutralisation. What is the acid’s molar mass?',options=['200 g mol⁻¹','160 g mol⁻¹','100 g mol⁻¹','50 g mol⁻¹'],audit='Corrected old D to C from aliquot scaling; replaced contradictory old arithmetic and corrected molar-mass units.',check='monobasic-molar-mass')
yes(303,'A','For the usual dilute-solution calculation, [H⁺] = 10⁻ᵖᴴ. With pH 4.398, [H⁺] = 10⁻⁴·³⁹⁸ ≈ 4.0×10⁻⁵ mol dm⁻³. A change of one pH unit corresponds to a tenfold concentration change.',['https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'],question='What is the hydrogen-ion concentration of a dilute solution with pH 4.398?',options=['4.0×10⁻⁵ mol dm⁻³','0.4×10⁻⁵ mol dm⁻³','4.0×10⁻³ mol dm⁻³','0.4×10⁻³ mol dm⁻³'],audit='Restored exponent notation and clarified dilute-solution concentration convention.',check='ph-concentration')
no(304,'Dilution givesV₁=(0.05×1)/11.0=0.004545dm³. None of0.05,0.10,0.55,11.0dm³ matches. Old explanation admitted the discrepancy then selectedC anyway. Need original stock concentration or corrected options; no nearest-choice key.',answer='0.004545dm³; none listed')
no(305,'A0.56dm³ follows0.1mol electrons/4 only if oxygen evolves at an inert anode. An ordinary copper coulometer uses a dissolving copper anode and does not evolve oxygen there. Source gives no inert-anode or oxygen cell condition. Do not invent apparatus to support A; old explanation also places oxygen at cathode.',answer='A conditional on oxygen-evolving inert anode')
yes(306,'A','Deposited nickel is proportional to charge. Increasing from 0.1 to 0.4 faraday deposits four times the mass: 4×2.95 = 11.8 g. The amount is 11.8/58.7 ≈ 0.20 mol.',[EL],question='A charge of 0.1 faraday deposits 2.95 g of nickel from an aqueous solution. How many moles will 0.4 faraday deposit under the same conditions? [Ni = 58.7]',options=['0.20 mol','0.30 mol','0.034 mol','5.87 mol'],audit='Corrected old B to A using direct proportionality, without changing ionic valence to rescue the old key.',check='nickel-charge')
yes(307,'B','For Cr₂O₇²⁻, let chromium’s oxidation number be x: 2x + 7(−2) = −2, so x = +6. The product is Cr³⁺, whose oxidation number is +3. Chromium is therefore reduced from +6 to +3.',[RX],question='In Cr₂O₇²⁻ + 6Fe²⁺ + 14H⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O, how does chromium’s oxidation number change?',options=['+7 to +3','+6 to +3','+5 to +3','−2 to +3'],audit='Restored formula charges and arrow and checked atom/charge conservation.',check='dichromate-redox')
no(308,'The source sentence omits which formation enthalpy belongs to each oxide. Assigning−1670 toAl₂O₃ and−822 toFe₂O₃ gives−848kJ, but this assignment is missing. SuperPrep reconstruction and generic thermochemical tables are not independent original wording. Hold until matching original recovers labels; do not infer ordering from expected values.',answer='C conditional on recovered enthalpy labels')
yes(309,'A','Zinc is oxidised more readily than iron and acts as the sacrificial anode. Its oxidation potential is more positive than iron’s, while its reduction potential is more negative. Electrons supplied by zinc oxidation keep the iron cathodic and help protect it from corrosion.',['https://openstax.org/books/chemistry-2e/pages/17-6-corrosion'],question='Iron galvanised with zinc receives cathodic protection because',options=['Zinc has a more positive oxidation potential than iron','Zinc has a less positive oxidation potential than iron','Both have the same oxidation potential','Zinc is harder than iron'],audit='Corrected old B to A; old explanation confused oxidation-potential and reduction-potential signs.',check='zinc-potential-sign')
yes(310,'D','Powder exposes more calcium carbonate surface to the acid than lumps do. A higher temperature also increases the rate by increasing the frequency of effective collisions. Powder at 50 °C combines both rate-increasing factors.',['https://openstax.org/books/chemistry-2e/pages/12-2-factors-affecting-reaction-rates'],question='With the same dilute nitric acid conditions, which calcium carbonate sample reacts fastest?',options=['5 g of lumps at 25 °C','5 g of powder at 25 °C','5 g of lumps at 50 °C','5 g of powder at 50 °C'],audit='Corrected powered to powdered and nitrate spelling. Made the ordinary controlled comparison explicit, preserving all four source mass/temperature conditions.')
no(311,'Endothermic HI decomposition favours products at higher temperature, supportingB. However C is printed adding the temperature, duplicatingB if read literally or hiding an unknown added species. Need complete optionC; do not infer catalyst or hydrogen from standard examples.',answer='B, with unresolved C')
yes(312,'D','Chlorine is denser than air and can enter below it, pushing air upward out of an upright gas jar. This is upward displacement of air. Hydrogen and ammonia are lighter than air; nitrogen monoxide reacts with oxygen in air and is unsuitable for this collection method.',['https://edu.rsc.org/exhibition-chemistry/floating-gas-bubbles/2020055.article','https://openstax.org/books/chemistry-2e/pages/18-11-occurrence-preparation-and-properties-of-halogens'],question='Which gas can be collected by upward displacement of air, with the air moving upward out of an upright jar?',options=['NO','H₂','NH₃','Cl₂'],audit='Corrected old C to D; made the direction refer explicitly to displaced air, not the entering gas. Independent density and NO oxidation checks used.',check='gas-collection-density')
no(313,'The stem omits what happens to nitric acid (heated/decomposed/exposed), and B/D both list water plusNO₂. Thermal decomposition can giveNO₂,O₂,H₂O, but cannot be substituted for the missing condition. Hold complete item until premise and distinct options are restored.',answer='C conditional on thermal decomposition')
yes(314,'C','Nitrogen monoxide, NO, reacts with oxygen in air to form brown NO₂: 2NO + O₂ → 2NO₂. This visible change distinguishes NO from the other three colourless gases in the list. Limewater alone cannot distinguish CO₂ from SO₂ because both can form white precipitates.',['https://edu.rsc.org/experiments/some-reactions-of-nitrogen-dioxide/533.article'],question='Which test can uniquely identify one gas from the list SO₂, H₂, CO₂ and NO?',options=['Pass each gas into water and test with blue litmus','Pass each gas into limewater','Expose each gas to air','Pass each gas into concentrated sulfuric acid'],audit='Clarified any one as uniquely identifying one member, not claiming a full separation of all four gases; corrected spelling.',check='nitrogen-monoxide')
yes(315,'C','The conventional Haber process uses an iron catalyst to speed the reaction between nitrogen and hydrogen. A finely divided catalyst provides a large surface on which the reactant gases can adsorb and react.',['https://edu.rsc.org/download?ac=12434'],question='The conventional Haber process for making ammonia commonly uses finely divided',options=['Vanadium','Platinum','Iron','Copper'],audit='Retained conventional industrial catalyst meaning without claiming all ammonia-synthesis technologies use iron.')
no(316,'Iron reacts with steam and dilute nonoxidising acids, but the source uses or, which can also admit lead reacting with suitable dilute acid before passivation. The old explanation incorrectly says lead cannot liberate hydrogen. Need original both/and or explicit acid conditions for a unique complete item.',answer='B for both steam and suitable dilute acid')
yes(317,'C','Incomplete combustion of coal can produce carbon monoxide. CO binds strongly to haemoglobin and reduces the blood’s ability to carry and release oxygen; it also interferes with cellular respiration. Dangerous CO can accumulate in a poorly ventilated room.',['https://www.cdc.gov/mmwr/preview/mmwrhtml/00040728.htm','https://www.cdc.gov/carbon-monoxide/about/index.html'],question='Why is a coal fire dangerous in a poorly ventilated room?',options=['Accumulated CO₂ simply causes deep sleep','The room is usually too hot','Carbon monoxide can accumulate and cause poisoning','It removes most gases from the room'],audit='Corrected old oxygen-displacement mechanism to haemoglobin/tissue toxicity; replaced vague suffocation wording with CO poisoning. No unsupported safe-indoor-use guidance.')
yes(318,'D','In the usual blast-furnace explanation, limestone supplies CaO, which reacts with silica impurity: CaO + SiO₂ → CaSiO₃. The calcium silicate joins the slag and is separated from the molten iron.',['https://openstax.org/books/chemistry-2e/pages/19-1-occurrence-preparation-and-properties-of-transition-metals-and-their-compounds','https://teamboma.com/member/post-explanation/3804'],question='Which compound is a major component of slag in the conventional blast-furnace production of iron?',options=['An alloy of calcium and iron','Coke','Impure iron','Calcium silicate'],audit='Matching TeamBoma question page states JAMB1990 and confirms four optionsA-D plus silicate(IV). Recovered sourceE asD, corrected format5→4, ion→iron and silicate oxidation numberV→IV through familiar equivalent name.',check='iron-slag')
yes(319,'A','Solid sodium hydroxide absorbs moisture from air. It is strongly hygroscopic and can become wet as enough water is absorbed, changing the condition and concentration of the stored reagent. A tightly closed container limits this uptake.',['https://wwwn.cdc.gov/TSP/PHS/PHS.aspx?phsid=246&toxid=45'],question='Why should sodium hydroxide be stored in a properly closed container?',options=['It readily absorbs water vapour from air','It is easily oxidised by atmospheric oxygen','It turns golden yellow in light','It melts at a low temperature'])
yes(320,'D','Copper compounds can introduce colour into glass. Copper ions interact with light, producing characteristic colours that depend on composition and oxidation state. Potassium, barium and zinc do not provide the same characteristic transition-metal colouring in this comparison.',['https://edu.rsc.org/experiments/making-glass/687.article','https://lagosbooksclub.wordpress.com/wp-content/uploads/2013/11/chemistry.pdf'],question='Small amounts of metal oxides can colour glass made from a mixture containing Na₂CO₃ and SiO₂. Which listed metal can provide such a colouring oxide?',options=['Potassium','Barium','Zinc','Copper'],audit='Matching older ChemistryPDF transcription corroborates SiO₂ rather than sourceSO₂; retained glass-colouring task and all metal alternatives.')
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-008','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry records281–320: twelve1989 records and twenty-eight1990 records. PDFpages26–29 visually inspected; table and structural formula restored where all source content is legible.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-008.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
