"""Private Chemistry review, normalized records 361–400. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][360:400]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==1991:return 33 if q['num']<50 else 34
 if q['year']==1993:return 37
 return 34 if q['num']<=16 else 35 if q['num']<=31 else 36
def yes(i,a,e,urls,*,question=None,options=None,year=None,num=None,audit='',check=None):
 q=qs[i-361];u=copy.deepcopy(q)
 if year:u['year']=year
 if num:u['num']=num
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-361];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})

ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
ATOM='https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism'
EQ='https://openstax.org/books/chemistry-2e/pages/13-2-equilibrium-constants'
MATCH='https://lagosbooksclub.wordpress.com/wp-content/uploads/2013/11/chemistry.pdf'
yes(361,'A','Ethene first adds sulfuric acid to form ethyl hydrogen sulfate. Adding water and warming hydrolyses this intermediate to ethanol and regenerates sulfuric acid. The overall change adds H and OH across the ethene double bond.',['https://patentimages.storage.googleapis.com/cd/de/04/c8ae0bb3612688/US4296261.pdf',RX],question='Ethene is absorbed in concentrated H₂SO₄. The product is diluted with water and warmed. Which organic product is formed?',options=['Ethanol','Diethyl ether','Ethanal','Diethyl sulfate'],check='ethene-hydration')
yes(362,'C','Soap forms insoluble calcium and magnesium salts, seen as scum in hard water. Common soapless detergents avoid this precipitation because their corresponding salts remain sufficiently soluble. They therefore retain cleaning action better in hard water.',['https://edu.rsc.org/outreach/hard-water-challenge-chemistry-for-all-project-14-16-years/4015892.article'],question='What is an advantage of common soapless detergents over soap in hard water?',options=['They are always easier to manufacture','They always foam more than soap','Their salts with hard-water ions remain soluble','They always kill more germs than soap'],audit='Clarified common soapless-detergent comparison and hard-water ion salts; no universal claim about all surfactant formulations.')
no(363,'Sourcepage33 leaves X undefined and has an extra malformed CHCH₃ product fragment beneath the main alkene. AlcoholicKOH suggests elimination, but identifying the leaving group as a halogen from the expected key would be circular. Hold until substrate, meaning ofX and all product structures are independently recovered.')
yes(364,'B','The longest carbon chain has three atoms. Numbering from CH₂Cl places chlorine at carbon 1 and the methyl branch at carbon 2. The compound is 1-chloro-2-methylpropane.',[ORG,'https://myschool.ng/classroom/chemistry/13111?exam_type=jamb&exam_year=1991&page=9'],question='What is the IUPAC name of CH₃CH(CH₃)CH₂Cl?',options=['1-Chloro-2-methylbutane','1-Chloro-2-methylpropane','2-Chloromethylethane','1-Chloro-2,2-dimethylethane'],audit='Visually inspected PDFpage33 skeleton. Matching Myschool13111 explanation independently identifies propane chain with chloro1/methyl2 and no sulfur atom, resolving stray lowercases beforeCH₂Cl. Kept sourceC distractor rather than different websiteC.',check='chloroalkane-naming')
no(365,'Glycerides can be mono-, di- or triglycerides. ThreeNaOH per molecule applies specifically to a triglyceride; a monoglyceride can yield one soap molecule. Matching Myschool13112 still lacks a defining triglyceride stem; user explanation is not original-premise recovery. Need actual ester count.',answer='A for triglyceride only')
yes(366,'A','In the first chlorination step, one hydrogen on the methyl group of ethanoic acid is replaced by chlorine. The products are chloroethanoic acid, ClCH₂COOH, and HCl. The carboxyl group remains intact.',['https://patents.google.com/patent/CN1282637C/en'],question='Which listed pair is produced by the chlorination of CH₃COOH with Cl₂ in sunlight?',options=['ClCH₂COOH + HCl','CH₃COCl + HOCl','CH₃COOCl + HCl','CH₃COCl + H₂O'],audit='Removed next-year heading. Primary photochlorination patent corroborates transformation; explanation describes first substitution, not exclusive products under unlimitedchlorine.',check='ethanoic-chlorination')
no(367,'Flood water is a conventional heterogeneous example, but writing inks can be pigment dispersions and soft drinks can contain gas bubbles. Source does not specify dye-based ink or a single liquid phase. These distinctions can create multiple non-homogeneous options. Retain intendedC pending unambiguous original alternatives.',answer='C under clear-solution assumptions forB/D')
no(368,'Actual1993Q1 page37. Both crystallisationA and evaporationB can recover unchanged sodium chloride; choices provide overlapping evidence of physical dissolution. Do not arbitrarily prefer evaporation or alterA to force a unique key.',year=1993,answer='A and B both support recovery')
yes(369,'C','Liquid metal still has strong attraction between its atoms and delocalised electrons. Melting permits atoms to move past one another, while boiling separates them into the gas phase and overcomes much more of this cohesion. This helps explain why vaporisation needs much more energy.',['https://openstax.org/books/chemistry-2e/pages/10-5-the-solid-state-of-matter'],question='Why can a metal have a large temperature interval between melting and boiling?',options=['All metals have very high melting points','Metals conduct heat rapidly','Metallic cohesion remains in the liquid, while boiling separates the atoms','Metal crystal lattices are easily broken'],audit='Replaced misleading individual metallic-bond language with cohesive-interaction explanation; avoided universal high-melting-metal claim.')
yes(370,'B','Bronze is an alloy containing copper and tin, often with smaller amounts of other elements. Its components are mixed rather than combined in one fixed molecular ratio, so it is a mixture. Pure sulfur, distilled water and ethanol are single substances.',['https://openstax.org/books/chemistry-2e/pages/1-2-phases-and-classification-of-matter'],question='Which listed substance is a mixture?',options=['Sulfur powder','Bronze','Distilled water','Ethanol'],year=1993,audit='Recovered actual1993Q2 from page37; stable importedID retained.')
no(371,'Source supplies0.5 without concentration units. It asks actualH⁺ moles: even if0.5M is inferred, sulfuric acid second dissociation is incomplete, so twice the acid amount is a neutralisation-equivalent calculation rather than actual freeH⁺ concentration. Need units and intended complete-dissociation or titratable-proton convention.',answer='1mol acid equivalents if0.5M and two titratable protons intended')
yes(372,'C','The balanced equation is 2KClO₃ → 2KCl + 3O₂. Two moles of chlorate produce three moles of oxygen, so 2.5 mol produces 2.5×3/2 = 3.75 mol of O₂.',[RX],question='How many moles of O₂ are formed by complete decomposition of 2.5 mol of KClO₃?',options=['2.50 mol','3.50 mol','3.75 mol','7.50 mol'],year=1993,audit='Recovered actual1993Q3 page37; corrected spelling.',check='chlorate-oxygen')
yes(373,'C','One Al₂(SO₄)₃ unit requires two aluminium atoms and three sulfate groups, giving coefficients 2 for Al(OH)₃ and 3 for H₂SO₄. Their 12 hydrogen atoms form 6H₂O. The balanced coefficients are 3, 2, 6 and 1.',[RX],question='Balance wH₂SO₄ + xAl(OH)₃ → yH₂O + zAl₂(SO₄)₃ using the smallest whole-number coefficients. What are w, x, y and z?',options=['2, 2, 5, 1','3, 2, 5, 2','3, 2, 6, 1','2, 2, 6, 2'],audit='Restored missing lowercase l in aluminium reactant symbolA(OH)₃ from explicit aluminium product identity; element-symbol completion rather than different reagent. Checked every element.',check='aluminium-neutralization')
yes(374,'A','At constant pressure, volume is proportional to absolute temperature. Convert 25 °C and 100 °C to about 298 K and 373 K. Then V₂ = 1.50×373/298 ≈ 1.88 dm³. Celsius temperatures cannot be used directly in the ratio.',['https://openstax.org/books/chemistry-2e/pages/9-2-relating-pressure-volume-amount-and-temperature-the-ideal-gas-law'],question='A gas occupies 1.50 dm³ at 25 °C and 1 atm. What volume does the same amount occupy at 100 °C and 1 atm?',options=['1.88 dm³','6.00 dm³','18.80 dm³','60.00 dm³'],year=1993,audit='Recovered actual1993Q5 page37; kept numerical data.',check='charles-volume')
yes(375,'B','For equal volumes under the same conditions, diffusion time is proportional to the square root of molar mass. Thus t(H₂) = 50×√(2/32) = 12.5 s. Hydrogen has one-sixteenth the molar mass of oxygen and diffuses four times as fast.',[GAS],question='100 cm³ of O₂ passes through a porous plug in 50 s. Under the same conditions, how long does the same volume of H₂ take through that plug? [O = 16, H = 1]',options=['10.0 s','12.5 s','17.7 s','32.0 s'],audit='Corrected oldC toB and inverted mass-ratio reasoning; same-conditions comparison explicit.',check='graham-time')
yes(376,'D','Temperature indicates average molecular kinetic energy. In the ideal-gas model, average translational kinetic energy is proportional to absolute temperature. Volume, mass and pressure are not direct measures of this average energy.',['https://openstax.org/books/chemistry-2e/pages/9-5-the-kinetic-molecular-theory'],question='Which quantity measures the average kinetic energy of a substance’s molecules?',options=['Volume','Mass','Pressure','Temperature'],audit='Removed entire next question merged into optionD; sourcepage34 boundary is clear.')
no(377,'Actual1993Q8 page37. Options compare energy directly with force, which are different dimensions. Sublimation overcomes solid intermolecular cohesion without passing through a liquid phase; sourceD incorrectly requires overcoming forces in both phases. None states the process accurately. Hold rather than rewriteD into a new valid answer.',year=1993)
yes(378,'C','Tritium is hydrogen-3. Hydrogen has atomic number 1, so its nucleus contains one proton. Mass number 3 means there are two additional nucleons, both neutrons. The electron of a neutral tritium atom is outside its nucleus.',[ATOM,'https://myschool.ng/classroom/chemistry/13138?qtid=818797'],question='What does the nucleus of tritium, ³H, contain?',options=['Two neutrons and no protons','One neutron and one proton','Two neutrons and one proton','Two neutrons, one proton and one electron'],audit='Matching1992Myschool13138 independently restores optionC proton where PDF says electron. Corrected oldD toC.',check='tritium')
yes(379,'B','Conservation of mass number gives 14 + A = 17 + 1, so A = 4. Conservation of atomic number gives 7 + Z = 8 + 1, so Z = 2. X is therefore ⁴₂He, an alpha particle or helium nucleus.',['https://openstax.org/books/chemistry-2e/pages/21-2-nuclear-equations'],question='In the nuclear equation ¹⁴₇N + X → ¹⁷₈O + ¹₁H, what is X?',options=['A neutron','A helium nucleus','A lithium nucleus','A deuterium nucleus'],audit='Restored nitrogen atomic number7 from element identity and nuclear notation. Changed atom to nucleus consistently for nuclear projectiles; no element identity changed.',check='nuclear-balance')
yes(380,'A','Gas solubility depends on how the gas and solvent interact, so both chemical identities matter. Temperature changes dissolution equilibrium, and the gas’s partial pressure also affects how much dissolves. All four listed factors can therefore affect solubility.',['https://openstax.org/books/chemistry-2e/pages/11-3-solubility'],question='Which factors can affect the solubility of a gas in a liquid? I. Nature of the solvent; II. Nature of the solute; III. Temperature; IV. Gas pressure.',options=['I, II, III and IV','I and II only','II only','I, III and IV only'],num=16,audit='Recovered full1992Q16 from PDFpage34; normalization mistook RomanII continuation for question11 and omitted gas premise. Actualnumber16 restored, stableID retained. Corrected oldB toA.')
yes(381,'D','Seven outer-shell electrons are characteristic of the halogens, which are predominantly nonmetals. They tend to gain one electron or share electrons to complete the shell. Having one, two or three outer-shell electrons is more commonly associated with metallic main-group elements.',[ATOM],question='P, Q, R and S have 1, 2, 3 and 7 outer-shell electrons, respectively. Which is least likely to be a metal?',options=['P','Q','R','S'],audit='Kept probabilistic unlikely wording; does not falsely classify hydrogen, helium or boron as metals.')
no(382,'No industry, process or emission source is specified. All four alternatives include substances that can occur in industrial air pollution, including ammonia,HCl,CO,dust and chlorine. SourceA is plausible but not uniquely selected by the general industrial-environment premise. Do not invent an industry to exclude other choices.')
yes(383,'D','Sulfur dioxide can dissolve in atmospheric water and undergo further oxidation to sulfuric acid. This contributes to acid rain. Oxygen, nitrogen and carbon monoxide are not the listed acid-rain precursor in this comparison.',['https://www.epa.gov/acidrain/what-acid-rain'],question='Which listed gas contributes to acid rain through reactions involving atmospheric water?',options=['Oxygen','Carbon monoxide','Nitrogen','Sulfur dioxide'],audit='Corrected water-vapour dissolution wording; explanation includes oxidation to sulfuric acid rather than calling sulfurous acid the principal component.')
yes(384,'B','Chlorination disinfects water by inactivating bacteria and other susceptible microorganisms. It does not remove the dissolved calcium and magnesium ions responsible for hardness. Effective treatment also depends on dose, contact time and water conditions.',['https://stacks.cdc.gov/view/cdc/37072/cdc_37072_DS1.pdf?download-document-submit=Download'],question='Chlorination of a town water supply primarily controls which of the following?',options=['Bad odour','Bacteria','Temporary hardness','Permanent hardness'],audit='Replaced absolute free-from wording with treatment purpose; no guarantee of sterility or all-contaminant removal.')
no(385,'Commercial emulsion paint contains pigment particles and polymer dispersion; emulsion separately denotes liquid droplets in another liquid. The question does not specify paint pigment dispersion, binder, or emulsion definition. SourceA also overlapsB. Hold rather than chooseC while teaching all emulsions are solid-in-liquid.')
no(386,'OptionC has lost the distinct CH₃COOH formula and comma boundary. The stem supplies neither physical states nor concentrations; aqueous acid conductivity cannot be compared from identity alone without common conditions. Need complete original options and measurement context; do not inferC from strong/weak-electrolyte ordering.')
yes(387,'C','NaHS is sodium hydrogen sulfide. It results from replacing only one of the two acidic hydrogens of H₂S with sodium, leaving a hydrogen in HS⁻. This makes it an acid salt by composition; that classification does not mean its aqueous solution must have pH below 7.',['https://openstax.org/books/chemistry-2e/pages/14-4-hydrolysis-of-salts'],question='Which listed substance is an acid salt?',options=['K₂SO₄·Al₂(SO₄)₃·24H₂O','CuCO₃·Cu(OH)₂','NaHS','CaOCl₂'],audit='Restored double-salt dots; distinguished acid-salt composition from acidic solutionpH.')
yes(388,'B','The required amount is concentration×volume = 6.00×0.175 = 1.05 mol. H₂SO₄ has molar mass 2(1.00) + 32.06 + 4(16.00) = 98.06 g mol⁻¹. The mass is 1.05×98.06 = 102.963 g, approximately 103.0 g.',[RX],question='What mass of H₂SO₄ is needed in 0.175 dm³ of 6.00 mol dm⁻³ H₂SO₄ solution? [S = 32.06, O = 16.00, H = 1.00]',options=['206.0 g','103.0 g','98.1 g','51.5 g'],audit='Moved constants out of answer option; used supplied sulfur mass without early rounding. Mass calculation only.',check='acid-mass')
yes(389,'B','At the cathode, Cu²⁺ gains electrons and deposits as copper. At the carbon anode, water is oxidised and oxygen is evolved. Thus the anode product is oxygen and the cathode product is copper.',[EL,'https://www.schoolngr.com/classroom/jamb/chemistry?examyear=1992&page=5'],question='Aqueous copper(II) sulfate is electrolysed using carbon electrodes. What are the main products at the anode and cathode, respectively?',options=['Copper and oxygen','Oxygen and copper','Hydrogen and copper','Copper and hydrogen'],audit='Matching SchoolNGR1992 transcription confirms tetraoxosulfateVI rather than sourceIV. Used conventional sulfate name.',check='copper-electrolysis')
yes(390,'B','The charge is 500×24×3600 = 43,200,000 C. Each Mg²⁺ ion needs two electrons, so the magnesium amount is Q/(2F) = 43,200,000/(2×96,500) ≈ 223.8 mol. Its mass is 223.8×24/1000 ≈ 5.4 kg.',[EL],question='What theoretical mass of magnesium is produced by electrolysis of magnesium chloride for 24 h at 500 A, assuming all the current deposits magnesium? [F = 96,500 C mol⁻¹; Mg = 24]',options=['2.7 kg','5.4 kg','10.8 kg','21.7 kg'],audit='Corrected oldC toB and Faraday unit Cmmol⁻¹ to Cmol⁻¹. Explicit theoretical current efficiency; no claim thatMg deposits from aqueoussolution.',check='magnesium-electrolysis')
yes(391,'C','Manganese changes from +4 in MnO₂ to +2 in Mn²⁺, a change of −2. Chlorine changes from −1 in Cl⁻ to 0 in Cl₂, a change of +1 per atom. Hydrogen stays at +1, so its change is 0. Reduction means manganese gains electrons.',[RX,'https://www.schoolngr.com/classroom/jamb/chemistry?examyear=1992&page=5'],question='In MnO₂ + 2Cl⁻ + 4H⁺ → Mn²⁺ + Cl₂ + 2H₂O, what are the changes in oxidation number per atom of Mn, Cl and H, respectively?',options=['+2, +2, +4','−1, −2, +4','−2, +1, 0','+2, +4, 0'],audit='Matching SchoolNGR stem corroboratesH⁺. Corrected oldD toC and per-atom versus total-electron confusion.',check='manganese-redox')
yes(392,'B','I₂ gains two electrons to form 2I⁻, so iodine is reduced. The species that is reduced is the oxidising agent. Thiosulfate donates electrons and is oxidised to tetrathionate.',[RX],question='In 2S₂O₃²⁻ + I₂ → S₄O₆²⁻ + 2I⁻, which species is the oxidising agent?',options=['S₂O₃²⁻','I₂','S₄O₆²⁻','I⁻'],audit='Restored coefficient2 before thiosulfate and iodide charge by element/charge conservation. No reagent identity changed.',check='iodine-redox')
no(393,'SourceD violates element conservation by convertingHCl intoN₂ andCl₂ and labels reactant solid; even inferredH₂ would give a solid-to-gas entropy increase competing withA. Need faithful balanced alternatives before selecting water vaporisation. Do not invent gas states to remove competing entropy signs.')
yes(394,'B','Reversing a reaction swaps the numerator and denominator of its equilibrium expression. At the same temperature, K_reverse = 1/K_forward. Multiplying the two constants therefore gives 1.',[EQ],question='At the same temperature, how are the equilibrium constants for a reaction and its exact reverse related?',options=['Their sum is 1','Their product is 1','They are identical','Their product is always greater than 1'],audit='Specified same temperature and exact reversed stoichiometry.',check='reciprocal-equilibrium')
yes(395,'A','H₂(g) + I₂(g) ⇌ 2HI(g) has two moles of gas on each side. Compressing the system changes all concentrations by the same factor, which cancels in the reaction quotient. The other listed equilibria have unequal gas-mole totals and shift when volume changes at constant temperature.',[EQ,MATCH],question='Which equilibrium has no net shift when its volume is decreased at constant temperature?',options=['H₂(g) + I₂(g) ⇌ 2HI(g)','2NO₂(g) ⇌ N₂O₄(g)','PCl₅(g) ⇌ PCl₃(g) + Cl₂(g)','ZnO(s) + CO₂(g) ⇌ ZnCO₃(s)'],audit='Matching older ChemistryPDF transcription suppliesPCl₅(g) state. Restored arrows/parentheses; removed repeated phrase.',check='compression-equilibrium')
yes(396,'C','For xP + yQ ⇌ mR + nS, the concentration expression places product concentrations in the numerator and reactant concentrations in the denominator. Each concentration is raised to its coefficient: Kc = [R]ᵐ[S]ⁿ/([P]ˣ[Q]ʸ).',[EQ],question='For xP + yQ ⇌ mR + nS, with all species included in the concentration expression, which formula gives Kc?',options=['k[P]ˣ[Q]ʸ','([P]ˣ[Q]ʸ)/([R]ᵐ[S]ⁿ)','([R]ᵐ[S]ⁿ)/([P]ˣ[Q]ʸ)','(m[R]n[S])/(x[P]y[Q])'],audit='Visually restored fraction bars/powers from PDFpage35. SourceA lowercasek retained as distractor; clarified concentration-expression convention.',check='equilibrium-expression')
no(397,'SourceA says supports combustion whileD gives a real magnesium-combustion example; the latter makes the former true under a literal existence reading. SelectingD requires treatingA as supports ordinary fuels, a condition absent from source. Hold for wording-distinct original; magnesium exception is valid.')
no(398,'Sourcepage35 apparatus labels collected gas Nitrogen(I)Oxide, not nitrogen. Sodium nitrite plus ammonium chloride normally generatesN₂, whereas ammonium nitrate chemistry can generateN₂O. Missing normalized diagram and source label/key conflict cannot be repaired by assuming gas name. Need matching apparatus and conditions; old qualitative-analysis explanation invented.')
yes(399,'C','Oxygen with ethyne forms the oxyacetylene flame used in gas welding. Oxygen with hydrogen forms an oxyhydrogen flame that can join suitable lower-melting metals. Hydrogen and ethyne alone are both fuels and do not supply the oxidising gas needed for these conventional torch combinations.',['https://www.twi-global.com/technical-knowledge/job-knowledge/oxy-fuel-welding-003'],question='Which listed combinations are conventional fuel–oxygen pairs used for metal welding? I. Oxygen and ethyne; II. Hydrogen and ethyne; III. Hydrogen and oxygen; IV. Ethyne, hydrogen and oxygen.',options=['I and II','III and IV','I and III','II and IV'],audit='Clarified conventional fuel–oxygen pair classification; no claim that every ternary mixture cannot burn. Preserved combinations.')
no(400,'NO reacts rapidly with oxygen in air, butN₂O₅ is also unstable and hydrolyses in moist air. General unstable-in-air wording does not specify oxidation versus thermal or moisture reaction. Old explanation claimingNO relatively stable is false. Hold for distinguishing observation or conditions.',answer='B for rapid atmospheric oxidation; D also unstable')
assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-010','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry records361–400: six1991, twenty-nine1992 and five1993 records. PDFpages33–37 visually inspected. Restored gas-solubility question as1992Q16; stable IDs preserved while source years corrected.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-010.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
