"""Recreate private review candidates only; never mutates the public/source bank."""
import copy, hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = Path(__file__).parent
pool = json.loads((ROOT / 'ops/jamb/source-pool.json').read_text(encoding='utf8'))
questions = [q for q in pool['questions'] if q['subject'] == 'chemistry'][:40]
S = {
 'reactions':'https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions',
 'salts':'https://edu.rsc.org/experiments/testing-salts-for-anions-and-cations/464.article',
 'soap':'https://www.rsc.org/suppdata/c7/rp/c7rp00133a/c7rp00133a2.pdf',
 'evaporation':'https://edu.rsc.org/download?ac=514059',
 'welding':'https://www.aws.org/magazines-and-media/welding-journal/2023/may/wj-may-23-feature-4-liston-aws-c4-a-guide-to-oxyacetylene-cutting',
 'alkanes':'https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons',
 'electrons':'https://openstax.org/books/chemistry-atoms-first-2e/pages/3-4-electronic-structure-of-atoms-electron-configurations',
 'fermentation':'https://pubs.rsc.org/en/content/articlehtml/2022/gc/d1gc04758b',
 'ester':'https://pubs.rsc.org/en/content/articlehtml/2001/gc/b007734h',
 'gas':'https://openstax.org/books/chemistry/pages/9-2-relating-pressure-volume-amount-and-temperature-the-ideal-gas-law',
 'electrolysis':'https://openstax.org/books/chemistry/pages/17-7-electrolysis',
 'displacement':'https://edu.rsc.org/cpd/displacement-reactions/4011106.article',
 'dispersants':'https://response.restoration.noaa.gov/oil-and-chemical-spills/oil-spills/resources/2-what-are-dispersants.html',
 'ph':'https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh',
 'steel':'https://edu.rsc.org/resources/alloys-of-iron-steels/4018479.article',
 'cracking':'https://edu.rsc.org/experiments/cracking-hydrocarbons-in-liquid-paraffin-with-a-catalyst/681.article',
 'atom':'https://openstax.org/books/chemistry/pages/2-3-atomic-structure-and-symbolism',
}
rows = []
def approve(i, answer, explanation, refs, *, question=None, options=None, year=None, num=None, audit='', check=None):
 q = questions[i-1]; u=copy.deepcopy(q)
 u['answer']=answer; u['ai_explanation']=explanation
 if question is not None: u['question']=question
 if options is not None: u['options']=dict(zip('ABCDE',options))
 if year: u['year']=year
 if num: u['num']=num
 u['format']=len(u['options'])
 page=5 if u['year']==1984 or u['num']>=45 else 4 if u['num']>=28 else 3 if u['num']>=14 else 2
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page,'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':explanation,'source_urls':[S[r] for r in refs],'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete stem and all options with supplied PDF; independently checked answer and replaced explanation with concise teaching text.','calculation_check':check})
def hold(i, reason, *, answer=None, num=None, year=None):
 q=questions[i-1]; y=year or q['year']; n=num or q['num']; page=5 if y==1984 or n>=45 else 4 if n>=28 else 3 if n>=14 else 2
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page,'actual_source_year':y,'actual_source_number':n,'publication_candidate':False,'hold_reason':reason,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})

approve(1,'C','Sodium hydrogensulfate, NaHSO₄, forms an acidic solution. Its hydrogen ions react with carbonate to release CO₂, which makes limewater milky. Its sulfate ions form insoluble white BaSO₄ with barium ions.',['reactions','salts'],question='X is a crystalline sodium salt. Its aqueous solution turns litmus red and releases a gas that makes limewater milky when added to sodium carbonate. With barium chloride solution, X gives a white precipitate insoluble in dilute hydrochloric acid. What is X?',options=['Na₂CO₃','NaHCO₃','NaHSO₄','Na₂SO₃','Na₂SO₄'],audit='Restored separate C and D options from supplied PDF page 2. Retained C after independent acid/carbonate/sulfate tests.')
approve(2,'D','Evaporation removes water from brine. The dissolved sodium chloride remains and crystallises as enough water is lost.',['evaporation'],year=1984,audit='The 1984 heading on PDF page 5 precedes this question. Corrected source year while preserving opaque ID; options and answer match.')
approve(3,'B','Alkaline hydrolysis of fats or oils produces the salts of fatty acids (soap) and glycerol. Glycerol is an alcohol with three hydroxyl groups.',['soap'])
approve(4,'D','Oxidation means an increase in oxidation state. Iron changes from 0 to +2 in reaction 1 and from +2 to +3 in reaction 3. It remains +2 in reaction 2 and is reduced from +3 to +2 in reaction 4. Therefore, iron is oxidised in 1 and 3.',['reactions'],num=16,question='In which of these reactions is iron oxidised?\n1. Fe + H₂SO₄ → H₂ + FeSO₄\n2. FeSO₄ + H₂S → FeS + H₂SO₄\n3. 2FeCl₂ + Cl₂ → 2FeCl₃\n4. 2FeCl₃ + SnCl₂ → 2FeCl₂ + SnCl₄',options=['1 only','2 only','3 only','1 and 3','2 and 4'],audit='Parser captured Q16 as Q2, omitted instruction and reaction 1. Recovered page 3 full context; independently balanced reactions 3/4, restored FeCl₂, changed key E to D. No official-key claim.',check='oxidation-and-balance')
hold(5,'Actual 1984 Q2: 20 cm³ H₂ consumes 10 cm³ O₂, leaving 10 cm³ at 373 K. At the stated final 298 K and equal pressure the residual volume is 10×298/373 = 7.99 cm³, absent from all options. D requires unstated remeasurement at original temperature. Do not silently ignore the temperature change.',answer=None,year=1984)
approve(6,'D','Burning acetylene in oxygen produces the hot oxy-acetylene flame used for welding and cutting suitable metals. Oxygen alone is not a fuel.',['welding'],question='The flame used by welders in cutting metals is',audit='Corrected printed cotton to cutting using coherent technical meaning and American Welding Society cutting reference; no repair text in learner copy.')
approve(7,'B','Alkanes have the general formula CₙH₂ₙ₊₂. Increasing n by one adds one carbon atom and two hydrogen atoms, so successive members differ by CH₂.',['alkanes'],options=['CH','CH₂','CH₃','CₙHₙ','CₙH₂ₙ₊₂'],check='alkane-series')
approve(8,'D','The final electrons occupy a p subshell (3p²), so the element belongs to the p block. The configuration contains 14 electrons and corresponds to silicon.',['electrons'],question='If an element has the electronic configuration 1s² 2s² 2p⁶ 3s² 3p², it is')
passage='An organic compound X has relative molecular mass 180. It is a colourless crystalline solid, readily soluble in water, containing C, H and O in the atomic ratio 1:2:1. It has a sweet taste and melts on heating. In the presence of yeast and absence of air, X forms compound Y and a colourless gas. Y reacts with sodium to release gas Z, which gives a pop with a lighted splint. Y also reacts with ethanoic acid to form a sweet-smelling compound W.\n\n'
approve(9,'D','Yeast converts glucose to ethanol, so Y is ethanol. Ethanol reacts with ethanoic acid to form ethyl ethanoate and water. Ethyl ethanoate belongs to the ester family, making W an ester.',['fermentation','ester'],question=passage+'Compound W is',audit='Recovered shared passage for Q8–10 from PDF page 2; removed duplicated clause and changed glowing to lighted splint for correct hydrogen test. Changed wrong key A to D; previous soap explanation ignored passage.')
approve(10,'B','The atomic ratio gives empirical formula CH₂O, with formula mass 12 + 2 + 16 = 30. The molecular mass is 180, so the multiplier is 180 ÷ 30 = 6. The molecular formula is C₆H₁₂O₆.',['fermentation'],question=passage+'The molecular formula of X is',options=['C₁₂H₂₂O₁₁','C₆H₁₂O₆','C₃H₆O₃','C₇H₁₄O₇','C₄H₃O₄'],audit='Recovered full passage; independently calculated empirical-to-molecular multiplier; changed wrong key A to B.',check='molecular-formula')
approve(11,'C','Yeast ferments glucose without air to form ethanol and carbon dioxide: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. This process is central to brewing.',['fermentation'],question=passage+'The reaction of X with yeast forms the basis of which industry?',audit='Recovered passage and corrected basis wording; retained C after checking fermentation equation.')
approve(12,'B','For a fixed amount of ideal gas, PV = nRT. Rearranging gives P = nR(T/V). Since nR is constant, P is proportional to T/V, with T measured in kelvin.',['gas'],question='For a fixed amount of ideal gas, which relationship connects pressure P, volume V and absolute temperature T?',options=['P ∝ VT','P ∝ T/V','PT ∝ V','PV ∝ VT','P ∝ V/T'],audit='Restored proportionality notation from printed ampersands and made fixed amount/absolute temperature explicit; no changed numerical data.',check='ideal-gas')
hold(13,'Figure on PDF page 2 heats ammonium chloride behind a porous plug; NH₃ diffuses faster than HCl, so damp neutral litmus initially turns blue (D), not C. Complete figure needs an owned accessible redraw before intake; previous chlorine explanation is unrelated.',answer='D')
approve(14,'C','Calcium produces a brick-red (orange-red) flame. Sodium gives yellow, potassium lilac, and copper a blue-green flame.',['salts'])
hold(15,'The PDF explicitly states ΔH = +Q for the forward equilibrium. Increasing temperature favours product, but no option says this. D decreases temperature and therefore favours reactants. A lowers reactant concentration; catalyst C does not alter equilibrium. B is direct addition of product, creating wording ambiguity rather than a valid Le Chatelier shift. Complete corrected source needed.')
hold(16,'Independent Faraday calculation gives 0.63/63×2×108 = 2.16 g Ag (D) for the series cells shown on PDF page 3. Stem omits deposited silver and figure must be redrawn/attached with series connection intact. Candidate remains excluded until complete apparatus restoration.',answer='D')
approve(17,'E','Iron is more reactive than copper and more readily loses electrons. Fe is oxidised to Fe²⁺ while Cu²⁺ gains those electrons and becomes copper metal.',['displacement'],question='In Fe + Cu²⁺ → Fe²⁺ + Cu, iron displaces copper from its ions because',options=['iron is metallic while copper is ionic','the atomic weight of copper is greater than that of iron','copper metal has more electrons than iron metal','iron is an inert metal','iron is higher in the electrochemical series than copper'])
hold(18,'The displayed structure is CH₂=C(CH₃)CH₂CH₃, correctly named 2-methylbut-1-ene, but the PDF prints that same correct name in both A and C. Do not invent a replacement distractor or choose one duplicate. Needs corroborated full options plus accessible structure.',answer='A and C')
approve(19,'A','Efflorescence is the loss of water of crystallisation from a hydrated salt on exposure to air. It differs from deliquescence, in which a solid absorbs enough moisture to dissolve.',['reactions'],question='Sodium sulfate decahydrate (Na₂SO₄·10H₂O) loses water of crystallisation on exposure to air. This process is known as',audit='Restored sodium sulfate name and hydrate dot. Independent definition check; reaction source supports general hydrate context but is not claimed to define efflorescence.')
approve(20,'E','At the anode, chloride ions lose electrons: 2Cl⁻ → Cl₂ + 2e⁻. Loss of electrons is oxidation. At the cathode, sodium ions gain electrons to form sodium metal.',['electrolysis'])
approve(21,'D','Detergents contain surfactants that help break oil into small droplets dispersed in water. Dispersion does not destroy the oil; real spill treatment uses selected dispersants and considers environmental conditions.',['dispersants'],question='Crude petroleum pollution on creeks and waterways can be dispersed by',options=['heating the affected water to boil off the petroleum','mechanically stirring to dissolve petroleum in water','pouring organic solvents into the water','spraying the water with detergents','cooling to freeze out the petroleum'],audit='Cleaned spelling and separated physical dispersion from actual removal in teaching explanation. Retained textbook conceptual option D, not operational spill-cleanup instruction.')
hold(22,'Intended answer D conflates gaining electrons with electronegativity, which specifically describes attraction for shared/bonding electrons. The supplied question has no precise option. Needs independently corroborated original wording or a separately identified newly authored practice item.',answer='D intended')
approve(23,'E','Higher pH corresponds to lower hydrogen-ion concentration. Z has the highest pH, 9.0, and is therefore the least acidic. X, with pH 3.0, is more acidic than Y, with pH 5.0.',['ph'],question='Solutions X, Y and Z have pH values 3.0, 5.0 and 9.0 respectively. Which statement is correct?',options=['All the solutions are acidic','All the solutions are basic','Y and Z are more acidic than water','Y is more acidic than X','Z is the least acidic'],check='ph-order')
hold(24,'The PDF has a malformed first option and suspicious enthalpies −2.86 kJ for water formation and −406 kJ for carbon dioxide formation. C follows printed magnitudes, but the source data/options need corroboration before a scientifically reliable teaching item is released.',answer='C from printed magnitudes')
hold(25,'Lead lies above hydrogen thermodynamically but forms an insoluble PbCl₂ surface layer in dilute HCl; wording dissolve gives C versus D ambiguity. Do not repeat the old unconditional claim that all three dissolve. Needs original wording and conditions.')
approve(26,'B','Stainless steel is an iron alloy containing chromium and usually some carbon. Chromium forms a protective surface oxide that improves corrosion resistance.',['steel'],question='Stainless steel is an alloy containing',options=['carbon, iron and lead','carbon, iron and chromium','carbon, iron and copper','carbon, iron and silver','carbon and iron only'])
approve(27,'A','H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. The NaOH amount is 0.1 × 20/1000 = 0.002 mol. Half as many moles of H₂SO₄ are needed: 0.001 mol. Its volume is 0.001/0.50 = 0.002 dm³ = 2.0 cm³.',['reactions'],question='What volume of 0.50 mol dm⁻³ H₂SO₄ exactly neutralises 20 cm³ of 0.10 mol dm⁻³ NaOH?',options=['2.0 cm³','5.0 cm³','6.8 cm³','8.3 cm³','10.4 cm³'],audit='Correct key A retained, but old displayed formula led to 8 rather than 2 and was replaced with balanced stoichiometry.',check='neutralization')
hold(28,'Old B explanation falsely says H₂ is already oxidised/unreactive. C (NO₂ and SO₃) is the likely conventional key, but a temperature-qualified direct-oxidation claim needs specific corroboration and reaction conditions. Do not approve solely from oxidation numbers.',answer='C provisional')
hold(29,'No option cleanly represents conventional extraction: iron thermal reduction, copper thermal extraction with possible electrolytic refining, aluminium electrolysis after ore preparation. Old E falsely describes thermal reduction of aluminium. Verify complete original options before release.')
approve(30,'A','Copper(II) nitrate requires nitrate ions. CuO reacts with nitric acid to form Cu(NO₃)₂ and water. Sulfuric acid would instead produce copper(II) sulfate, so step A cannot make the requested salt.',['reactions'],question='A student prepares pure Cu(NO₃)₂ crystals starting with CuO. Which reported step is incorrect?',options=['Some CuO was reacted with excess dilute H₂SO₄','The solution was concentrated','After cooling, the crystals were separated by filtration','The crystals were washed with very cold water','The crystals were allowed to dry'])
hold(31,'The >95% threshold is imprecise: ordinary fractionation can approach about 95.6% ethanol by mass, while removal beyond the azeotrope needs drying. C is intended, but A is not strictly excluded by the supplied threshold and unspecified purity basis. Verify source before release.',answer='C intended')
hold(32,'Pressure alone does not determine density without conditions: heating a sealed rigid container increases pressure at constant density. D requires compression/fixed-temperature context that is absent from the PDF. Needs original context or separately authored item.',answer='D if isothermal compression')
approve(33,'C','The formula mass of KClO₃ is 39 + 35.5 + 3×16 = 122.5. The dissolved amount is 3.06/122.5 ≈ 0.0250 mol in 10 cm³ of water. Per dm³ of water, this is 0.0250×100 = 2.50 mol.',['reactions'],question='At 25 °C, 3.06 g of KClO₃ saturates 10 cm³ of water. Express the solubility in mol per dm³ of water. [K = 39, Cl = 35.5, O = 16]',options=['5.0 mol dm⁻³','3.0 mol dm⁻³','2.5 mol dm⁻³','1.0 mol dm⁻³','0.5 mol dm⁻³'],audit='Recovered missing D/E option boundaries from PDF page 4. Restored chloride symbol and negative unit exponent. Explicitly uses solvent-volume solubility rather than falsely treating 10 cm³ water as measured final solution volume.',check='solubility')
approve(34,'C','Cracking splits larger hydrocarbon molecules into smaller alkanes and alkenes. This increases the supply of shorter hydrocarbons useful in petrol and other engine fuels.',['cracking'])
approve(35,'B','CuSO₄ contains sulfate ions, which give white BaSO₄ with barium chloride. Its copper ions produce a blue-green flame. Ammonium sulfate can give the sulfate precipitate but does not give the copper flame colour.',['salts','reactions'],question='Which solution gives a white precipitate with barium chloride solution and a green flame test?',options=['Na₂SO₄','CuSO₄','CaSO₄','CaCl₂','(NH₄)₂SO₄'],audit='Changed erroneous key E to B. Removed invented potassium-contamination justification; both independent identification tests must match.')
approve(36,'D','Almost all atomic mass comes from the nucleus. Protons and neutrons each have a mass close to 1 u; electrons contribute very little. The total number of protons and neutrons is the mass number.',['atom'])
hold(37,'E correctly identifies acid-base neutralisation, but options A and D are incomplete even in supplied PDF pages 4–5. Complete distractors must be restored before release; do not invent missing reactants.',answer='E')
hold(38,'B is intended: sodium with water produces hydrogen, not oxygen. However C says nitrogen is insoluble rather than sparingly soluble, making a literal FALSE question ambiguous. The copper(I) preparation statement also requires conditions. Need accurate complete source or revised independent item.',answer='B intended')
hold(39,'Supplied PDF page 5 has an incomplete dissolves-is stem and malformed formula HaNO₂. The thermal observation/solvent/conditions are absent. Lattice breaking alone cannot establish net dissolution enthalpy; do not approve old B reasoning.')
approve(40,'A','Powdered zinc has a larger exposed surface area than the same mass in pellets. More zinc is in contact with the acid at once, so more successful collisions can occur per second.',['reactions'],question='Zn + H₂SO₄ → ZnSO₄ + H₂. Which change greatly increases the rate of this reaction under otherwise identical conditions?',options=['using powdered zinc','using a greater volume of acid','using a smaller volume of acid','placing the reaction vessel in an ice bath','using zinc pellets'],audit='Corrected impossible ZnCl₂ product to ZnSO₄ by atom conservation; corrected powdered wording. No new chlorine can appear in reaction. Fixed comparative conditions.',check='zinc-balance')

assert len(rows)==40
rows.sort(key=lambda r: [q['id'] for q in questions].index(r['id']))
result={'schema_version':1,'batch_id':'chemistry-earliest-normalized-001','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','source_authority':{'status':'authorized-by-owner','basis':'Owner supplied past-question reuse and independent AI verification instruction; no exam-board/teacher approval claimed'},'scope':'First 40 normalized Chemistry records, visually compared with PDF pages 2–5. Two records belong to 1984; the other 38 belong to 1983. Parser omissions outside these IDs are not counted as reviewed.','publication_contract':'Candidate content is ready for coordinator intake subject to shared trust method and fingerprint validation. Private history/held reasons must never enter learner explanations. No shared/public files mutated.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-001.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps(result['counts']))
