"""Private Chemistry review, normalized records 161–200. No shared bank writes."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]; OUT=Path(__file__).parent
qs=[q for q in json.loads((ROOT/'ops/jamb/source-pool.json').read_text(encoding='utf8'))['questions'] if q['subject']=='chemistry'][160:200]
RX='https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'
GAS='https://openstax.org/books/chemistry-2e/pages/9-4-effusion-and-diffusion-of-gases'
EL='https://openstax.org/books/chemistry/pages/17-7-electrolysis'
REB='https://elearning.reb.rw/pluginfile.php/11670/mod_resource/content/1/S3%20Chemistry%20SB.pdf'
rows=[]
def page(q):
 if q['year']==1986:return 16
 return 17 if q['num']<=16 else 18 if q['num']<=31 else 19
def yes(i,a,e,urls,*,question=None,options=None,year=None,audit='',check=None):
 q=qs[i-161];u=copy.deepcopy(q)
 if year:u['year']=year
 if question:u['question']=question
 if options:u['options']=dict(zip('ABCDE',options))
 u['answer']=a;u['ai_explanation']=e;u['format']=len(u['options'])
 rows.append({'id':q['id'],'before':q,'update':u,'source_pdf_page':page(u),'actual_source_year':u['year'],'actual_source_number':u['num'],'publication_candidate':True,'review_method':'ai-calculation-checked' if check else 'ai-source-checked','independent_reasoning':e,'source_urls':urls,'source_checked_at':'2026-09-12','private_repair_history':audit or 'Compared complete question and options against the supplied PDF; independently solved and wrote a teaching explanation.','calculation_check':check})
def no(i,why,*,year=None,answer=None):
 q=qs[i-161];temp={**q,'year':year or q['year']}
 rows.append({'id':q['id'],'before':q,'update':None,'source_pdf_page':page(temp),'actual_source_year':temp['year'],'actual_source_number':temp['num'],'publication_candidate':False,'hold_reason':why,'independently_indicated_answer':answer,'source_checked_at':'2026-09-12'})

METAL='https://openstax.org/books/chemistry-2e/pages/18-2-occurrence-and-preparation-of-the-representative-metals'
ORG='https://openstax.org/books/chemistry-2e/pages/20-1-hydrocarbons'
FOUNTAIN='https://edu.rsc.org/experiments/ammonia-fountain-demonstration/979.article'
THIO='https://edu.rsc.org/download?ac=522804'
yes(161,'B','The four water molecules require eight hydrogen atoms, so y = 8. Nitrogen balance then gives 8 = 2x + z. Oxygen balance gives 24 = 6x + 4 + z. Subtracting these equations gives x = 3, then z = 2. The balanced equation is 3Cu + 8HNO₃ → 3Cu(NO₃)₂ + 4H₂O + 2NO.',[RX],question='What are x, y and z respectively in the balanced equation xCu + yHNO₃ → xCu(NO₃)₂ + 4H₂O + zNO?',options=['4, 1, 2','3, 8, 2','2, 8, 3','8, 3, 2'],check='copper-nitric-balance')
yes(162,'B','Hot sodium hydroxide dissolves the aluminium-containing component as aluminate. The iron(III) oxide impurity remains insoluble and can be filtered off. This separates the impurity without dissolving it along with the aluminium.',[METAL],question='How is iron(III) oxide impurity separated during purification of bauxite?',options=['Fractional crystallisation in acid solution','Treatment with sodium hydroxide followed by filtration','Extraction with concentrated ammonia followed by reprecipitation','Electrolysis of the molten mixture'],audit='Clarified B so it does not imply that iron oxide is the component dissolved by sodium hydroxide.')
yes(163,'C','Potassium ions give a lilac flame. Sulfate ions form a white barium sulfate precipitate with acidified barium chloride. K₂SO₄ provides both ions, while each other option fails at least one test.',['https://edu.rsc.org/experiments/testing-salts-for-anions-and-cations/464.article'],question='Which compound gives a lilac flame and a white precipitate with acidified barium chloride solution?',options=['KCl','NaNO₃','K₂SO₄','CaSO₄'],audit='Restored missing sulfate oxygen subscript in C from the two independent qualitative tests and charge-balanced sulfate formula. PDF prints K₂SO.')
yes(164,'D','A very reactive metal is obtained by reducing its ions during electrolysis of a molten salt. In an aqueous salt solution, water can be reduced instead, and any highly reactive metal formed would react with the water.',[METAL,EL],question='Which extraction method is appropriate for a highly reactive metal that reacts violently with air and dilute acids?',options=['Electrolysis of an aqueous salt solution','Thermal decomposition of its oxide','Displacement from an aqueous solution by an alkali metal','Electrolysis of a molten salt'],audit='Expanded fused to molten and made aqueous alternatives explicit; retained original extraction distinction.')
no(165,'B is the likely intended incorrect statement, but glucose/chromate colour change at 0 °C depends on pH, concentration and observation time; source has no acidification or duration. A, C and D are standard reactions after formula repairs. Need a reliable original/reaction-condition qualifier before asserting immediate colour behaviour.',answer='B intended')
yes(166,'B','Tetraethyllead was historically added to petrol to suppress engine knocking by altering combustion chemistry. It is the antiknock additive among these choices.',['https://www.rsc.org/images/Michael_Wade_tcm18-235157.pdf'],question='Which compound was historically used as an antiknock additive in petrol for automobile engines?',options=['Tetramethylsilane','Tetraethyllead','Glycerol','n-Heptane'],audit='Changed present-tense use to historical use, avoiding an inaccurate current-fuel claim or recommendation.')
yes(167,'B','Saponification is the alkaline hydrolysis of fats and oils. Palm oil reacts with the alkaline solution to produce glycerol and salts of fatty acids; the fatty-acid salts are soap.',['https://edu.rsc.org/exhibition-chemistry/soap-from-bacon-the-dangers-of-alkaline-solutions/2020068.article'],question='What reaction produces soap when palm oil is treated with an alkaline potash solution?',options=['Neutralisation','Saponification','Etherification','Salting out'],audit='Clarified the soap-producing reaction; foam alone is not a unique chemical identification test.')
no(168,'Ethanol with concentrated H₂SO₄ can form ether or ethene depending on temperature and relative conditions. C is intended at sufficient temperature, but the source gives no temperature and the omitted ether pathway matters. Recover the actual condition before assigning an unconditional dehydration-to-ethene key.',answer='C at ethene-forming temperature')
yes(169,'B','Stepwise replacement of methane hydrogen atoms by chlorine gives CH₃Cl, CH₂Cl₂, CHCl₃ and eventually CCl₄. These direct substitution products retain one carbon atom. C₂H₅Cl has two carbon atoms and is not one of them.',[ORG],question='Which compound is not a direct substitution product when chlorine replaces hydrogen atoms in methane?',options=['CH₃Cl','C₂H₅Cl','CH₂Cl₂','CHCl₃'],audit='Specified direct substitution to avoid the false absolute assertion that radical coupling side products can never contain two carbons.',check='methane-substitution')
yes(170,'B','An acyclic alkane has formula CₙH₂ₙ₊₂. Replacing one hydrogen atom with a halogen atom X gives CₙH₂ₙ₊₁X, the formula for a saturated acyclic monohaloalkane.',[ORG],question='What is the general formula of a saturated acyclic alkyl monohalide, where X is a halogen atom?',options=['CₙH₂ₙ₋₂X','CₙH₂ₙ₊₁X','CₙH₂ₙ₊₂X','CₙH₂ₙX'],audit='Restored subscripts and removed stray leading dash in B; specified the family for which the formula applies.',check='monohalide-hydrogens')
yes(171,'B','Nylon and rubber are polymers made by linking many small molecular units. Nylon can form by condensation polymerisation, while common synthetic rubbers form from unsaturated monomers. Soap and margarine are produced by different reactions.',['https://openstax.org/books/organic-chemistry/pages/14-6-diene-polymers-natural-and-synthetic-rubbers','https://openstax.org/books/organic-chemistry/pages/21-9-polyamides-and-polyesters-step-growth-polymers'],question='Which pair consists of materials made by polymerisation?',options=['Nylon and soap','Nylon and rubber','Soap and butane','Margarine and nylon'])
yes(172,'B','Starch is first hydrolysed to fermentable sugars. Yeast then converts glucose into ethanol and carbon dioxide: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. Distillation can subsequently separate the ethanol but does not create it.',['https://pmc.ncbi.nlm.nih.gov/articles/PMC5069817/'],question='After starch has been hydrolysed to sugars, which process converts those sugars into ethyl alcohol?',options=['Distillation','Fermentation','Isomerisation','Cracking'],audit='Made the necessary starch-hydrolysis stage explicit; removed page marker from D. No claim that ordinary yeast directly ferments intact starch.',check='fermentation-balance')
yes(173,'A','Atomic numbers 12 and 9 identify magnesium and fluorine. Magnesium loses two electrons to form Mg²⁺, while two fluorine atoms each gain one electron to form F⁻. Their electrostatic attraction forms ionic MgF₂.',['https://openstax.org/books/chemistry-2e/pages/7-1-ionic-bonding'],question='Elements X and Y have atomic numbers 12 and 9 respectively. What type of bonding occurs in their compound?',options=['Ionic','Covalent','Neutral','Coordinate'],audit='Corrected covalent spelling and removed stray punctuation; independently identified the elements.',check='magnesium-fluoride-charge')
yes(174,'B','Relative atomic mass is the abundance-weighted mean of isotopic masses: (0.90 × 16) + (0.10 × 18) = 16.2.',[RX],question='Element Z consists of 90% ¹⁶₈Z and 10% ¹⁸₈Z. Using the mass numbers as isotope masses, what is its relative atomic mass?',options=['16.0','16.2','17.0','17.8'],audit='Restored both isotope mass and atomic-number annotations from PDF page 17.',check='isotope-average')
yes(175,'B','A larger electronegativity difference causes the bonding electrons to be shared less equally. The resulting partial charges are larger, so the bond is more polar.',['https://openstax.org/books/chemistry-2e/pages/7-2-covalent-bonding'],question='As the electronegativity difference between bonded atoms increases, which statement is generally correct?',options=['The bond polarity decreases','The bond polarity increases','The bond becomes weaker','The substance is more likely to consist of molecules'],audit='Recovered C from text merged into B. Source labels final option E without D; normalised four visible alternatives to A–D.')
yes(176,'D','Alum helps fine suspended particles clump together into larger flocs that can settle or be filtered out. This coagulation step removes suspended matter; it is distinct from disinfection.',['https://www.open.edu/openlearn/science-maths-technology/what-chemical-compounds-might-be-present-drinking-water/content-section-4.1.2/?printable=1'],question='What is the principal role of alum in treatment of a town water supply?',options=['To kill bacteria','To control water pH','To improve water taste','To coagulate fine mud particles'])
no(177,'A is the intended untreated-permanent-hardness answer, and D is wrong because permutit removes Ca²⁺. However distinct samples have no starting concentrations; permanently hard water can be less concentrated than residual calcium in another sample. Recover comparison conditions or approve an explicitly adapted equal-initial-hardness exercise rather than imply a universal titre ranking.',answer='A under usual comparable-sample assumption')
no(178,'Detergent/dispersant does not remove oil and may increase exposure within the water column. Burning and dispersal require site-specific assessment; no generic best safe cleanup follows for ponds/creeks. Needs an environmentally sound, sourced scenario rather than a blanket spray-detergent instruction.',answer='B historical intended, not a general cleanup recommendation')
yes(179,'D','Na₃AsO₄ has molar mass 3×23 + 75 + 4×16 = 208 g mol⁻¹. The hydrate has mass 208 + 12×18 = 424 g mol⁻¹. Thus 38.9 g hydrate contains 38.9×208/424 = 19.08 g Na₃AsO₄. The solution mass is 100 + 38.9 = 138.9 g, giving 19.08/138.9×100 = 13.7%.',[RX],question='The solubility of Na₃AsO₄·12H₂O is 38.9 g per 100 g of water. What is the mass percentage of Na₃AsO₄ in the saturated solution? [Na = 23, As = 75, O = 16, H = 1]',options=['87.2%','38.9%','19.1%','13.7%'],audit='Corrected physically false supplied O=12 to standard O=16. Restored hydrate dot and changed old C to D. Included water of crystallisation in total solution mass.',check='hydrate-percentage')
yes(180,'A','Lime juice contains acids that react with bicarbonate to release CO₂. Ethanol is not acidic enough to release CO₂ from sodium bicarbonate. Thus gas forms with lime juice but not with ethanol.',[RX],question='Which pair of reported observations is correct for fresh lime juice and ethanol respectively?',options=['Adding NaHCO₃: gas evolves; no gas evolves','Methyl orange: turns colourless; no change','Taste: bitter; sour','Adding sodium: no gas evolves; hydrogen evolves'],audit='Recovered all three table columns as complete alternative text. Retained the theoretical taste distractor as reported observation, not an instruction to taste laboratory substances.')
no(181,'C is the conventional ordering but the source provides no concentrations, and milk of magnesia is a suspension with solubility-limited OH⁻. Arbitrarily dilute strong acid/base solutions need not rank as stated. C also has corrupted sodium-chloride wording. Need defined comparable concentrations or a qualitative acid/neutral/base classification adaptation.',answer='C conventional only')
yes(182,'A','HCl and NaOH react in a 1:1 mole ratio. At equivalence, c(HCl) = 0.15 × 24.83/39.45 = 0.09441 mol dm⁻³, corresponding to 0.094 mol dm⁻³.',[RX],question='A 24.83 cm³ sample of 0.15 mol dm⁻³ NaOH requires 39.45 cm³ of HCl to reach equivalence. What is the HCl concentration?',options=['0.094 mol dm⁻³','0.150 mol dm⁻³','0.940 mol dm⁻³','1.500 mol dm⁻³'],check='acid-titration')
no(183,'One faraday deposits at most 0.5 mol Cu, so the old C key is false. B holds with an inert anode because water oxidation generates H⁺; with a copper anode copper dissolves instead. Source does not specify electrode material, solution volume or current efficiency, so no unconditional listed answer is justified.',answer='B for inert anode')
yes(184,'C','The time is 2.5×3600 = 9000 s, so charge is 2×9000 = 18000 C. Mg²⁺ requires two electrons, giving mass = 18000×24/(2×96500) = 2.238 g, or 2.24 g.',[EL],question='What mass of magnesium is deposited when 2 A flows for 2 hours 30 minutes through molten MgCl₂? Assume 100% current efficiency. [Mg = 24; F = 96500 C mol⁻¹]',options=['1.12 g','2.00 g','2.24 g','4.48 g'],check='magnesium-electrolysis')
yes(185,'C','Copper in CuO has oxidation state +2 and gains two electrons to become Cu. One mole of copper therefore requires two moles of electrons: 2×6.0×10²³ = 1.2×10²⁴ electrons.',[RX],question='For 3CuO + 2NH₃ → 3Cu + 3H₂O + N₂, how many electrons are transferred per mole of copper produced? Use Avogadro constant 6.0 × 10²³ mol⁻¹.',options=['4.0 × 10⁻²³','3.0 × 10⁻²³','1.2 × 10²⁴','6.0 × 10²⁴'],audit='Restored complete N₂ product and grammatical per-mole statement. Made the rounded Avogadro convention explicit; no change to answer meaning.',check='copper-electrons')
yes(186,'B','The molar mass of NH₄NO₃ is 80 g mol⁻¹, so 5 g is 0.0625 mol. Cooling the surroundings means the dissolution absorbs heat. Its enthalpy is +1.6/0.0625 = +25.6 kJ mol⁻¹.',[RX],question='Dissolving 5 g of NH₄NO₃ in water absorbs 1.6 kJ from the water and container. What is its molar enthalpy of solution? [N = 14, O = 16, H = 1]',options=['+51.4 kJ mol⁻¹','+25.6 kJ mol⁻¹','+12.9 kJ mol⁻¹','−6.4 kJ mol⁻¹'],audit='Corrected old A to B and replaced dimensionally incorrect cooled-by-kJ wording with absorbed heat.',check='heat-solution')
yes(187,'B','By Hess’s law, reaction enthalpy equals product formation enthalpy minus the total for reactants: −811 − [(−395) + (−286)] = −130 kJ mol⁻¹. The negative sign means heat is released.',['https://openstax.org/books/chemistry-2e/pages/5-3-enthalpy'],question='Calculate the enthalpy change for SO₃(g) + H₂O(l) → H₂SO₄(l), given formation enthalpies of −395, −286 and −811 kJ mol⁻¹ respectively.',options=['−1032 kJ mol⁻¹','−130 kJ mol⁻¹','+130 kJ mol⁻¹','+1032 kJ mol⁻¹'],audit='Restored sulfuric acid oxidation-state name by using formula and completed missing calculate-enthalpy question; retained supplied numerical data.',check='hess-law')
yes(188,'A','For the same visible amount of sulfur, the average reaction rate is proportional to 1/time. The times halve from 72 to 36 to 18 seconds for successive 10 °C increases. The corresponding rates therefore double at each step in these data.',[THIO],question='Equal reaction mixtures of sodium thiosulfate and hydrochloric acid reach the same sulfur-cloudiness endpoint in these times:\n25 °C: 72 s\n35 °C: 36 s\n45 °C: 18 s\nWhat do these results show over this temperature range?',options=['The rate doubles for each 10 °C temperature rise','The rate halves for each 10 °C temperature rise','Endpoint time is independent of temperature','The rate triples for each 10 °C temperature rise'],audit='Recovered source table from PDF page 18. Replaced chemically impossible iodine product with sulfur, justified by thiosulfate/acid atom conservation and RSC experiment. Specified common endpoint and restricted empirical temperature rule to given range.',check='rate-table')
yes(189,'C','The forward reaction is exothermic. Lowering the equilibrium temperature favours the heat-producing direction, increasing the equilibrium yield of SO₃. A catalyst speeds approach to equilibrium without changing the equilibrium yield.',['https://openstax.org/books/chemistry-2e/pages/13-3-shifting-equilibria-le-chateliers-principle'],question='For 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), ΔH = −196 kJ, which change increases the equilibrium yield of SO₃?',options=['Adding a suitable catalyst','Increasing the reaction temperature','Decreasing the reaction temperature','Decreasing the SO₂ concentration'],audit='Restored equilibrium arrow and ΔH; corrected C from temperature of SO₂ to temperature of the reaction mixture, and specified equilibrium yield rather than production rate.')
yes(190,'B','Hot concentrated alkali converts chlorine into chloride and chlorate(V): 3Cl₂ + 6OH⁻ → ClO₃⁻ + 5Cl⁻ + 3H₂O. Chlorine is both oxidised to +5 and reduced to −1, so the reaction is disproportionation.',[RX,'https://www.cdc.gov.ss/read?book=Secondary-Chemistry-3-Student-Textbook.pdf'],question='Which ionic equation represents chlorine reacting with hot concentrated aqueous sodium hydroxide?',options=['Cl₂(g) + 2OH⁻(g) → OCl⁻(aq) + Cl⁻(aq) + H₂O(l)','3Cl₂(g) + 6OH⁻(aq) → ClO₃⁻(aq) + 5Cl⁻(aq) + 3H₂O(l)','3Cl₂(g) + 6OH⁻(aq) → ClO₃⁻(s) + 5Cl⁻(aq) + 3H₂O(l)','3Cl₂(g) + 6OH⁻(aq) → 5ClO₃⁻(aq) + Cl⁻(aq) + 3H₂O(l)'],audit='Restored lost ion charges, arrows and state labels. Preserved wrong gas/solid state distractors A/C and unbalanced D; specified sodium hydroxide to resolve salt context.',check='chlorate-disproportionation')
yes(191,'A','Magnesium reacts with nitrogen to form Mg₃N₂. Water hydrolyses this nitride: Mg₃N₂ + 6H₂O → 3Mg(OH)₂ + 2NH₃. The ammonia gives dense white NH₄Cl fumes with HCl, identifying the original gas as nitrogen.',['https://uwaterloo.ca/centre-advanced-science-education/news/magnesium-nitride-formed-combustion-magnesium',FOUNTAIN],question='Magnesium burns in gas P to form a solid residue Q. Adding water to Q releases a gas that forms dense white fumes with hydrogen chloride. What is gas P?',options=['Nitrogen','Chlorine','Oxygen','Sulfur dioxide'],audit='Removed false white colour assigned to pure magnesium nitride in source; nitride is yellow/greenish yellow, unlike MgO. Retained full reaction chain and identifying observations.',check='magnesium-nitride')
yes(192,'A','Immediately flush the affected skin with plenty of running water and remove contaminated clothing while rinsing. Alert the teacher and obtain medical attention. Do not try to neutralise the acid on the skin with an alkali; the reaction can add heat and worsen the injury.',['https://www.cdc.gov/niosh/npg/npgd0577.html','https://www.cdc.gov/niosh/npg/firstaid.html','https://myschool.ng/classroom/chemistry/14535?filter=oldest'],question='A student accidentally spills concentrated sulfuric acid on their skin. Which should be used immediately to flush the affected area?',options=['Plenty of cool running water','Sodium hydroxide solution','Iodine solution','Sodium carbonate solution'],audit='Changed unsafe old D key to A. Recovered corrupt B as sodium hydroxide from matching 1987 Myschool transcription; independent answer and first-aid wording checked against CDC. No repair history belongs in learner explanation.')
yes(193,'D','Oxygen has the allotropes O₂ and O₃. Sulfur also has distinct structural forms, including rhombic and monoclinic sulfur. Thus both elements in the oxygen–sulfur pair exhibit allotropy under ordinary conditions.',['https://openstax.org/books/chemistry-2e/pages/18-9-occurrence-preparation-and-compounds-of-oxygen','https://edu.rsc.org/experiments/allotropes-of-sulfur/686.article'],question='Which pair consists of elements that both have familiar allotropes under ordinary conditions?',options=['Phosphorus and hydrogen','Oxygen and chlorine','Sulfur and nitrogen','Oxygen and sulfur'],audit='Added ordinary-conditions scope to distinguish familiar school allotropy from exotic high-pressure phases or nuclear-spin isomers.')
yes(194,'C','Ammonia and hydrogen chloride are highly soluble in water. When either dissolves rapidly inside the flask, the pressure falls and outside air pressure pushes water in, producing a fountain. Nitrogen and nitrous oxide are much less suitable.',[FOUNTAIN,'https://edu.rsc.org/solubility/the-properties-of-hydrogen-chloride/834.article'],question='Which gases are suitable for the classic water-fountain experiment?\n(i) Nitrogen\n(ii) Ammonia\n(iii) Nitrogen(I) oxide\n(iv) Hydrogen chloride',options=['(ii) and (iii)','(i) and (iii)','(ii) and (iv)','(ii) only'])
yes(195,'C','Heating an ammonium salt with calcium hydroxide releases ammonia. It can be dried by passing it directly through calcium oxide. Water absorbs ammonia, while concentrated sulfuric acid and calcium chloride react with it.',[FOUNTAIN],question='Ammonia is produced by heating calcium hydroxide with ammonium sulfate. Which treatment dries the gas before collection?',options=['Bubbling it through concentrated H₂SO₄','Bubbling it through water, then passing it through CaO','Passing it directly through CaO','Passing it directly through CaCl₂'],audit='Corrected wrong B to C. Source confuses drying path with collection method; clarified drying before collection without inventing collection apparatus.')
no(196,'None of Cl, Mg, Ag or Mn provides the usual simple amphoteric oxide dissolving in both dilute HNO₃ and aqueous NaOH under the stated conditions. MnO₂ requires different redox/fusion conditions, so old D is not a justified acid/base answer. Recover likely missing Al/Zn/Sn alternative or original conditions.')
yes(197,'C','Stainless steel is an iron-based alloy containing carbon and chromium. Chromium forms a protective oxide layer that improves corrosion resistance. Some grades contain additional elements such as nickel.',['https://openstax.org/books/chemistry-2e/pages/17-6-corrosion'],question='Which listed set of elements is characteristic of stainless steel?',options=['Iron, carbon and silver','Iron, carbon and lead','Iron, carbon and chromium','Iron and carbon only'])
yes(198,'D','A common way to make an alloy is to mix the constituent elements in a molten metallic mixture and then allow it to solidify. Mixing them before solidification distributes the components through the alloy.',['https://openstax.org/books/additive-manufacturing-essentials/pages/3-2-metallic-materials'],question='Which option describes the usual melt-based method of preparing an alloy?',options=['Arc welding the metals together','Electrolysis with the main metal as cathode','Reducing a mixture of the elements’ oxides','Cooling a molten mixture of the required elements'],audit='Corrected are/arc typo. Limited claim to usual melt-based method; powder metallurgy and other alloying methods also exist.')
yes(199,'D','All metals can suffer corrosion in a suitable environment, although their resistance differs greatly. Even noble metals can be attacked under particular conditions. Rusting is the specific corrosion of iron, not the name for all metal corrosion.',['https://nepis.epa.gov/Exe/ZyPURL.cgi?Dockey=P1005PMH.TXT'],question='Which is the broadest correct statement about metals capable of corrosion in a suitable environment?',options=['Iron only','Electropositive metals only','Only metals below hydrogen in the electrochemical series','All metals'],audit='Changed incorrect old C to D and made environment dependence and broadest-set question explicit.')
yes(200,'C','Carbon has four valence electrons. In the valence-bond description of methane, one 2s orbital and three 2p orbitals mix to form four sp³ hybrid orbitals, each used in a C–H bond. This accounts for four equivalent tetrahedral bonds.',['https://openstax.org/books/chemistry-2e/pages/8-2-hybrid-atomic-orbitals'],question='Carbon has ground-state configuration 1s²2s²2p². Which statement about its 2s and 2p orbitals is consistent with the valence-bond explanation of four equivalent bonds in methane?',options=['The separate 2s and 2p orbitals initially have equal energies','Electrons in the separate 2s and 2p orbitals are already equivalent','The 2s and 2p orbitals hybridise','Six orbitals hybridise to make four orbitals'],audit='Restored configuration and explicitly tied simplified hybridisation explanation to methane. Avoided treating hybridisation alone as a universal cause of carbon valency or all carbon bonding.')

assert len(rows)==40
b={'schema_version':1,'batch_id':'chemistry-earliest-normalized-005','reviewed_at':'2026-09-12','reviewer':'Codex (AI), independent chemistry review','base_commit':'f6b5ab0beb0b24a15cdde38f0b7e6c2dc4043540','source_file':'CHEMISTRY-JAMB-Past-Questions.pdf','source_pdf_sha256':'d70da60adbad7d2c2b972ea2e71d33d9f5f512869f416aa73cbc8594c205bc75','scope':'Normalized Chemistry records 161–200: twelve 1986 records and twenty-eight 1987 records. PDF pages 16–19 visually inspected. Stable IDs retained; source omissions outside these IDs not counted as reviewed.','counts':{'examined':40,'candidates':sum(r['publication_candidate'] for r in rows),'held':sum(not r['publication_candidate'] for r in rows)},'records':rows}
(OUT/'batch-005.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(b['counts'])
