const {test,expect}=require('@playwright/test');const fs=require('node:fs');
for(const [locale,route]of [['en','/tools/leave-calculator/'],['sw','/sw/zana/kikokotoo-likizo/'],['fr','/fr/tools/calculateur-conges-pto/']])test(`${locale}: CI eligibility controls, native TXT and real calendar boundaries`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(route);const decline=page.getByRole('button',{name:locale==='sw'?'Kataa uchanganuzi':locale==='fr'?'Refuser les analyses':'Decline analytics',exact:true});if(await decline.isVisible())await decline.click();
 if(locale!=='fr')await page.locator('#lc-tab-parental').click();const card=page.locator('#ci-birth-permission');await expect(card).toBeVisible();
 for(const [key,value]of [['birth','2026-09-18'],['start','2026-09-18'],['months','6'],['used','8']])await card.locator('[name='+key+']').fill(value);
 await card.locator('[name=family]').check();await card.locator('[name=confirmed]').check();await card.locator('[name=authorization]').selectOption('prior');await card.locator('[name=schedule]').selectOption('five');await card.locator('[name=exclusions]').fill('2026-09-21');await card.locator('button[type=submit]').focus();await page.keyboard.press('Enter');
 await expect(card.locator('[data-result]')).toContainText('2026-09-22');await expect(card.locator('[data-result]')).toContainText('2026-09-23');
 for(const format of ['txt','ics']){const pending=page.waitForEvent('download');await card.locator('[data-'+format+']').click();const body=fs.readFileSync(await(await pending).path(),'utf8').replace(/\r\n /g,'');expect(body).toContain('25.12');expect(body).toContain(locale==='fr'?'Autorisation préalable obtenue':locale==='sw'?'Idhini ya awali ilipatikana':'Prior authorization obtained');expect(body).toContain(locale==='fr'?'naissance':locale==='sw'?'kuzaliwa':'birth');if(format==='ics'){expect(body).toContain('DTSTART;VALUE=DATE:20260918');expect(body).toContain('DTEND;VALUE=DATE:20260923');expect(body).toContain('DTSTART;VALUE=DATE:20260923');expect(body.match(/BEGIN:VEVENT/g)).toHaveLength(2);}}
 await card.locator('[name=months]').fill('5');await expect(card.locator('[data-ics]')).toBeDisabled();await expect(card.locator('[data-txt]')).toBeDisabled();await card.locator('button[type=submit]').click();await expect(card.locator('[data-ics]')).toBeDisabled();await expect(card.locator('[data-result]')).not.toContainText('2026-09-22');
 await card.locator('[name=months]').fill('6');await card.locator('[name=used]').fill('9');await card.locator('button[type=submit]').click();await expect(card.locator('[data-ics]')).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});expect(await page.evaluate(async()=> (await axe.run(document.querySelector('#ci-birth-permission'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}})).violations.map(v=>v.id))).toEqual([]);
 const path=require('node:path').resolve(__dirname,'../../../leave-workflow-evidence/ci-birth-'+locale+'-mobile.png');fs.mkdirSync(require('node:path').dirname(path),{recursive:true});await card.screenshot({path});
});
