const{test,expect}=require('@playwright/test');test.use({trace:'off',screenshot:'off',video:'off'});
for(const[locale,route]of [['fr','/fr/tools/generateur-lettre-motivation/app.html'],['sw','/sw/zana/barua-ombi/']])test('native generated letter and protected user text: '+locale,async({page,baseURL},info)=>{
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:390,height:844});await page.goto(route);await page.waitForFunction(()=>document.querySelector('#letterText').value.length>0);await expect(page.locator('#letterText')).not.toHaveValue(/I am pleased|Dear Hiring/);await expect(page.locator('#templateId option[value=technology]')).toHaveText(locale==='fr'?'Technologie':'Teknolojia');let downloads=0;page.on('download',()=>downloads++);await page.locator('#tab-draft').click();await page.locator('#exportReviewConfirm').check();await page.locator('[data-action=pdf]').click();await expect(page.locator('#exportReviewStatus')).toContainText(locale==='fr'?'entre crochets':'kwenye mabano');expect(downloads).toBe(0);
 await page.evaluate(()=>{for(const[id,value]of Object.entries({fullName:'Language',jobTitle:'Skills',company:'Reference',hiringManager:'Élodie Mwang’ombe',achievement:'Projet Énergie — Ujuzi wa mawasiliano',skills:'Analyse et communication',whyCompany:'Engagement local',resumeSummary:'Parcours QZSUMMARY',contextNote:'Texte utilisateur QZCONTEXT',availability:'QZAVAILABLE',referral:'QZREFERRAL',source:'QZSOURCE',market:'Kenya',lengthId:'detailed'}))document.getElementById(id).value=value;});await page.locator('#tab-draft').click();
 for(const template of ['technology','finance','healthcare','education','engineering','ngo','government','sales','creative','graduate']){await page.evaluate(id=>document.querySelector('#templateId').value=id,template);await page.locator('#stage-draft [data-action=rebuild]:visible').first().click();const text=await page.locator('#letterText').inputValue();expect(text).toContain(locale==='fr'?'Cordialement,':'Wenu mwaminifu,');expect(text).toContain('QZSUMMARY');expect(text).toContain('QZCONTEXT');expect(text).toContain('Kenya');expect(text).not.toMatch(/I am pleased|Yours sincerely|Dear Hiring/);}
 await page.locator('[data-action=save]').click();await expect(page.locator('.saved-title').first()).toHaveText('Skills — Reference');
 const text=await page.locator('#letterText').inputValue();await page.locator('#exportReviewConfirm').check();const download=page.waitForEvent('download');await page.locator('[data-action=pdf]').click();const file=info.outputPath(locale+'-native-letter.pdf');await(await download).saveAs(file);const parsed=await require('pdf-parse')(new Uint8Array(require('fs').readFileSync(file)));expect(parsed.text.replace(/\s+/g,' ')).toContain(text.replace(/\s+/g,' '));await page.emulateMedia({media:'print'});const printed=await page.pdf({format:'A4',path:info.outputPath(locale+'-native-print.pdf')});const printText=await require('pdf-parse')(new Uint8Array(printed));expect(printText.text.replace(/\s+/g,' ').trim()).toBe(text.replace(/\s+/g,' ').trim());await page.emulateMedia({media:'screen'});
 await page.locator('#letterText').fill('Skills\n\nLanguage\n\nReference');await expect(page.locator('#paperPreview p')).toHaveText(['Skills','Language','Reference']);await page.waitForTimeout(400);await expect(page.locator('#paperPreview p')).toHaveText(['Skills','Language','Reference']);
 // The exclusion belongs only to explicit user content; sibling chrome still localizes.
 await page.evaluate(()=>{const p=document.createElement('p');p.id='localizer-regression';p.textContent='Language';document.querySelector('.app-shell').appendChild(p);});await expect(page.locator('#localizer-regression')).toHaveText(locale==='fr'?'Langue':'Lugha');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

for(const[locale,route]of [['fr','/fr/tools/generateur-recu/'],['sw','/sw/zana/kizalishaji-risiti/']])test('document localizer still translates ordinary receipt chrome: '+locale,async({page})=>{await page.goto(route);await page.evaluate(()=>{const section=document.createElement('section');section.innerHTML='<p id="ordinary-copy">Language</p><p id="protected-copy" data-cover-letter-user-content>Language</p>';document.body.appendChild(section);});await expect(page.locator('#ordinary-copy')).toHaveText(locale==='fr'?'Langue':'Lugha');await expect(page.locator('#protected-copy')).toHaveText('Language');});
