const{test,expect}=require('@playwright/test');const fs=require('fs');test.use({trace:'off',screenshot:'off',video:'off'});
for(const[locale,route]of [['en','/tools/cover-letter-generator/app.html'],['fr','/fr/tools/generateur-lettre-motivation/app.html'],['sw','/sw/zana/barua-ombi/']])test('long letter preserves content and native scoring: '+locale,async({page,baseURL},info)=>{
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:390,height:844});await page.goto(route);await page.waitForFunction(()=>document.querySelector('#templateId').options.length>2);
 const greeting={en:'Dear Hiring Manager,',fr:'Madame, Monsieur,',sw:'Ndugu waajiri,'}[locale],closing={en:'Yours sincerely,',fr:'Cordialement,',sw:'Wenu mwaminifu,'}[locale];const paragraphs=Array.from({length:36},(_,index)=>'QZPARA'+String(index).padStart(2,'0')+' '+('Élodie Mwang’ombe vérifie la réconciliation des données. Ujuzi wa mawasiliano na ushirikiano unaimarisha kazi ya timu. ').repeat(3)+'QZEND'+index);const token='QZLONG'+('é'.repeat(1400))+'QZLONGEND';const text=['Élodie Mwang’ombe',greeting,...paragraphs,token,closing,'QZFINALSIGNATURE'].join('\n\n');
 await page.evaluate(text=>{for(const[id,value]of Object.entries({fullName:'Élodie Mwang’ombe',email:'synthetic@example.test',jobTitle:'Analyst',company:'Example',skills:'réconciliation, communication',jobDescription:'réconciliation données data',achievement:'Réduction de 20 pour cent',whyCompany:'Une raison précise et suffisamment détaillée pour ce poste.',letterText:text})){const node=document.getElementById(id);node.value=value;node.dispatchEvent(new Event('input',{bubbles:true}));}},text);
 const structure={en:'Professional structure',fr:'Structure de la lettre',sw:'Muundo wa barua'}[locale];await expect(page.locator('#checksList .check').filter({hasText:structure})).toHaveClass(/good/);await expect(page.locator('#scoreCopy')).toContainText({en:'Word count:',fr:'Nombre de mots :',sw:'Idadi ya maneno:'}[locale]);await expect(page.locator('#keywordChips')).toContainText('réconciliation');await expect(page.locator('#keywordChips')).toContainText('données');await expect(page.locator('#scoreValue')).toHaveText('90');if(locale!=='en')await expect(page.locator('#checksList')).not.toContainText(/Contact details|Role and company|Proof with result|Company motivation|Job keywords|Letter length|Professional structure|No placeholders|Looks good|Aim for/);
 await page.locator('#tab-draft').click();await page.locator('#exportReviewConfirm').check();for(const format of ['pdf','word']){const download=page.waitForEvent('download');await page.locator('[data-action='+format+']').click();const file=info.outputPath(locale+'-long.'+(format==='word'?'doc':'pdf'));await(await download).saveAs(file);if(format==='pdf'){const pages=[];const result=await require('pdf-parse')(new Uint8Array(fs.readFileSync(file)),{pagerender:async pdfPage=>{const content=await pdfPage.getTextContent();const viewport=pdfPage.getViewport(1);pages.push({width:viewport.width,height:viewport.height,items:content.items.map(item=>({x:item.transform[4],y:item.transform[5],width:item.width,text:item.str}))});return content.items.map(item=>item.str).join('\n');}});expect(result.numpages).toBeGreaterThan(2);expect(result.text.replace(/\s/g,'')).toBe(text.normalize('NFC').replace(/\s/g,''));for(const page of pages){expect(page.items.some(item=>item.text.trim())).toBe(true);for(const item of page.items.filter(item=>item.text.trim())){expect(item.x).toBeGreaterThanOrEqual(50);expect(item.x+item.width).toBeLessThanOrEqual(page.width-48);expect(item.y).toBeGreaterThanOrEqual(50);expect(item.y).toBeLessThanOrEqual(page.height-40);}}fs.writeFileSync(info.outputPath(locale+'-bounds.json'),JSON.stringify(pages.map(page=>({width:page.width,height:page.height,lines:page.items.length}))));}else{const extracted=await page.evaluate(html=>{const doc=new DOMParser().parseFromString(html,'text/html');return Array.from(doc.body.querySelectorAll('p')).map(p=>{p.querySelectorAll('br').forEach(br=>br.replaceWith('\n'));return p.textContent;}).join('\n\n');},fs.readFileSync(file,'utf8'));expect(extracted).toBe(text);}}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
