const {test,expect}=require('@playwright/test');
test.use({trace:'off',screenshot:'off',video:'off'});
for(const [locale,route] of [['en','/tools/cover-letter-generator/app.html'],['fr','/fr/tools/generateur-lettre-motivation/app.html'],['sw','/sw/zana/barua-ombi/']])test('local cover-letter backup validation and restore: '+locale,async({page,baseURL},info)=>{
 const sent=[];page.on('request',request=>{if(request.postData())sent.push(request.postData());});await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:320,height:844});await page.goto(route);await page.waitForFunction(()=>document.querySelector('#templateId').options.length>2);
 const text='Élodie Mwang’ombe\n\nMadame, Monsieur,\nJe souhaite rejoindre Énergie Locale. Mon expérience en coordination et communication accompagne cette candidature. Ujuzi wa mawasiliano na ushirikiano.\n\nCordialement,\nÉlodie Mwang’ombe';
 await page.evaluate(text=>{for(const [id,value]of Object.entries({fullName:'Élodie Mwang’ombe',jobTitle:'Coordination',company:'Énergie Locale',letterText:text})){const input=document.getElementById(id);input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));}},text);await page.locator('[data-action=save]').click();
 await page.locator('#tab-draft').click();const before=await page.evaluate(()=>localStorage.getItem('afrotools-saved-cover-letter'));await page.locator('#exportReviewConfirm').check();const download=page.waitForEvent('download');await page.locator('[data-action=json]').click();const file=info.outputPath(locale+'.json');await(await download).saveAs(file);const backup=JSON.parse(require('fs').readFileSync(file,'utf8'));expect(backup.letterText).toBe(text);
 await page.locator('#letterText').fill('Existing synthetic draft');for(const invalid of ['{}','[]','null','{"fullName":{},"letterText":"x"}','{"fullName":"x","letterText":"x","__proto__":{"polluted":true}}','{"fullName":"x","letterText":"x","schemaVersion":999}']){await page.locator('#importInput').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(invalid)});await page.waitForTimeout(100);await expect(page.locator('#letterText')).toHaveValue('Existing synthetic draft');}
 await page.locator('#importInput').setInputFiles(file);await expect(page.locator('#letterText')).toHaveValue(text);for(const key of Object.keys(backup)){if(await page.locator('#'+key).count())await expect(page.locator('#'+key)).toHaveValue(backup[key]);}await page.locator('[data-action=save]').click();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('afrotools-saved-cover-letter')));expect(after.length).toBe(JSON.parse(before).length+1);

 await page.locator('#exportReviewConfirm').check();
 for(const format of ['txt','word','pdf']){const event=page.waitForEvent('download');await page.locator('[data-action='+format+']').click();const artifact=info.outputPath(locale+'-letter.'+({word:'doc'}[format]||format));await(await event).saveAs(artifact);const bytes=require('fs').readFileSync(artifact);if(format==='txt')expect(bytes.toString('utf8')).toBe(text);else if(format==='word'){const extracted=await page.evaluate(html=>{const doc=new DOMParser().parseFromString(html,'text/html');return Array.from(doc.body.querySelectorAll('p')).map(p=>p.innerHTML.replace(/<br\s*\/?[^>]*>/gi,'\n')).join('\n\n');},bytes.toString('utf8'));expect(extracted).toContain('Élodie Mwang’ombe');expect(extracted).toContain('Ujuzi wa mawasiliano na ushirikiano.');}else{const parsed=await require('pdf-parse')(new Uint8Array(bytes));expect(parsed.text).toContain('Élodie Mwang’ombe');expect(parsed.text.replace(/\s+/g,' ')).toContain(text.replace(/\s+/g,' '));}}
 await page.evaluate(()=>{window.__copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.__copied=value;}}});window.__printed=0;window.print=()=>window.__printed++;});await page.locator('[data-action=copy]').click();expect(await page.evaluate(()=>window.__copied)).toBe(text);await page.locator('[data-action=print]').click();expect(await page.evaluate(()=>window.__printed)).toBe(1);await page.emulateMedia({media:'print'});const print=await page.pdf({path:info.outputPath(locale+'-print.pdf'),format:'A4'});const parsedPrint=await require('pdf-parse')(new Uint8Array(print));expect(parsedPrint.text.replace(/\s+/g,' ')).toContain(text.replace(/\s+/g,' '));await page.emulateMedia({media:'screen'});
 const blank={...backup,letterText:''};await page.locator('#importInput').setInputFiles({name:'blank.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(blank))});await expect(page.locator('#letterText')).toHaveValue('');await page.reload();await expect(page.locator('#letterText')).toHaveValue('');expect(await page.evaluate(()=>({}.polluted))).toBeUndefined();expect(sent.every(body=>!body.includes('Mwang')&&!body.includes('Ujuzi'))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
