const {test,expect}=require('@playwright/test'),fs=require('fs'),pdf=require('pdf-parse');test.use({timezoneId:'UTC'});
for(const[locale,route,header,failure]of[['en','/crypto/remittance/','Sending country','Could not copy'],['fr','/fr/crypto/remittance/','Pays d’envoi','Impossible de copier'],['sw','/sw/zana/ulinganisho-nukuu-za-kutuma-fedha/','Nchi ya kutuma','Imeshindikana kunakili']])test(`${locale} native private exports refresh expiry and reset`,async({page})=>{
 const sends=[];page.on('request',r=>sends.push(r.url()+' '+(r.postData()||'')));await page.clock.install({time:new Date('2026-09-16T12:00:00Z')});await page.goto(route);
 for(const letter of ['a','b'])for(const[key,value]of Object.entries({label:'PRIVATE_SYNTHETIC_'+letter,sendCountry:'GB',receiveCountry:letter==='a'?'SN':'Sénégal',send:'USD',debit:'100',receive:'XOF',recipient:letter==='a'?'58000':'59000',observed:'2026-09-16T11:00',expires:letter==='b'?'2026-09-16T12:01':''}))await page.locator(`#rm-${letter}-${key}`).fill(value);
 await page.locator('#rm-form button[type=submit]').click();await expect(page.locator('.rm-result[data-highest=true]')).toHaveCount(1);
 let event=page.waitForEvent('download');await page.locator('#rm-csv').click();const csv=fs.readFileSync(await(await event).path(),'utf8');expect(csv).toContain(header);expect(csv).toContain('Sénégal');expect(csv).toContain('59000');expect(csv).toContain('PRIVATE_SYNTHETIC_b');
 event=page.waitForEvent('download');await page.locator('#rm-pdf').click();const parsed=await pdf(fs.readFileSync(await(await event).path()));expect(parsed.text).toContain('PRIVATE_SYNTHETIC_b');expect(parsed.text).toContain('XOF');
 await page.clock.setFixedTime(new Date('2026-09-16T12:01:00Z'));event=page.waitForEvent('download');await page.locator('#rm-json').click();const json=JSON.parse(fs.readFileSync(await(await event).path(),'utf8'));expect(json.requireCorridor).toBe(true);expect(json.quotes[1].expiryState).toBe('expired');expect(json.hasEligibleComparison).toBe(false);expect(json.quotes[1].receiveCountry).toBe('Sénégal');expect(await page.evaluate(input=>window.RemittanceQuoteComparatorEngine.calculate(input),json)).toEqual(json);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedQuote=text;}}}));await page.locator('#rm-copy').click();expect(await page.evaluate(()=>window.copiedQuote)).toContain('Sénégal');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('denied'))}}));await page.locator('#rm-copy').click();await expect(page.locator('#rm-status')).toContainText(failure);await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined}));await page.locator('#rm-copy').click();await expect(page.locator('#rm-status')).toContainText(failure);
 await page.locator('#rm-b-receiveCountry').fill('Unknown synthetic');await page.locator('#rm-form button[type=submit]').click();await expect(page.locator('#rm-b-receiveCountry')).toBeFocused();await expect(page.locator('.rm-result')).toHaveCount(0);
 await page.locator('#rm-third').check();await page.locator('#rm-form button[type=reset]').click();await expect(page.locator('#rm-third')).not.toBeChecked();await expect(page.locator('#rm-c-label')).toBeDisabled();await expect(page.locator('#rm-quote-c')).toBeHidden();await expect(page.locator('#rm-error')).toBeEmpty();expect(sends.join('\n')).not.toContain('PRIVATE_SYNTHETIC');
});
