const{test,expect}=require('@playwright/test'),fs=require('fs'),pdf=require('pdf-parse');
const fixture=require('../fixtures/cv-complete-form'),{inspectRasterPdf}=require('../support/cv-raster-pdf-bounds');
test.use({trace:'off',screenshot:'off',video:'off'});
for(const[lang,route]of [['en','/tools/cv-builder/'],['fr','/fr/tools/generateur-cv/'],['sw','/sw/zana/mjenzi-cv/']])test('unbroken local content wraps in styled PDF and print: '+lang,async({page,baseURL},info)=>{
 await page.context().route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:320,height:844});await page.goto(route);await page.waitForFunction(()=>window.CVExportPdfQuality);await page.waitForTimeout(1100);
 await page.evaluate(async f=>{Object.assign(CVApp.getState().data,f,{summary:'LONGSUMMARY'+'z'.repeat(700)+'ENDSUMMARY',web:'https://example.test/'+'w'.repeat(350)+'ENDURL'});CVApp.getState().data.exps[0].e='LONGDATE'+'d'.repeat(300)+'ENDDATE';CVExportUpgrade.setOptions({density:'comfortable',breakEdu:false});await loadPdfLibs();const original=html2canvas;window.captureEvidence=[];window.html2canvas=async function(node,opts){captureEvidence.push({width:node.scrollWidth,text:node.innerText,overflow:[...node.querySelectorAll('*')].filter(n=>n.clientWidth>0&&n.scrollWidth>n.clientWidth+3).map(n=>n.tagName)});return original(node,opts);};},fixture);
 for(const template of ['lagos-corporate','cape-town-modern']){
 await page.evaluate(id=>{CVApp.getState().template=id;CVApp.renderAll();},template);const pending=page.waitForEvent('download');await page.evaluate(()=>CVExportUpgrade.exportPdf());const file=info.outputPath(lang+'-'+template+'.pdf');await(await pending).saveAs(file);expect((await inspectRasterPdf(fs.readFileSync(file))).every(b=>b.insidePaper)).toBe(true);
 }
 const captures=await page.evaluate(()=>captureEvidence);for(const c of captures){expect(c.width).toBe(595);expect(c.overflow).toEqual([]);for(const marker of ['ENDSUMMARY','ENDURL','ENDDATE','QZRelationshipX'])expect(c.text).toContain(marker);}
 // Chromium document.write print windows fail CSS loading while request interception is enabled.\n await page.context().unrouteAll({behavior:'wait'});const popupEvent=page.waitForEvent('popup');await page.evaluate(()=>CVExportUpgrade.printCv());const popup=await popupEvent;await popup.waitForLoadState();await popup.waitForFunction(()=>{const date=document.querySelector(".cvx-row>span");return date&&getComputedStyle(date).maxWidth==="55%";});await popup.evaluate(()=>document.fonts.ready);const printFile=info.outputPath(lang+'-print.pdf');await popup.pdf({path:printFile,printBackground:true,preferCSSPageSize:true});const parsed=await pdf(new Uint8Array(fs.readFileSync(printFile)));const normalized=parsed.text.replace(/\s+/g,'');for(const token of ['LONGSUMMARY'+'z'.repeat(700)+'ENDSUMMARY','https://example.test/'+'w'.repeat(350)+'ENDURL','LONGDATE'+'d'.repeat(300)+'ENDDATE','QZRelationshipX'])expect(normalized).toContain(token);await popup.close();
});

