const{test,expect}=require('@playwright/test'),fs=require('fs');
test.use({trace:'off',screenshot:'off',video:'off'});
for(const route of ['/tools/cv-builder/','/fr/tools/generateur-cv/','/sw/zana/mjenzi-cv/'])test('actual PDF photo follows visibility and template policy: '+route,async({page,baseURL},info)=>{
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:320,height:844});await page.goto(route);await page.waitForFunction(()=>window.CVExportPdfQuality);await page.addScriptTag({url:'/assets/vendor/pdf-lib/pdf-lib.min.js'});
 for(const [template,visible,expected]of [['lagos-corporate',true,true],['lagos-corporate',false,false],['pan-african-minimal',true,false]]){
 await page.evaluate(({template,visible})=>{const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.fillStyle='#ed2020';x.fillRect(0,0,32,32);Object.assign(CVApp.getState().data,{fn:'Synthetic',ln:'Photo',summary:'Photo policy fixture',showPhoto:visible,photo:c.toDataURL('image/png')});CVApp.getState().template=template;CVApp.renderAll();},{template,visible});const pending=page.waitForEvent('download');await page.evaluate(()=>CVExportUpgrade.exportPdf());const file=info.outputPath(template+'-'+visible+'.pdf');await(await pending).saveAs(file);
 const red=await page.evaluate(async bytes=>{const doc=await PDFLib.PDFDocument.load(new Uint8Array(bytes));let red=0;for(const[,obj]of doc.context.enumerateIndirectObjects()){if(!(obj instanceof PDFLib.PDFRawStream)||String(obj.dict.get(PDFLib.PDFName.of('Filter')))!=='/DCTDecode')continue;const blob=new Blob([obj.contents],{type:'image/jpeg'}),url=URL.createObjectURL(blob),im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);const data=x.getImageData(0,0,c.width,c.height).data;for(let i=0;i<data.length;i+=4)if(data[i]>160&&data[i+1]<85&&data[i+2]<85)red++;URL.revokeObjectURL(url);}return red;},Array.from(fs.readFileSync(file)));expect(red>100,template+' '+visible+' actual JPEG red pixels '+red).toBe(expected);
 }
});
