const{test,expect}=require('@playwright/test'),fs=require('fs'),pdf=require('pdf-parse'),crypto=require('crypto');
const fixture=require('../fixtures/cv-complete-form'),PDFLib=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');
const families=['pan-african-minimal','lagos-corporate','nairobi-tech','accra-graduate','creative-portfolio','ats-plain','cape-town-modern','kigali-developer','ngo-impact','scholarship-academic'];
test.use({trace:'off',screenshot:'off',video:'off'});
for(const[lang,route,heading]of [['en','/tools/cv-builder/','EDUCATION'],['fr','/fr/tools/generateur-cv/','FORMATION'],['sw','/sw/zana/mjenzi-cv/','ELIMU']])test('actual print preserves short content across ten layout families: '+lang,async({page,baseURL},info)=>{
 test.setTimeout(120000);await page.context().route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.fulfill({status:204}));await page.setViewportSize({width:320,height:844});await page.goto(route);await page.waitForFunction(()=>window.CVExportPdfQuality);await page.waitForTimeout(1100);
 await page.evaluate(f=>{Object.assign(CVApp.getState().data,f);CVExportUpgrade.setOptions({density:'comfortable',avoidSplits:true,breakExp:false,breakEdu:false,breakProjects:false,breakRefs:false});},fixture);
 // Request interception prevents Chromium document.write windows loading their CSS.
 await page.context().unrouteAll({behavior:'wait'});const evidence=[];
 for(const template of families){await page.evaluate(async id=>{CVApp.getState().template=id;CVApp.renderAll();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));},template);await page.waitForFunction(()=>document.querySelector("#cvpreview").textContent.includes("QZCustomContentX"));const pending=page.waitForEvent('popup');await page.evaluate(()=>CVExportUpgrade.printCv());const popup=await pending;await popup.waitForFunction(()=>document.querySelector('#cvpreview')&&[...document.querySelectorAll('link[rel="stylesheet"]')].every(n=>n.sheet));await popup.evaluate(()=>document.fonts.ready);
 const headingPx=await popup.evaluate(()=>parseFloat(getComputedStyle(document.querySelector("#cvpreview h1")).fontSize));const file=info.outputPath(lang+'-'+template+'-print.pdf');await popup.pdf({path:file,printBackground:true,preferCSSPageSize:true});const bytes=fs.readFileSync(file);const overflow=[],pageTexts=[];let printedNameHeight;const parsed=await pdf(new Uint8Array(bytes),{pagerender:async pg=>{const content=await pg.getTextContent();const viewport=pg.getViewport(1);for(const item of content.items){if(pg.pageNumber===1&&item.str.includes("Élodie"))printedNameHeight=Math.max(printedNameHeight||0,Math.hypot(item.transform[2],item.transform[3]));const[x,y]=item.transform.slice(4);if(item.str.trim()&&(x<-.5||x+item.width>viewport.width+.5||y<-.5||y+item.height>viewport.height+.5))overflow.push({page:pg.pageNumber,x,y,width:item.width,height:item.height});}const pageText=content.items.map(i=>i.str).join('\n');pageTexts.push(pageText);return pageText;}});expect(pageTexts.every(text=>text.trim().length>0),template+' has no blank print page').toBe(true);expect(pageTexts[0].replace(/\s+/g,''),template+' first page uses available space').toContain('QZRoleX');expect(printedNameHeight,template+" physical heading scale").toBeCloseTo(headingPx*194/595*72/25.4,1);const text=parsed.text.replace(/\s+/g,'');for(const marker of ['ÉlodieFrançoisŁukasz','QZCustomContentX','QZAltX','QZWebX','QZGitX','QZPortfolioX','QZEduDetailX','QZGradeX','QZProjectURLX','QZCertX','QZLanguageX','QZRelationshipX','QZHobbyX','QZMemberX','QZSkill29X'])expect(text,template+' '+marker).toContain(marker);expect(parsed.text.toUpperCase()).toContain(heading);expect(overflow,template+' print text bounds').toEqual([]);const doc=await PDFLib.PDFDocument.load(bytes);for(const p of doc.getPages()){expect(p.getWidth()).toBeCloseTo(595.28,0);expect(p.getHeight()).toBeCloseTo(841.89,0);}evidence.push({lang,template,file,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),pages:parsed.numpages,textBounds:'inside A4'});await popup.close();}
 fs.writeFileSync(info.outputPath(lang+'-print-manifest.json'),JSON.stringify(evidence,null,2));
});
