const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
const records=require('../../data/energy/electricity-tariffs.json').records;
const routes={en:'/tools/electricity-tariff/',fr:'/fr/tools/tarifs-electricite/',sw:'/sw/zana/kikokotoo-tariff-ya-umeme/'};
const expected={
 fr:[['Résidentiel standard','Tarif résidentiel moyen.','Coût de l’énergie résidentielle'],['Résidentiel au tarif social','la moyenne glissante sur six mois ne doit pas dépasser 100 kWh','Tarif social — 15 premiers kWh','Tarif résidentiel standard au-delà de 15 kWh'],['Professionnels basse tension','La tarification selon les périodes de pointe, intermédiaires et creuses','Coût moyen de l’énergie pour les professionnels'],['D1 résidentiel à faible consommation','inférieure à 75 kWh par mois','75 premiers kWh','Consommation au-delà de 75 kWh'],['T1 usage général basse tension','logements, petits commerces, industrie légère, éclairage public et panneaux publicitaires','Coût de l’énergie pour usage général']],
 sw:[['Nyumbani kawaida','Jumla ya risiti inaweza kutofautiana','Gharama ya nishati ya nyumbani'],['Nyumbani wanaostahiki tarifa nafuu','wastani unaosogea wa miezi sita usizidi 100 kWh','Tarifa nafuu — kWh 15 za kwanza','Tarifa ya kawaida ya nyumbani baada ya kWh 15'],['Biashara ya volteji ya chini','vipindi vya matumizi ya juu, ya kati na ya chini','Wastani wa gharama ya nishati ya biashara'],['D1 matumizi madogo ya nyumbani','wastani wa matumizi chini ya kWh 75 kwa mwezi','kWh 75 za kwanza','Matumizi zaidi ya kWh 75'],['T1 matumizi ya jumla ya volteji ya chini','makazi, biashara ndogo, viwanda vyepesi, taa za maeneo ya umma na mabango','Gharama ya nishati kwa matumizi ya jumla']]
};
for(const [locale,route]of Object.entries(routes))test(`${locale} all five tariff records retain numbers and display native names, notes and tiers`,async({page},info)=>{
 test.setTimeout(90000);await page.addInitScript(()=>{window.__AFROTOOLS_ELECTRICITY_AS_OF__='2026-08-20';});await page.setViewportSize({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(route);await page.waitForFunction(()=>window.AFROTOOLS_ELECTRICITY_READY===true);await page.locator('input[name="electricityMode"][value="units_to_bill"]').check();const evidence=[];
 for(let i=0;i<records.length;i++) {const record=records[i];await page.locator('#electricityCountry').selectOption(record.country_code);await page.locator('#electricityTariff').selectOption(record.tariff_id);await page.locator('#electricityAmount').fill('100');await page.locator('.electricity-button').click();await expect(page.locator('#electricityPrimary')).toContainText(['77,940','69,999','56,210','16,250','29,200'][i]);await expect(page.locator('#electricityTariff')).toHaveValue(record.tariff_id);await expect(page.locator('#electricitySource')).toHaveAttribute('href',record.source_url);await expect(page.locator('#electricityFreshness')).toContainText(record.last_verified_at);
  if(locale==='en'){await expect(page.locator('#electricityAssumptions')).toContainText(record.notes);for(const tier of record.tiers)await expect(page.locator('#electricityBreakdown')).toContainText(tier.label);}else{const [name,note,...tiers]=expected[locale][i];await expect(page.locator('#electricityTariff option:checked')).toContainText(name);await expect(page.locator('#electricitySourceTitle')).toContainText(name);await expect(page.locator('#electricityAssumptions')).toContainText(note);await expect(page.locator('#electricityAssumptions')).not.toContainText(record.notes);for(const tier of tiers)await expect(page.locator('#electricityBreakdown')).toContainText(tier);for(const tier of record.tiers)await expect(page.locator('#electricityBreakdown')).not.toContainText(tier.label);}
  evidence.push({id:record.tariff_id,name:await page.locator('#electricityTariff option:checked').textContent(),notes:await page.locator('#electricityAssumptions').textContent(),tiers:await page.locator('#electricityBreakdown').textContent(),result:await page.locator('#electricityPrimary').textContent()});
 }
 expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);fs.writeFileSync(info.outputPath('tariff-notes.json'),JSON.stringify(evidence,null,2));
});
