const {test,expect}=require('@playwright/test');
const fs=require('fs');
const pdfParse=require('pdf-parse');
const routes=['/tools/architectural-fee/','/fr/tools/honoraires-architecte/'];
async function prepare(page){await page.locator('[name="country"]').selectOption('KE');await page.locator('[name="projectType"]').selectOption('commercial_medium');await page.locator('[name="constructionValue"]').fill('10000000');await page.locator('[name="minRate"]').fill('5');await page.locator('[name="typicalRate"]').fill('7');await page.locator('[name="maxRate"]').fill('9');await page.locator('[name="scope"]').selectOption('concept');await page.locator('[name="scopeShare"]').fill('50');await page.locator('[name="practice"]').selectOption('small_firm');await page.locator('[name="practiceAdjustment"]').fill('10');await page.locator('[name="disbursements"]').fill('100000');await page.locator('[name="taxPct"]').fill('10');await page.locator('[name="scopeNotes"]').fill('Concept options and two revisions');await page.locator('[name="exclusions"]').fill('Approval fees and engineering');await page.locator('[name="assumptionsConfirmed"]').check();await page.locator('[name="localVerificationConfirmed"]').check();}

for(const route of routes)test(`${route} calculates and reopens every advertised output`,async({page,baseURL})=>{
  const errors=[],external=[];let privacyArmed=false;await page.addInitScript(()=>localStorage.setItem('afrotools_cookie_consent','declined'));await page.route(/^https?:\/\//,r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.abort());page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{const url=request.url();if(privacyArmed&&(request.method()!=='GET'||request.postData()))external.push(request.method()+' '+new URL(url).pathname);});
  const calculate=page.locator('[data-architectural-fee-workspace] button[type="submit"]');await page.goto(route);await expect(page.locator('[data-architectural-fee-workspace]')).toHaveAttribute('data-workflow-ready','true');privacyArmed=true;await calculate.click();await expect(page.locator('[data-status]')).toContainText(route.includes('/fr/')?'Vérifiez':'Review');await prepare(page);await expect(page.locator('[name="currency"]')).toHaveValue('KES');await page.locator('[data-action="save"]').click();await page.locator('[name="typicalRate"]').fill('8');await page.locator('[data-action="load"]').click();await expect(page.locator('[name="typicalRate"]')).toHaveValue('7');await calculate.click();await expect(page.locator('[data-results]')).toBeVisible();await expect(page.locator('[data-typical]')).toContainText('KES 533,500');await expect(page.locator('[data-stage-body] tr')).toHaveCount(7);await expect(page.locator('[data-basis]')).toContainText(route.includes('/fr/')?'faible confiance':'low confidence');
  await page.evaluate(()=>{window.__copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copied=text;}}});});await page.locator('[data-action="copy"]').click();expect(await page.evaluate(()=>window.__copied)).toContain('KES 533,500');if(route.includes('/fr/'))await expect(page.locator('[data-status]')).toContainText('Résumé copié');
  const jsonEvent=page.waitForEvent('download');await page.locator('[data-action="json"]').click();const jsonPath=await(await jsonEvent).path();const record=JSON.parse(fs.readFileSync(jsonPath,'utf8'));expect(record.englishId).toBe('architectural-fee');expect(record.result.range.typical.total).toBeCloseTo(533500,4);expect(record.inputs.scopeNotes).toBe('Concept options and two revisions');
  const csvEvent=page.waitForEvent('download');await page.locator('[data-action="csv"]').click();const csv=fs.readFileSync(await(await csvEvent).path(),'utf8').replace(/^\uFEFF/,'');const rows=csv.trim().split(/\r?\n/);expect(rows[0]).toBe('"field","value"');expect(rows.some(row=>row.startsWith('"typical_total","533500'))).toBeTruthy();expect(rows.some(row=>row.startsWith('"stage_concept_amount"'))).toBeTruthy();
  const txtEvent=page.waitForEvent('download');await page.locator('[data-action="txt"]').click();const txt=fs.readFileSync(await(await txtEvent).path(),'utf8');expect(txt).toContain(route.includes('/fr/')?'Estimation des honoraires d’architecte':'Architectural fee planning estimate');expect(txt).toContain('Approval fees and engineering');
  const pdfEvent=page.waitForEvent('download');await page.locator('[data-action="pdf"]').click();const pdfBuffer=fs.readFileSync(await(await pdfEvent).path());expect(pdfBuffer.subarray(0,5).toString()).toBe('%PDF-');const parsed=await pdfParse(pdfBuffer);expect(parsed.text).toContain(route.includes('/fr/')?'Estimation des honoraires d’architecte':'Architectural fee planning estimate');expect(parsed.text).toContain('Concept options and two revisions');
  if(route.includes('/fr/')){expect(txt).toContain('Immeuble de bureaux');expect(txt).toContain('Esquisse et conception');expect(txt).not.toMatch(/Inception|Working drawings|Country:|Project type:/);await expect(page.locator('[data-stage-body]')).not.toContainText(/Inception|Concept design|working drawings/);}await page.locator('[data-action="reset"]').click();await page.locator('[data-action="import"]').click();await page.locator('[name="importFile"]').setInputFiles(jsonPath);await expect(page.locator('[data-results]')).toBeVisible();await expect(page.locator('[name="scopeNotes"]')).toHaveValue('Concept options and two revisions');await expect(page.locator('[data-typical]')).toContainText('KES 533,500');expect(external).toEqual([]);expect(errors).toEqual([]);
});

test('invalid range and stage allocations fail closed and reset works',async({page})=>{await page.goto('/fr/tools/honoraires-architecte/');const calculate=page.locator('[data-architectural-fee-workspace] button[type="submit"]');await prepare(page);await calculate.click();await expect(page.locator('[data-results]')).toBeVisible();await page.locator('[name="minRate"]').fill('10');await expect(page.locator('[data-results]')).toBeHidden();await expect(page.locator('[data-result-actions]')).toBeHidden();await calculate.click();await expect(page.locator('[data-status]')).toContainText('minimum');await expect(page.locator('[data-results]')).toBeHidden();await page.locator('[name="minRate"]').fill('5');await page.locator('[name="phase-inception"]').fill('6');await calculate.click();await expect(page.locator('[data-status]')).toContainText('100 %');await page.locator('[data-action="reset"]').click();await expect(page.locator('[name="constructionValue"]')).toHaveValue('');await expect(page.locator('[name="phase-inception"]')).toHaveValue('5');});

for(const width of [320,375])test(`French architectural fee reflows at ${width}px, 200% text and both themes`,async({page})=>{await page.setViewportSize({width,height:900});for(const scheme of ['light','dark']){await page.emulateMedia({colorScheme:scheme,reducedMotion:'reduce'});await page.goto('/fr/tools/honoraires-architecte/');await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});const size=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.viewport+2);const unnamed=await page.locator('[data-architectural-fee-workspace] input,[data-architectural-fee-workspace] select,[data-architectural-fee-workspace] textarea,[data-architectural-fee-workspace] button').evaluateAll(nodes=>nodes.filter(node=>!node.labels?.length&&!node.getAttribute('aria-label')&&!node.textContent.trim()).length);expect(unnamed).toBe(0);await page.locator('[name="country"]').focus();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement!==document.body)).toBeTruthy();}});
