const{test,expect}=require('@playwright/test');const fs=require('node:fs');test.use({timezoneId:'UTC'});
for(const[code,country,currency]of [['CM','Cameroun','XAF'],['SN','Sénégal','XOF'],['ML','Mali','XOF'],['CI','Côte d’Ivoire','XOF']])test(`Orange guide ${code} retains context through native comparison and reset`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.clock.setFixedTime(new Date('2026-09-16T12:00:00Z'));const requests=[];page.on('request',r=>requests.push(r.url()+' '+(r.postData()||'')));await page.goto('/fr/blog/frais-orange-money-guide-2026/');await page.locator('[data-orange-quote-context="'+code+'"]').click();await expect(page).toHaveURL(new RegExp('market='+code+'&operation=withdraw#mm-form$'));
 await expect(page.locator('#mm-status')).toContainText('aucun tarif Orange Money');await expect(page.locator('#mm-provider option')).toHaveCount(2);await expect(page.locator('#mm-provider')).not.toContainText('Orange');
 for(const l of ['a','b','c']){await expect(page.locator('#mm-'+l+'-market')).toHaveValue(country);await expect(page.locator('#mm-'+l+'-currency')).toHaveValue(currency);await expect(page.locator('#mm-'+l+'-type')).toHaveValue('withdraw');for(const field of ['amount','sender','recipient','observed','expires'])await expect(page.locator('#mm-'+l+'-'+field)).toHaveValue('');}
 await page.locator('#mm-third').check();for(const[l,fee]of [['a','100'],['b','75'],['c','50']])for(const[k,v]of Object.entries({label:'SYNTHETIC-ORANGE-PRIVATE-'+l,amount:'10000',sender:'0',recipient:fee,observed:'2026-09-16T11:00'}))await page.locator('#mm-'+l+'-'+k).fill(v);
 await page.locator('#mm-form button[type=submit]').click();await expect(page.locator('#mm-primary-value')).toHaveText('50 '+currency);await expect(page.locator('#mm-result-list .rm-result')).toHaveCount(3);const pending=page.waitForEvent('download');await page.locator('#mm-json').click();const json=JSON.parse(fs.readFileSync(await(await pending).path(),'utf8'));expect(json.locale).toBe('fr');expect(json.result.quotes.map(q=>q.market)).toEqual([country,country,country]);expect(json.result.quotes.map(q=>q.transactionType)).toEqual(['withdraw','withdraw','withdraw']);expect(json.resume).toContain('Frais de réception ou de retrait');
 await page.locator('#mm-form button[type=reset]').click();await expect(page.locator('#mm-a-market')).toHaveValue('');await expect(page.locator('#mm-a-currency')).toHaveValue('');await expect(page.locator('#mm-quote-c')).toBeHidden();await expect(page.locator('#mm-result-list')).toBeEmpty();expect(requests.join('\n')).not.toContain('SYNTHETIC-ORANGE-PRIVATE');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('invalid or unsupported handoff cannot supply fees or change tariff provider',async({page})=>{
 for(const query of ['market=XX&operation=withdraw','market=CM&operation=unknown','market=CM&operation=withdraw&amount=1000000&sender=0&currency=USD']){await page.goto('/fr/tools/frais-mobile-money/?'+query+'#mm-form');await expect(page.locator('#mm-form')).toHaveAttribute('data-readiness','ready');await expect(page.locator('#mm-a-amount')).toHaveValue('');await expect(page.locator('#mm-a-sender')).toHaveValue('');if(query.includes('currency=USD')){await expect(page.locator('#mm-a-currency')).toHaveValue('XAF');}else{await expect(page.locator('#mm-a-market')).toHaveValue('');await expect(page.locator('#mm-a-currency')).toHaveValue('');}await expect(page.locator('#mm-provider')).toHaveValue('mtn-uganda');}
});
for(const theme of ['light','dark'])test(`French comparison is accessible at 320px in ${theme} mode`,async({page})=>{
 await page.setViewportSize({width:320,height:844});await page.goto('/fr/tools/frais-mobile-money/?market=CM&operation=withdraw#mm-form');await expect(page.locator('#mm-form')).toHaveAttribute('data-readiness','ready');if(theme==='dark'){await page.getByRole('button',{name:'Ouvrir le menu',exact:true}).click();await page.locator('#mobThemeToggle').click();await page.keyboard.press('Escape');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');}
 for(const l of ['a','b'])for(const[k,v]of Object.entries({label:'Synthetic '+l,amount:'100',sender:'1',recipient:'2',observed:'2020-01-01T12:00'}))await page.locator('#mm-'+l+'-'+k).fill(v);await page.locator('#mm-form button[type=submit]').click();await expect(page.locator('#mm-result-list .rm-result')).toHaveCount(2);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const r=await axe.run(document.querySelector('main'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}});return r.violations.filter(x=>['serious','critical'].includes(x.impact)).map(x=>({id:x.id,nodes:x.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});expect(violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
