const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function setup(page){await page.setViewportSize({width:390,height:844});await page.addInitScript(()=>{navigator.clipboard.writeText=async text=>{window.copied=text;};});}
async function downloaded(page){const pending=page.waitForEvent('download');await page.locator('#downloadBtn').click();return fs.readFile(await(await pending).path(),'utf8');}
test('French HTML numeric and hex encode sensitive ASCII and supplementary Unicode',async({page})=>{await setup(page);await page.goto('/fr/tools/entites-html/');await page.locator('#inputText').fill('<é😀&');await page.locator('#entityStyle').selectOption('numeric');await expect(page.locator('#outputText')).toHaveValue('&#60;&#233;&#128512;&#38;');await page.locator('#entityStyle').selectOption('hex');await expect(page.locator('#outputText')).toHaveValue('&#x3C;&#xE9;&#x1F600;&#x26;');expect(await downloaded(page)).toBe('&#x3C;&#xE9;&#x1F600;&#x26;');await page.locator('#swapBtn').click();await expect(page.locator('#outputText')).toHaveValue('<é😀&');await page.locator('#inputText').fill('&Eacute; &eacute; &#0; &#x110000; &unknown; <img src=x onerror=alert(1)>');await expect(page.locator('#outputText')).toHaveValue('É é � � &unknown; <img src=x onerror=alert(1)>');await page.locator('#copyBtn').click();expect(await page.evaluate(()=>window.copied)).toContain('É é � �');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);});
test('French URL modes roundtrip Unicode and retain malformed input safely',async({page})=>{await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/fr/tools/encodeur-url/');await page.locator('#urlInput').fill("café 😀 !'()* +");await page.locator('#encodeRfcBtn').click();await expect(page.locator('#urlOutput')).toHaveText('caf%C3%A9%20%F0%9F%98%80%20%21%27%28%29%2A%20%2B');expect(await downloaded(page)).toContain('caf%C3%A9');await page.locator('#encodeFormBtn').click();await expect(page.locator('#urlOutput')).toHaveText("caf%C3%A9+%F0%9F%98%80+!'()*+%2B");await page.locator('#urlInput').fill('caf%C3%A9+%F0%9F%98%80');await page.locator('#decodeBtn').click();await expect(page.locator('#urlOutput')).toHaveText('café 😀');for(const value of ['%','%GG','%E0%A4']){await page.locator('#urlInput').fill(value);await expect(page.locator('#urlOutput')).toHaveText(value);}await page.locator('#urlInput').evaluate(el=>{el.value='\ud800';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#encodeComponentBtn').click();await expect(page.locator('#warningList')).toContainText('Unicode');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);});
test('English HTML UI agrees with the independently expected numeric output',async({page})=>{await page.goto('/tools/html-entities/');await page.locator('#input').fill('<é😀&');await page.locator('#encodeStyle').selectOption('decimal');await expect(page.locator('#output')).toHaveValue('&#60;&#233;&#128512;&#38;');});
test('English URL component outputs match French RFC and form expectations',async({page})=>{await page.goto('/tools/url-encoder/');await page.locator('#componentInput').fill("café 😀 !'()* +");await expect(page.locator('#rfcOut')).toHaveText('caf%C3%A9%20%F0%9F%98%80%20%21%27%28%29%2A%20%2B');await expect(page.locator('#formOut')).toHaveText("caf%C3%A9+%F0%9F%98%80+!'()*+%2B");});

for(const tool of ['html','url'])test(`${tool} codec keeps synthetic input out of every network payload`,async({page})=>{
  await setup(page);
  const marker='CodecPrivateFixture739251',fixture=marker+' café 😀 <&+>',requests=[];
  page.on('request',request=>requests.push({url:request.url(),body:request.postData()||''}));
  await page.goto(tool==='html'?'/fr/tools/entites-html/':'/fr/tools/encodeur-url/');
  await page.locator(tool==='html'?'#inputText':'#urlInput').fill(fixture);
  if(tool==='html')await page.locator('#entityStyle').selectOption('hex');
  else await page.locator('#encodeFormBtn').click();
  await page.locator('#copyBtn').click();
  await downloaded(page);
  await page.waitForTimeout(1200); // Observe asynchronous telemetry after conversion/export.
  const variants=[marker,encodeURIComponent(fixture),encodeURIComponent(encodeURIComponent(fixture)),Buffer.from(fixture).toString('base64'),Array.from(marker).map(c=>'&#'+c.codePointAt(0)+';').join(''),Array.from(marker).map(c=>'&#x'+c.codePointAt(0).toString(16)+';').join('')];
  for(const request of requests){const payload=request.url+' '+request.body;for(const value of variants)expect(payload.toLowerCase(),'Synthetic codec input leaked in request').not.toContain(value.toLowerCase());}
});
