const {test,expect}=require('@playwright/test');const fs=require('fs');
test('French leave adds real accrual, payout, parental ICS, weekend and comparison workflows',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/fr/tools/calculateur-conges-pto/');await expect(page.locator('[data-leave-workflow]')).toHaveCount(5);
 const accrual=page.locator('[data-leave-workflow="accrual"]');await accrual.locator('#ac-start').fill('2026-01-01');await accrual.locator('#ac-today').fill('2026-07-02');await accrual.locator('#ac-entitlement').fill('12');await accrual.getByRole('button',{name:'Calculer',exact:true}).click();await expect(accrual.locator('[data-output]')).toContainText('5,9');
 let dl=page.waitForEvent('download');await accrual.getByRole('button',{name:'Télécharger TXT'}).click();let d=await dl;expect(fs.readFileSync(await d.path(),'utf8')).toContain('Jours acquis : 5,9');await accrual.locator('#ac-start').fill('');await expect(accrual.locator('[data-txt]')).toBeDisabled();
 const payout=page.locator('[data-leave-workflow="payout"]');await payout.locator('#po-country').selectOption('KE');await payout.locator('#po-unused').fill('10');await payout.locator('#po-salary').fill('2600');await payout.getByRole('button',{name:'Calculer',exact:true}).click();await expect(payout.locator('[data-output]')).toContainText('1 200');
 const parental=page.locator('[data-leave-workflow="parental"]');await page.evaluate(()=>{LEAVE_ENTITLEMENTS.KE.paternityLeave.days=3;});await parental.locator('#pp-country').selectOption('KE');await parental.locator('#pp-type').selectOption('pat');await parental.locator('#pp-due').fill('2026-09-18');await parental.getByRole('button',{name:'Calculer',exact:true}).click();await expect(parental.locator('[data-output]')).toContainText('2026-09-22');dl=page.waitForEvent('download');await parental.getByRole('button',{name:'Télécharger ICS'}).click();d=await dl;const ics=fs.readFileSync(await d.path(),'utf8').replace(/\r\n /g,'');expect(ics).toContain('DTSTART;VALUE=DATE:20260918');expect(ics).toContain('DTEND;VALUE=DATE:20260923');expect(ics).toContain('DTEND;VALUE=DATE:20260924');expect(ics).toContain('TRIGGER:-P7D');expect(ics).toContain('SUMMARY:Congé paternité — Kenya');expect(ics).not.toContain('20260702');expect(ics.match(/BEGIN:VEVENT/g)).toHaveLength(2);await info.attach('french-parental-ics',{body:ics,contentType:'text/calendar'});await parental.locator('#pp-due').fill('');await expect(parental.getByRole('button',{name:'Télécharger ICS'})).toBeDisabled();
 const weekends=page.locator('[data-leave-workflow="weekends"]');await weekends.locator('#lw-country').selectOption('NG');await weekends.getByRole('button',{name:'Calculer',exact:true}).click();await expect(weekends.locator('[data-output]')).toContainText('Jour de l’An — 2026-01-01');await expect(weekends.locator('[data-output]')).toContainText('4 jours avec un congé le 2026-01-02');await expect(weekends.getByRole('button',{name:'Partager sur WhatsApp'}).first()).toBeVisible();
 const compare=page.locator('[data-leave-workflow="compare"]');await compare.getByRole('button',{name:'Calculer',exact:true}).click();await expect(compare.locator('tbody tr')).toHaveCount(54);await expect(compare.locator('[data-output]')).toContainText('à vérifier');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const artifact=require('path').resolve(__dirname,'../../../leave-workflow-evidence/french-leave-mobile.png');fs.mkdirSync(require('path').dirname(artifact),{recursive:true});await page.screenshot({path:artifact,fullPage:true});expect(errors).toEqual([]);
});
test('French native leave rights retain save/reload and parsed native exports',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/fr/tools/calculateur-conges-pto/');const form=page.locator('[data-frhr-app] form').first();await form.locator('#country').selectOption('KE');await form.locator('#daysTaken').fill('4');await form.getByRole('button',{name:'Afficher et calculer'}).click();await expect(page.locator('[data-result-rows]')).toContainText('17 jours');await page.locator('[data-save]').click();await page.reload();await expect(page.locator('#country')).toHaveValue('KE');await expect(page.locator('#daysTaken')).toHaveValue('4');await form.getByRole('button',{name:'Afficher et calculer'}).click();
 const result=page.locator('[data-result]');await result.locator('[data-copy]').click();await expect(result.locator('[data-status]')).toContainText('copié');
 for(const type of ['csv','txt','json','pdf']){const dl=page.waitForEvent('download');await result.locator('[data-'+type+']').click();const d=await dl;const buffer=fs.readFileSync(await d.path());if(type==='pdf'){const parsed=await require('pdf-parse')(buffer);expect(parsed.text).toContain('17 jours');expect(parsed.text.toLowerCase().replace(/\s+/g,' ')).toContain('conge annuel restant');}else if(type==='json'){const parsed=JSON.parse(buffer.toString());expect(parsed.result.annualLeave.days).toBe(21);expect(parsed.source).toBeTruthy();}else expect(buffer.toString()).toContain('17 jours');}
 await form.getByRole('button',{name:'Réinitialiser',exact:true}).click();await expect(result).toBeHidden();await page.locator('[data-clear]').click();expect(await page.evaluate(()=>localStorage.getItem('afrotools.frhr.leave'))).toBeNull();
});
