const {test,expect}=require('@playwright/test');
const fs=require('fs');
const routes={en:'/tools/fuel-tracker/',fr:'/fr/tools/suivi-carburant/',sw:'/sw/zana/ufuatiliaji-bei-za-mafuta/'};
function fixture(){const date=new Date().toISOString().slice(0,10),fuel=(type,price,extra={})=>({fuel_type:type,price,currency:'USD',unit:'litre',effective_date:date,last_verified_at:date,source_name:'Synthetic source',source_url:'https://example.org/fuel',confidence:'low',notes:'Synthetic fixture only.',...extra}),market=(id,code,latitude,fuels)=>({market_id:id,country_code:code,country_name:code,locality_name:id,latitude,longitude:30,granularity:'national',coverage_note:'Synthetic national reference.',fuels});return{schema_version:1,stale_after_days:45,markets:[market('tz-current','TZ',-6,[fuel('petrol',2),fuel('diesel',2.5)]),market('ke-stale','KE',0,[fuel('petrol',999,{effective_date:'2000-01-01'})]),market('ug-future','UG',2,[fuel('petrol',888,{effective_date:'2999-01-01'})]),market('ng-expired','NG',9,[fuel('petrol',777,{valid_to:'2000-01-01'})])]};}
for(const [locale,route]of Object.entries(routes))test(`${locale} shared market: semantics, stale gates, exports, location privacy and mobile`,async({page},info)=>{
 const requests=[];page.on('request',request=>requests.push(request.url()+' '+(request.postData()||'')));
 await page.route('**/data/fuel/markets.json',r=>r.fulfill({json:fixture()}));
 // The market finder must work independently of the historical national snapshot fetch.
 await page.route('**/data/fuel/latest.json',r=>r.fulfill({status:503,body:'unavailable'}));
 await page.addInitScript(()=>{window.testGeoCalls=0;Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition(success,failure){window.testGeoCalls++;if(window.testGeoDenied){failure({code:1});return;}success({coords:{latitude:-6.123456789,longitude:30.987654321}});}}});});
 await page.setViewportSize({width:390,height:844});await page.goto(route);const reject=page.locator('#afro-cookie-consent button').filter({hasText:/Reject analytics|Refuser|Kataa/});if(await reject.count())await reject.first().click();
 const root=page.locator('[data-fuel-market-locale]');await expect(root.locator('#fuel-country')).toBeEnabled();expect(await page.evaluate(()=>window.testGeoCalls)).toBe(0);
 for(const code of ['KE','UG','NG']){await root.locator('#fuel-country').selectOption(code);await expect(root.locator('#fuel-price')).toHaveValue('');await expect(root.locator('#fuel-fill-json')).toBeDisabled();await expect(root.locator('#fuel-result-price')).not.toContainText(/999|888|777/);}
 await root.locator('#fuel-country').selectOption('TZ');await expect(root.locator('#fuel-price')).toHaveValue('2');await root.locator('#fuel-quantity').fill('10');await root.locator('#fuel-fill-calc').focus();await page.keyboard.press('Enter');await expect(root.locator('#fuel-fill-result')).toBeVisible();
 async function saved(kind){const pending=page.waitForEvent('download');await root.locator('#fuel-fill-'+kind).click();return fs.readFileSync(await(await pending).path(),'utf8');}
 let result=JSON.parse(await saved('json'));expect(result.calculation.totalCost).toBe(20);expect(result.market.id).toBe('tz-current');expect(result.market.granularity).toBe('national');expect(result.market.sourceUrl).toBe('https://example.org/fuel');expect(result.priceBasis).toBe('market-reference');
 const visibleReject=page.getByRole('button',{name:/Reject analytics|Refuser|Kataa/});if(await visibleReject.count())await visibleReject.first().click();await root.locator('#fuel-fill-result').evaluate(el=>window.scrollTo({top:el.getBoundingClientRect().top+scrollY-100,behavior:'instant'}));await page.screenshot({path:info.outputPath('fuel-fill-'+locale+'-390.png')});
 let txt=await saved('txt');expect(txt).toContain({en:'Estimated fill cost',fr:'Coût estimé du plein',sw:'Makadirio ya gharama ya kujaza'}[locale]);expect(txt).toContain('https://example.org/fuel');
 await root.locator('#fuel-unit').selectOption('gallon');await expect(root.locator('#fuel-fill-result')).toBeHidden();await root.locator('#fuel-quantity').fill('2');await root.locator('#fuel-fill-calc').click();result=JSON.parse(await saved('json'));expect(result.calculation.litres).toBeCloseTo(7.570823568,10);expect(result.calculation.totalCost).toBeCloseTo(15.141647136,10);
 await root.locator('#fuel-fill-mode').selectOption('tank');await expect(root.locator('#fuel-quantity')).toBeHidden();await expect(root.locator('#fuel-tank-size')).toBeVisible();await root.locator('#fuel-unit').selectOption('litre');await root.locator('#fuel-tank-size').fill('40');await root.locator('#fuel-current-level').fill('25');await root.locator('#fuel-fill-calc').click();result=JSON.parse(await saved('json'));expect(result.calculation.litres).toBe(30);expect(result.calculation.totalCost).toBe(60);
 for(const invalid of ['','-1','101']){await root.locator('#fuel-current-level').fill(invalid);await root.locator('#fuel-fill-calc').click();await expect(root.locator('#fuel-fill-json')).toBeDisabled();}
 await root.locator('#fuel-current-level').fill('100');await root.locator('#fuel-fill-calc').click();expect(JSON.parse(await saved('json')).calculation.totalCost).toBe(0);
 await root.locator('#fuel-country').selectOption('KE');await root.locator('#fuel-price').fill('3');await root.locator('#fuel-current-level').fill('50');await root.locator('#fuel-fill-calc').click();result=JSON.parse(await saved('json'));expect(result.calculation.totalCost).toBe(60);expect(result.priceBasis).toBe('manual');expect(result.market).toBeNull();
 await root.locator('#fuel-use-location').click();expect(await page.evaluate(()=>window.testGeoCalls)).toBe(1);await expect(root.locator('#fuel-country')).toHaveValue('TZ');await expect(root.locator('#fuel-fill-json')).toBeDisabled();
 await page.evaluate(()=>{window.testGeoDenied=true;});await root.locator('#fuel-use-location').click();await expect(root.locator('#fuel-location-status')).toContainText({en:'denied',fr:'refusée',sw:'imekataliwa'}[locale]);
 const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage},url:location.href}));for(const coordinate of ['-6.123456789','30.987654321']){expect(storage).not.toContain(coordinate);expect(requests.join('\n')).not.toContain(coordinate);expect(requests.join('\n')).not.toContain(encodeURIComponent(coordinate));}
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=> (await axe.run('[data-fuel-market-locale]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}})).violations);expect(violations.map(v=>v.id)).toEqual([]);
 await root.evaluate(el=>window.scrollTo({top:el.getBoundingClientRect().top+scrollY-80,behavior:'instant'}));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('fuel-market-'+locale+'-390.png')});
 const broken=fixture();broken.markets[0].fuels[0].source_url='';await page.route('**/data/fuel/markets.json',r=>r.fulfill({json:broken}));await page.reload();await expect(root.locator('#fuel-data-status')).toContainText({en:'could not be loaded',fr:'Impossible de charger',sw:'hazijapakiwa'}[locale]);await expect(root.locator('#fuel-price')).toHaveValue('');await root.locator('#fuel-price').fill('4');await root.locator('#fuel-quantity').fill('5');await root.locator('#fuel-fill-calc').click();result=JSON.parse(await saved('json'));expect(result.calculation.totalCost).toBe(20);expect(result.market).toBeNull();
});
