const {test,expect}=require('@playwright/test');const fs=require('node:fs');const pdfParse=require('pdf-parse');
const variants=[{locale:'en',route:'/tools/idea-board/',country:'South Africa',level:'Low',currency:'Currency',source:'Source URL',confidence:'Confidence'}, {locale:'fr',route:'/fr/tools/tableau-idees/',country:'Afrique du Sud',level:'Faible',currency:'Devise',source:'URL de la source',confidence:'Confiance'}, {locale:'sw',route:'/sw/zana/kichunguzi-ushahidi-wa-mawazo/',country:'Afrika Kusini',level:'Ndogo',currency:'Sarafu',source:'URL ya chanzo',confidence:'Uhakika'}];
for(const v of variants)test(`${v.locale} native labels reach screen CSV TXT and PDF without mutating JSON`,async({page})=>{
 await page.route('**/.netlify/functions/idea-evidence**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({rows:[{id:'synthetic-locale',name:'=Synthetic example',country_code:'ZA',country_name:'South Africa',sector:'technology',risk:'low',currency:'ZAR',source_confidence:'low',startup_cost_min:100,startup_cost_max:200}],reportedTotal:1})}));
 await page.goto(v.route);await expect(page.locator('#iee-country option[value=ZA]')).toHaveText(v.country);await expect(page.locator('#iee-risk option[value=low]')).toHaveText(v.level);await page.locator('[data-search-form] button[type=submit]').click();await expect(page.locator('.iee-card')).toHaveCount(1);await expect(page.locator('.iee-risk')).toHaveText(v.level);await expect(page.locator('.iee-country')).toHaveText(v.country);await expect(page.locator('.iee-source')).toContainText(v.confidence+': '+v.level);await page.locator('[data-action^="add:"]').click();
 async function download(action){const pending=page.waitForEvent('download');await page.locator(`[data-action=${action}]`).click();return fs.readFileSync(await (await pending).path())}
 const csv=(await download('csv')).toString('utf8');expect(csv.split('\n')[0]).toContain('"'+v.currency+'"');expect(csv.split('\n')[0]).toContain('"'+v.source+'"');expect(csv).toContain('"'+v.country+'"');expect(csv).toContain('"'+v.level+'"');expect(csv).toContain('"\'=Synthetic example"');
 const txt=(await download('txt')).toString('utf8');expect(txt).toContain(v.country);expect(txt).toContain(v.confidence+': '+v.level);
 const pdf=await pdfParse(await download('pdf'));expect(pdf.text).toContain(v.country);expect(pdf.text).toContain(v.confidence+': '+v.level);
 const backup=JSON.parse((await download('backup')).toString('utf8'));expect(backup.items[0].countryName).toBe('South Africa');expect(backup.items[0].risk).toBe('low');expect(backup.items[0].source.confidence).toBe('low');expect(backup.items[0].name).toBe('=Synthetic example');
});
