const{test,expect}=require('@playwright/test');const fs=require('fs'),parse=require('pdf-parse');
const locales={en:['/tools/invoice-generator/','Partially paid','Paid','Unpaid'],fr:['/fr/tools/generateur-factures/','Partiellement payé','Payé','Non payé'],sw:['/sw/zana/kizalishaji-ankara/','Imelipwa kiasi','Imelipwa','Haijalipwa']};
async function reveal(page,id){const el=page.locator('#'+id);for(const d of await el.locator('xpath=ancestor::details').all())if(await d.getAttribute('open')===null)await d.locator('summary').first().click();return el;}
async function dl(page,id){const pending=page.waitForEvent('download');await(await reveal(page,id)).click();return fs.readFileSync(await(await pending).path());}
for(const[locale,[route,partial,paid,unpaid]]of Object.entries(locales))test(`${locale} document modes preserve recorded payments and custom tax`,async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:390,height:844});const requests=[];page.on('request',r=>requests.push(r.url()+' '+(r.postData()||'')));await page.goto(route);
 await page.locator('#companyName').fill('SYNTHETIC-PAYMENT-PRIVATE-72');await page.locator('#clientName').fill('Synthetic client');await page.locator('.li-desc').fill('Synthetic service');await page.locator('#currency').selectOption('USD');await page.locator('.li-price').fill('100');await(await reveal(page,'taxType')).selectOption('none');await(await reveal(page,'amountPaid')).fill('25');await(await reveal(page,'paymentTerms')).selectOption('net-30');
 for(const mode of ['receipt','invoice','estimate','receipt']){
  await page.locator('#documentType').selectOption(mode);await expect(page.locator('#amountPaid')).toHaveValue('25');await expect(page.locator('#paymentTerms')).toHaveValue('net-30');await expect(page.locator('#markPaid')).not.toBeChecked();await expect(page.locator('#previewStatus')).toHaveText(partial);await expect(page.locator('#invoiceStatusPanel')).toContainText(partial);await expect(page.locator('#invoiceStatusPanel')).toContainText('75.00');
  await page.locator('#invoiceReviewConfirm').check();const text=(await parse(await dl(page,'btnPDF'))).text;expect(text).toContain(partial);expect(text).toContain('USD 25.00');expect(text).toContain('USD 75.00');
 }
 await(await reveal(page,'taxType')).selectOption('vat');await(await reveal(page,'taxRate')).fill('12.34');for(const currency of ['KES','USD']){await page.locator('#currency').selectOption(currency);await expect(page.locator('#taxRate')).toHaveValue('12.34');await expect(page.locator('#taxType')).toHaveValue('vat');await expect(page.locator('#amountPaid')).toHaveValue('25');await expect(page.locator('.li-price')).toHaveValue('100');}
 await page.locator('#invoiceReviewConfirm').check();const backup=await dl(page,'btnExportJson');const state=JSON.parse(backup);expect(state.ap).toBe('25');expect(state.tr).toBe('12.34');expect(state.pt).toBe('net-30');
 // A historical contradictory paid flag cannot fabricate a payment on restore.
 state.mp='1';await page.locator('#importJsonInput').setInputFiles({name:'synthetic-mismatch.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(state))});await expect(page.locator('#amountPaid')).toHaveValue('25');await expect(page.locator('#markPaid')).not.toBeChecked();await expect(page.locator('#previewStatus')).toHaveText(partial);
 await(await reveal(page,'withholdingPercent')).fill('10');await(await reveal(page,'markPaid')).check();await expect(page.locator('#amountPaid')).toHaveValue('102.34');await expect(page.locator('#previewStatus')).toHaveText(paid);await expect(page.locator('#invoiceStatusPanel')).toContainText('0.00');
 await page.locator('.li-price').fill('200');await expect(page.locator('#amountPaid')).toHaveValue('102.34');await expect(page.locator('#markPaid')).not.toBeChecked();await expect(page.locator('#previewStatus')).toHaveText(partial);
 await(await reveal(page,'markPaid')).check();await expect(page.locator('#amountPaid')).toHaveValue('204.68');await(await reveal(page,'markPaid')).uncheck();await expect(page.locator('#amountPaid')).toHaveValue('0');await expect(page.locator('#previewStatus')).toHaveText(unpaid);
 await page.locator('#importJsonInput').setInputFiles({name:'synthetic-backup.json',mimeType:'application/json',buffer:backup});await expect(page.locator('#amountPaid')).toHaveValue('25');await expect(page.locator('#taxRate')).toHaveValue('12.34');await expect(page.locator('#paymentTerms')).toHaveValue('net-30');
 await(await reveal(page,'btnSaveInvoice')).click();await page.reload();await page.locator("#inv-saved-grid .invoice-saved-card").first().click();await expect(page.locator('#amountPaid')).toHaveValue('25');await expect(page.locator('#taxRate')).toHaveValue('12.34');await expect(page.locator('#previewStatus')).toHaveText(partial);
 await(await reveal(page,'dueDate')).fill('2000-01-01');await expect(page.locator('#previewStatus')).toHaveText(partial);await expect(page.locator('#overdueBar')).toBeVisible();await expect(page.locator('#invoiceStatusPanel')).toContainText(partial);
 for(const width of [320,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
 expect(requests.join('\n')).not.toContain('SYNTHETIC-PAYMENT-PRIVATE-72');
});
