const{test,expect}=require('@playwright/test');const fs=require('fs');
for(const[locale,route,menu]of[['en','/tools/mobile-money-fees/','Open menu'],['fr','/fr/tools/frais-mobile-money/','Ouvrir le menu'],['sw','/sw/zana/ada-pesa-simu/','Fungua menyu']])for(const width of[320,390])for(const theme of['light','dark'])test(`${locale} ${width}px ${theme}: complete three-quote result, accessibility and local JSON`,async({page})=>{
 await page.setViewportSize({width,height:844});await page.clock.setFixedTime(new Date('2026-09-16T12:00:00Z'));const sends=[];page.on('request',r=>sends.push(r.url()+' '+(r.postData()||'')));await page.goto(route);
 if(theme==='dark'){await page.getByRole('button',{name:menu,exact:true}).click();await page.locator('#mobThemeToggle').click();await page.keyboard.press('Escape');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');}
 // Axe cannot reliably evaluate text over gradients; protect the manually inspected heading color too.
 await expect.poll(()=>page.locator('.rm-hero h1').evaluate(node=>{const rgb=getComputedStyle(node).color.match(/[\d.]+/g).slice(0,3).map(Number);const lum=values=>values.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);const foreground=lum(rgb);return Math.min(...[[16,47,98],[8,121,104]].map(stop=>{const background=lum(stop);return(Math.max(foreground,background)+.05)/(Math.min(foreground,background)+.05);}));})).toBeGreaterThanOrEqual(3);
 if(locale==='sw'){await expect(page.locator('.rm-badges')).toContainText('Rejea rasmi zilizochapishwa');await expect(page.locator('.rm-badges')).not.toContainText('Official');}
 await page.locator('#mm-provider').selectOption('airtel-tanzania');await expect(page.locator('#mm-action option')).toHaveCount(2);await page.locator('#mm-action').selectOption('withdraw');await page.locator('#mm-amount').fill('3000');await page.locator('#mm-tariff-form button[type=submit]').click();await expect(page.locator('#mm-tariff-result')).toContainText('590 TZS');
 await page.locator('#mm-third').focus();await page.keyboard.press('Space');for(const[l,fee]of[['a','30'],['b','20'],['c','10']])for(const[k,v]of Object.entries({label:'PRIVATE-SYNTHETIC-Éwé-'+l,market:locale==='fr'?'Sénégal':'Synthetic market',currency:'XOF',amount:'10000',sender:fee,recipient:'5',observed:'2026-09-16T11:00'}))await page.locator('#mm-'+l+'-'+k).fill(v);
 await page.locator('#mm-form button[type=submit]').focus();await page.keyboard.press('Enter');await expect(page.locator('#mm-primary-value')).toHaveText('15 XOF');await expect(page.locator('#mm-result-list .rm-result')).toHaveCount(3);
 const download=page.waitForEvent('download');await page.locator('#mm-json').click();const json=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));expect(json.result.quotes.map(q=>q.totalFee)).toEqual([35,25,15]);expect(json.result.quotes[2].label).toBe('PRIVATE-SYNTHETIC-Éwé-c');expect(sends.join('\n')).not.toContain('PRIVATE-SYNTHETIC');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const r=await axe.run({include:[['.rm-hero'],['main']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}});return r.violations.filter(x=>['serious','critical'].includes(x.impact)).map(x=>({id:x.id,nodes:x.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});expect(violations).toEqual([]);
});
