const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),pdfParse=require('pdf-parse');
const routes={en:'/morocco/ma-paye',fr:'/fr/maroc/calculateur-salaire-net',sw:'/sw/morocco/kikokotoo-kodi-mshahara/',legacy:'/fr/morocco/ma-paye'};
test('native routes retain keyboard, contrast and reflow at 320px, dark mode and 200%',async({page})=>{
 test.setTimeout(120000);
 for(const route of Object.values(routes).slice(0,3))for(const view of [{width:320,zoom:1,scheme:'light'},{width:390,zoom:1,scheme:'dark'},{width:750,zoom:2,scheme:'light'}]){
  await page.setViewportSize({width:view.width,height:850});await page.emulateMedia({colorScheme:view.scheme});await page.goto(route);await page.evaluate(z=>document.documentElement.style.zoom=String(z),view.zoom);await page.locator('#ma-gross').focus();await page.keyboard.type('10000');await page.keyboard.press('Tab');await expect(page.locator('#ma-presets button').first()).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#ma-net')).toContainText(/2.?331[,.]50/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const r=await axe.run(document.querySelector('main'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)}));});expect(violations).toEqual([]);
 }
});
for(const [locale,route]of Object.entries(routes))test(`${locale}: source-backed calculation, private export, reverse and mobile parity`,async({page},info)=>{
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')requests.push(r.url());});
 await page.setViewportSize({width:390,height:844});await page.goto(route);await page.locator('#ma-gross').fill('10000');await page.locator('#ma-form button[type=submit]').click();
 await expect(page.locator('#ma-net')).toContainText(/8.?903[,.]64/);await expect(page.locator('[data-field=professional]')).toContainText(/30.?000[,.]00/);
 await page.locator('[data-save]').click();await page.locator('#ma-gross').fill('3000');await page.locator('[data-load]').click();await expect(page.locator('#ma-gross')).toHaveValue('10000');
 await page.locator('#ma-period').selectOption('annual');await page.locator('#ma-gross').fill('120000');await page.locator('#ma-form button[type=submit]').click();await expect(page.locator('[data-field=annualNet]')).toContainText(/106.?843[,.]68/);
 for(const format of ['json','csv','txt','pdf']){const pending=page.waitForEvent('download');await page.locator(`[data-export=${format}]`).click();const download=await pending,buffer=await fs.readFile(await download.path());if(format==='pdf'){await fs.writeFile(info.outputPath('report.pdf'),buffer);const parsed=await pdfParse(new Uint8Array(buffer));expect(parsed.text).toMatch(/106.?843[,.]68/);expect(parsed.text).not.toMatch(/undefined|NaN/);expect(parsed.numpages).toBeGreaterThan(0);}if(format==='json'){const exported=JSON.parse(buffer.toString());expect(exported.result.annualNet).toBeCloseTo(106843.68,6);expect(exported.result.contributionEvidence).toContain('unresolved');}if(format==='csv')expect(buffer.toString()).toContain('106843.68');}
 await page.locator('#ma-target').fill('10000');await page.locator('[data-reverse]').click();const once=await page.locator('#ma-gross').inputValue();await page.locator('[data-reverse]').click();await expect(page.locator('#ma-gross')).toHaveValue(once);
 await page.locator('#ma-gross').fill('0');await page.locator('#ma-form button[type=submit]').click();await expect(page.locator('#ma-net')).toContainText(/0[,.]00/);await page.locator('#ma-gross').fill('-1');await page.locator('#ma-form button[type=submit]').click();await expect(page.locator('#ma-gross')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#ma-net')).toBeEmpty();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);expect(errors).toEqual([]);expect(requests).toEqual([]);await expect(page.locator('[data-ai]')).toBeDisabled();
 await page.locator('#ma-gross').fill('120000');await page.locator('#ma-form button[type=submit]').click();await page.screenshot({path:info.outputPath('morocco-'+locale+'-390.png'),fullPage:true});
});
test('explicit AI consent and failure preserve local calculation',async({page})=>{await page.goto(routes.fr);await page.locator('#ma-gross').fill('10000');await page.locator('#ma-form button[type=submit]').click();let payload;await page.route('**/.netlify/functions/ai-advisor',async r=>{payload=r.request().postDataJSON();await r.fulfill({status:503,body:'unavailable'});});await page.locator('#ma-consent').check();await page.locator('[data-ai]').click();await expect(page.locator('#ma-ai-result')).toContainText('indisponible');expect(payload.aiConsent).toBe('accepted');expect(payload.context.period).toBe('annual');await expect(page.locator('#ma-net')).toContainText(/8.?903[,.]64/);});

for(const status of [200,503])test(`late AI ${status} response cannot revive reset output`,async({page})=>{let release,arrived;const seen=new Promise(resolve=>arrived=resolve);await page.route('**/.netlify/functions/ai-advisor',async route=>{await new Promise(resolve=>{release=resolve;arrived();});await route.fulfill({status,contentType:'application/json',body:JSON.stringify({text:'Stale answer'})});});await page.goto(routes.en);await page.locator('#ma-gross').fill('10000');await page.locator('#ma-form button[type=submit]').click();await page.locator('#ma-consent').check();await page.locator('[data-ai]').click();await seen;await page.locator('[data-reset]').click();const response=page.waitForResponse('**/.netlify/functions/ai-advisor');release();await response;await page.waitForTimeout(100);await expect(page.locator('#ma-ai-result')).toBeEmpty();});
test('monthly reports preserve period, switches and dependent count; invalid input blocks exports',async({page})=>{await page.goto(routes.en);await page.locator('#ma-gross').fill('10000');await page.locator('#ma-form button[type=submit]').click();for(const format of ['txt','csv','pdf']){const pending=page.waitForEvent('download');await page.locator(`[data-export=${format}]`).click();const file=await pending,buffer=await fs.readFile(await file.path());const text=format==='pdf'?(await pdfParse(new Uint8Array(buffer))).text:buffer.toString();expect(text).toMatch(/10,?000[.]00/);expect(text).toMatch(/8,?903[.]64/);expect(text).toMatch(/monthly/i);expect(text).toMatch(/CNSS/);expect(text).toMatch(/AMO/);}await page.locator('#ma-gross').fill('');let downloads=0;page.on('download',()=>downloads++);await page.locator('[data-export=json]').click();await expect(page.locator('#ma-status')).toHaveAttribute('data-error','true');expect(downloads).toBe(0);});
test('legacy French identity remains the public French primary',async({page})=>{await page.goto(routes.legacy);const canonical='https://afrotools.com/fr/maroc/calculateur-salaire-net';await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href',canonical);await expect(page.locator('meta[property="og:url"]')).toHaveAttribute('content',canonical);expect(await page.locator('script[type="application/ld+json"]').allTextContents()).toEqual(expect.arrayContaining([expect.stringContaining(canonical)]));});
test('eligible dependents and contribution comparison switches recalculate',async({page})=>{await page.goto(routes.en);await page.locator('#ma-gross').fill('10000');await page.locator('#ma-dependents').selectOption('6');await page.locator('#ma-form button[type=submit]').click();await expect(page.locator('[data-field=familyRelief]')).toContainText(/3,600[.]00/);await page.locator('#ma-cnss').uncheck();await page.locator('#ma-amo').uncheck();await expect(page.locator('#ma-net')).toBeEmpty();await page.locator('#ma-form button[type=submit]').click();await expect(page.locator('[data-field=cnss]')).toContainText(/0[.]00/);await expect(page.locator('[data-field=amo]')).toContainText(/0[.]00/);await expect(page.locator('#ma-net')).toContainText(/9,550[.]00/);});
