const {test,expect}=require('@playwright/test'),fs=require('node:fs');
const {PDFDocument}=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');
const routes={en:'/tools/pdf-form-filler/',fr:'/fr/tools/remplir-formulaire-pdf/',sw:'/sw/zana/kujaza-fomu-pdf/'};
let fixture;
test.beforeAll(async()=>{const d=await PDFDocument.create(),p=d.addPage([400,500]),p2=d.addPage([400,500]),f=d.getForm();p.drawText('PUBLIC SYNTHETIC FORM',{x:20,y:470});p2.drawText('SECOND PAGE RETAINED',{x:20,y:470});const text=f.createTextField('Applicant');text.enableRequired();text.addToPage(p,{x:20,y:410,width:260,height:25});f.createCheckBox('Agreed').addToPage(p,{x:20,y:360,width:20,height:20});const dd=f.createDropdown('Choice');dd.addOptions(['Revenue','Year 1']);dd.addToPage(p,{x:20,y:310,width:160,height:25});const rg=f.createRadioGroup('Delivery');rg.addOptionToPage('Email',p,{x:20,y:260,width:20,height:20});rg.addOptionToPage('Paper',p,{x:60,y:260,width:20,height:20});fixture=Buffer.from(await d.save());});
async function download(page,info){const waiting=page.waitForEvent('download',{timeout:7000});await page.locator('#downloadBtn').click();let d;try{d=await waiting;}catch(e){if(await page.locator('.pdg-overlay').isVisible()){await page.screenshot({path:info.outputPath('account-gate.png')});throw new Error('Guest local export opened an account-registration dialog instead of downloading');}throw e;}return fs.readFileSync(await d.path());}
for(const[locale,route]of Object.entries(routes))test(`${locale} guest interactive and flattened form outputs retain synthetic values`,async({page},info)=>{
 await page.setViewportSize({width:390,height:844});const requests=[];page.on('request',r=>requests.push(r.url()+' '+(r.postData()||'')));await page.route('**/api/capture-lead',r=>r.abort());
 await page.goto(route);await page.locator('#fileInput').setInputFiles({name:'synthetic-form-95173.pdf',mimeType:'application/pdf',buffer:fixture});await expect(page.locator('#pdf-form-field-0')).toBeVisible();
 await page.locator('#pdf-form-field-0').fill('Nadia École 95173');await page.locator('#pdf-form-field-1').check();await page.locator('#pdf-form-field-2').selectOption('Year 1');await page.locator('input[type=radio][value=Paper]').check();
 const interactive=await download(page,info),doc=await PDFDocument.load(interactive),f=doc.getForm();expect(doc.getPageCount()).toBe(2);expect(f.getTextField('Applicant').getText()).toBe('Nadia École 95173');expect(f.getCheckBox('Agreed').isChecked()).toBe(true);expect(f.getDropdown('Choice').getSelected()).toEqual(['Year 1']);expect(f.getRadioGroup('Delivery').getSelected()).toBe('Paper');
 await page.locator('#flattenCheck').check();const flattened=await download(page,info),flat=await PDFDocument.load(flattened);expect(flat.getPageCount()).toBe(2);expect(flat.getForm().getFields()).toHaveLength(0);
 const parsed=await page.evaluate(async bytes=>{const d=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise,out=[];for(let i=1;i<=d.numPages;i++)out.push((await(await d.getPage(i)).getTextContent()).items.map(x=>x.str).join(' '));await d.destroy();return out;},[...flattened]);expect(parsed[0]).toContain('Nadia École 95173');expect(parsed[0]).toContain('Year 1');expect(parsed[1]).toContain('SECOND PAGE RETAINED');
 expect(requests.join('\n')).not.toContain('/api/capture-lead');expect(requests.join('\n')).not.toContain('Nadia');expect(requests.join('\n')).not.toContain('synthetic-form-95173');expect(await page.locator('.pdg-overlay').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const png=await page.evaluate(async bytes=>{const d=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise,p=await d.getPage(1),v=p.getViewport({scale:1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const png=c.toDataURL().split(',')[1];await d.destroy();return png;},[...flattened]);fs.writeFileSync(info.outputPath(`filled-${locale}.png`),Buffer.from(png,'base64'));
 fs.writeFileSync(info.outputPath(`filled-${locale}.pdf`),flattened);
});
