const {test,expect}=require('@playwright/test'),fs=require('node:fs');const {PDFDocument}=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');let A,B;test.beforeAll(async()=>{async function pdf(label){const d=await PDFDocument.create();d.addPage([300,400]).drawText(label,{x:20,y:200,size:16});return Buffer.from(await d.save());}A=await pdf('SOURCE ALPHA');B=await pdf('SOURCE BETA');});
const routes={en:'/tools/pdf-reorder/',fr:'/fr/tools/reorganiser-pdf/',sw:'/sw/zana/kupanga-kurasa-pdf/'};
async function upload(page,name,buffer,id='#fileInput'){await page.locator(id).setInputFiles({name,mimeType:'application/pdf',buffer});}
async function exported(page){await page.locator('#reviewConfirm').check();const waiting=page.waitForEvent('download');await page.locator('#btnDownload').click();const d=await waiting;const bytes=fs.readFileSync(await d.path());fs.writeFileSync(test.info().outputPath(d.suggestedFilename()),bytes);const text=await page.evaluate(async bytes=>{const d=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise;const out=[];for(let i=1;i<=d.numPages;i++)out.push((await(await d.getPage(i)).getTextContent()).items.map(x=>x.str).join(' '));return out;},[...bytes]);return {name:d.suggestedFilename(),text};}
for(const[locale,route]of Object.entries(routes)){
 test(`${locale} late upload cannot replace current PDF and keyboard selection keeps focus`,async({page})=>{await page.goto(route);await page.evaluate(()=>{const original=PdfUtils.loadPdf;PdfUtils.loadPdf=async function(file){if(file.name==='A.pdf')await new Promise(r=>window.releaseOld=r);return original.apply(this,arguments);};});await upload(page,'A.pdf',A);await page.waitForFunction(()=>!!window.releaseOld);await expect(page.locator('#btnDownload')).toBeDisabled();await expect(page.locator('#btnReset')).toBeDisabled();await upload(page,'B.pdf',B);await expect(page.locator('.page-card')).toHaveCount(1);await page.evaluate(()=>window.releaseOld());await page.waitForTimeout(500);const result=await exported(page);expect(result).toEqual({name:'B_managed.pdf',text:['SOURCE BETA']});await page.locator('.page-card').focus();await page.keyboard.press('Space');await expect(page.locator('.page-card')).toBeFocused();});
 test(`${locale} late export and late add cannot publish into replacement source`,async({page})=>{await page.goto(route);await upload(page,'A.pdf',A);await expect(page.locator('.page-card')).toHaveCount(1);await page.evaluate(()=>{const original=PDFLib.PDFDocument.create;PDFLib.PDFDocument.create=async function(){PDFLib.PDFDocument.create=original;await new Promise(r=>window.releaseExport=r);return original.apply(this,arguments);};});const downloads=[];page.on('download',d=>downloads.push(d));await page.locator('#reviewConfirm').check();await page.locator('#btnDownload').click();await page.waitForFunction(()=>!!window.releaseExport);await upload(page,'B.pdf',B);await expect(page.locator('#fileName')).toHaveText('B.pdf');await expect(page.locator('.page-card')).toHaveCount(1);await page.evaluate(()=>window.releaseExport());await page.waitForTimeout(500);expect(downloads).toHaveLength(0);expect(await exported(page)).toEqual({name:'B_managed.pdf',text:['SOURCE BETA']});
 await page.evaluate(()=>{const original=PdfUtils.loadPdf;PdfUtils.loadPdf=async function(file){if(file.name==='add-A.pdf')await new Promise(r=>window.releaseAdd=r);return original.apply(this,arguments);};});await upload(page,'add-A.pdf',A,'#insertFileInput');await page.waitForFunction(()=>!!window.releaseAdd);await upload(page,'new-B.pdf',B);await expect(page.locator('.page-card')).toHaveCount(1);await page.evaluate(()=>window.releaseAdd());await page.waitForTimeout(500);expect(await exported(page)).toEqual({name:'new-B_managed.pdf',text:['SOURCE BETA']});
 const priorDownloads=downloads.length;
 await page.evaluate(()=>{const original=PDFLib.PDFDocument.create;PDFLib.PDFDocument.create=async function(){PDFLib.PDFDocument.create=original;await new Promise(r=>window.releaseBeforeAdd=r);return original.apply(this,arguments);};});await page.locator('#reviewConfirm').check();await page.locator('#btnDownload').click();await page.waitForFunction(()=>!!window.releaseBeforeAdd);await upload(page,'committed-A.pdf',A,'#insertFileInput');await expect(page.locator('.page-card')).toHaveCount(2);await page.evaluate(()=>window.releaseBeforeAdd());await page.waitForTimeout(500);expect(downloads).toHaveLength(priorDownloads);expect(await exported(page)).toEqual({name:'new-B_managed.pdf',text:['SOURCE BETA','SOURCE ALPHA']});});
}

for(const[locale,route]of Object.entries(routes))test(`${locale} undo invalidates pending export and its review`,async({page})=>{
 await page.goto(route);await upload(page,'A.pdf',A);await expect(page.locator('.page-card')).toHaveCount(1);await page.locator('[data-action=rotateCW]').click();await page.evaluate(()=>{const original=PDFLib.PDFDocument.create;PDFLib.PDFDocument.create=async function(){PDFLib.PDFDocument.create=original;await new Promise(r=>window.releaseUndoExport=r);return original.apply(this,arguments);};});const downloads=[];page.on('download',d=>downloads.push(d));await page.locator('#reviewConfirm').check();await page.locator('#btnDownload').click();await page.waitForFunction(()=>!!window.releaseUndoExport);await page.locator('#btnUndo').click();await expect(page.locator('#reviewConfirm')).not.toBeChecked();await page.evaluate(()=>window.releaseUndoExport());await page.waitForTimeout(500);expect(downloads).toHaveLength(0);expect(await exported(page)).toEqual({name:'A_managed.pdf',text:['SOURCE ALPHA']});const d=await PDFDocument.load(fs.readFileSync(test.info().outputPath('A_managed.pdf')));expect(d.getPage(0).getRotation().angle).toBe(0);
});

for(const[locale,route]of Object.entries(routes))test(`${locale} duplicate retains source pages`,async({page})=>{await page.goto(route);await upload(page,'A.pdf',A);await expect(page.locator('.page-card')).toHaveCount(1);await page.locator('.page-card').click();await page.locator('#btnDuplicate').click();await expect(page.locator('.page-card')).toHaveCount(2);expect(await exported(page)).toEqual({name:'A_managed.pdf',text:['SOURCE ALPHA','SOURCE ALPHA']});});
