const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
const {PDFDocument}=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');
const out=path.join(__dirname,'../../test-results/password-artifacts');fs.mkdirSync(out,{recursive:true});
let fixture;const pw='Synthetic-Only-7264!',owner='Owner-Only-4829!';
test.beforeAll(async()=>{const d=await PDFDocument.create();d.addPage([400,500]).drawText('SYNTHETIC PASSWORD PDF 7264',{x:20,y:450,size:14});fixture=Buffer.from(await d.save());});
for(const[locale,route]of Object.entries({en:'/tools/pdf-password/',fr:'/fr/tools/proteger-pdf/',sw:'/sw/zana/kulinda-pdf-kwa-nenosiri/'}))test(`${locale} guest encrypted artifacts and native protect/unlock`,async({page})=>{
 test.setTimeout(120000);const result={locale};const requests=[],logs=[];page.on('console',m=>logs.push(m.text()));page.on('request',r=>requests.push(r.url()+' '+(r.postData()||'')));await page.setViewportSize({width:390,height:844});await page.goto(route);await page.locator('#pdfFileInput').setInputFiles({name:'Revenue {0}.pdf',mimeType:'application/pdf',buffer:fixture});await expect(page.locator('#fileList')).toContainText('Revenue {0}.pdf');await page.locator('#openPassword').fill(pw);await page.locator('#confirmPassword').fill(pw);await page.locator('#ownerPassword').fill(owner);await page.locator('#allowCopy').uncheck();await page.locator('#processBtn').click();await expect(page.locator('#actionRow')).toHaveClass(/\bon\b/,{timeout:60000});result.protectText=await page.locator('#resultCard').innerText();
 let protectedBytes;const dl=page.waitForEvent('download',{timeout:3000}).catch(()=>null);await page.locator('#downloadBtn').click();const downloaded=await dl;result.protectGuestDownload=!!downloaded;expect(downloaded,'guest protect download').not.toBeNull();result.gate=await page.locator('.pdg-overlay').isVisible();result.protectText=await page.locator('#resultCard').innerText();expect(result.protectText).toContain({en:'Protected 1 PDF.',fr:'Protection terminée : 1 PDF.',sw:'PDF 1 zimelindwa.'}[locale]);await page.screenshot({path:path.join(out,`${locale}-protect.png`)});
 if(downloaded){protectedBytes=fs.readFileSync(await downloaded.path());fs.writeFileSync(path.join(out,`${locale}-protected.pdf`),protectedBytes);await page.addScriptTag({url:'/assets/vendor/pdfjs/pdf.min.js'});result.reader=await page.evaluate(async({bytes,pw,owner})=>{pdfjsLib.GlobalWorkerOptions.workerSrc='/assets/vendor/pdfjs/pdf.worker.min.js';const out={};for(const [key,password]of Object.entries({none:undefined,wrong:'Incorrect-7264',correct:pw,owner})){try{const d=await pdfjsLib.getDocument({data:new Uint8Array(bytes),password}).promise;out[key]={pages:d.numPages,permissions:await d.getPermissions(),text:(await(await d.getPage(1)).getTextContent()).items.map(x=>x.str).join(' ')};await d.destroy();}catch(e){out[key]={name:e.name,code:e.code}}}return out;},{bytes:[...protectedBytes],pw,owner});expect(result.reader.none.name).toBe('PasswordException');expect(result.reader.wrong.name).toBe('PasswordException');expect(result.reader.correct.text).toContain('SYNTHETIC PASSWORD PDF 7264');expect(result.reader.owner.pages).toBe(1);expect(result.reader.correct.permissions).not.toContain(16);expect(result.reader.correct.permissions).toContain(4);
 }else{protectedBytes=fs.readFileSync(path.join(out,'en-protected.pdf'));await page.reload();}
 await page.locator('#modeUnlock').click();if(await page.locator('#clearFilesBtn').isVisible())await page.locator('#clearFilesBtn').click();await page.locator('#pdfFileInput').setInputFiles({name:'protected-synthetic.pdf',mimeType:'application/pdf',buffer:protectedBytes});await page.locator('#unlockPassword').fill('Incorrect-7264');await page.locator('#unlockProcessBtn').click();await expect(page.locator('#unlockProcessBtn')).toBeEnabled({timeout:60000});result.wrongPasswordText=await page.locator('#resultCard').innerText();expect(result.wrongPasswordText).toContain({en:'password was not accepted',fr:'mot de passe a été refusé',sw:'Nenosiri halikukubaliwa'}[locale]);expect(result.wrongPasswordText).not.toContain('input.pdf:');result.wrongHasDownload=await page.locator('#actionRow').evaluate(e=>e.classList.contains('on'));expect(result.wrongHasDownload).toBe(false);
 await page.locator('#unlockPassword').fill(pw);await page.locator('#unlockProcessBtn').click();await expect(page.locator('#actionRow')).toHaveClass(/\bon\b/,{timeout:60000});result.correctUnlockText=await page.locator('#resultCard').innerText();const udl=page.waitForEvent('download',{timeout:3000}).catch(()=>null);await page.locator('#downloadBtn').click();const u=await udl;result.unlockGuestDownload=!!u;expect(u,'guest unlock download').not.toBeNull();result.correctUnlockText=await page.locator('#resultCard').innerText();expect(result.correctUnlockText).toContain({en:'Unlocked 1 PDF.',fr:'Déverrouillage terminé : 1 PDF.',sw:'PDF 1 zimefunguliwa.'}[locale]);if(u){const b=fs.readFileSync(await u.path());fs.writeFileSync(path.join(out,`${locale}-unlocked.pdf`),b);const d=await PDFDocument.load(b);expect(d.getPageCount()).toBe(1);result.unlockedEncrypted=d.isEncrypted;expect(d.isEncrypted).toBe(false);result.unlockedText=await page.evaluate(async bytes=>{const doc=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise;const t=(await(await doc.getPage(1)).getTextContent()).items.map(x=>x.str).join(' ');await doc.destroy();return t;},[...b]);expect(result.unlockedText).toContain('SYNTHETIC PASSWORD PDF 7264');}
 await page.setViewportSize({width:320,height:740});result.overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);result.sensitiveRequests=requests.filter(x=>x.includes(pw)||x.includes(owner)||x.includes('SYNTHETIC PASSWORD PDF 7264'));for(const marker of [pw,owner,'SYNTHETIC PASSWORD PDF 7264']){for(const value of [marker,encodeURIComponent(marker)]){expect(requests.join(' ')).not.toContain(value);expect(logs.join(' ')).not.toContain(value);}}expect(result.overflow).toBe(false);fs.writeFileSync(path.join(out,`${locale}.json`),JSON.stringify(result,null,2));
});

for(const [locale,route] of Object.entries({en:'/tools/pdf-password/',fr:'/fr/tools/proteger-pdf/',sw:'/sw/zana/kulinda-pdf-kwa-nenosiri/'})) test(`${locale} unreadable PDF has native error and no output`,async({page})=>{
 await page.goto(route);await page.locator('#pdfFileInput').setInputFiles({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('SYNTHETIC INVALID PDF')});await page.locator('#openPassword').fill(pw);await page.locator('#confirmPassword').fill(pw);await page.locator('#processBtn').click();await expect(page.locator('#resultRows')).toContainText({en:'could not be processed',fr:'n’a pas pu être traité',sw:'haikuweza kuchakatwa'}[locale]);await expect(page.locator('#actionRow')).not.toHaveClass(/\bon\b/);await expect(page.locator('#resultRows')).not.toContainText('input.pdf:');
});
