const {test,expect}=require('@playwright/test');
test.use({trace:'off',video:'off',screenshot:'off'});
const routes={en:'/tools/pdf-workspace/',fr:'/fr/tools/espace-pdf/',sw:'/sw/zana/nafasi-pdf/'};
const key='afrotools-saved-pdf-workspace';
async function prepare(page,baseURL,locale,raw){
 const errors=[];page.on('pageerror',()=>errors.push('pageerror'));page.on('dialog',d=>d.accept());await page.setViewportSize({width:390,height:844});
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.abort());
 await page.route('**/__history_fixture__',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Synthetic history fixture</title>'}));
 await page.goto('/__history_fixture__');
 await page.evaluate(async({key,raw})=>{if(raw!==undefined)localStorage.setItem(key,raw);await new Promise((resolve,reject)=>{const request=indexedDB.open('afrotools-pdf-workspace',1);request.onupgradeneeded=()=>request.result.createObjectStore('recent-files');request.onsuccess=()=>{const db=request.result,tx=db.transaction('recent-files','readwrite');tx.objectStore('recent-files').put(new Uint8Array([1,2,3]),'legacy');tx.objectStore('recent-files').put(new Uint8Array([4,5,6]),'unindexed');tx.oncomplete=()=>{db.close();resolve()};tx.onabort=()=>reject(Error('seed failure'))};request.onerror=()=>reject(Error('seed open failure'))})},{key,raw});
 await page.goto(routes[locale]);await page.waitForFunction(()=>window.AfroPdfHistory);return errors;
}
async function snapshot(page){return page.evaluate(async()=>{return new Promise((resolve,reject)=>{const request=indexedDB.open('afrotools-pdf-workspace',2);request.onsuccess=()=>{const db=request.result,tx=db.transaction(['recent-files','recent-operations','history-state'],'readonly'),output={};for(const name of ['recent-files','recent-operations','history-state']){const store=tx.objectStore(name),keys=store.getAllKeys(),values=store.getAll();keys.onsuccess=()=>output[name+'Keys']=keys.result;values.onsuccess=()=>output[name]=values.result.map(v=>v instanceof Uint8Array?Array.from(v):v)}tx.oncomplete=()=>{db.close();resolve(output)};tx.onabort=()=>reject(Error('snapshot failure'))};request.onerror=()=>reject(Error('snapshot open failure'))})})}
async function fault(page,store,method){await page.evaluate(({store,method})=>{const original=IDBObjectStore.prototype[method];IDBObjectStore.prototype[method]=function(...args){if(this.name===store)throw new DOMException('Synthetic fault','QuotaExceededError');return original.apply(this,args)};window.restoreDatabase=()=>IDBObjectStore.prototype[method]=original},{store,method})}
const legacy=JSON.stringify([{id:'legacy',title:'Synthetic legacy.pdf',createdAt:1,updatedAt:1,data:{operation:'Synthetic saved operation',hasFile:true}}]);
for(const locale of Object.keys(routes)){
 test(locale+' PDF history: mobile actions are keyboard reachable and labelled',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale,legacy);const resume=page.locator('[data-pdf-history-action=resume]'),remove=page.locator('[data-pdf-history-action=delete]');await expect(resume).toBeVisible();await expect(resume).toHaveText({en:'Resume',fr:'Reprendre',sw:'Endelea'}[locale]);const box=await remove.boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);expect(box.x+box.width).toBeLessThanOrEqual(391);await resume.focus();await page.keyboard.press('Tab');await expect(remove).toBeFocused();await expect(page.locator('[data-pdf-history-id] time')).toBeVisible();expect(errors).toEqual([]);
 });
 test(locale+' PDF history: missing file copy never opens or changes the current document',async({page,baseURL})=>{
  const missing=JSON.stringify([{id:'missing',title:'Synthetic missing.pdf',createdAt:1,updatedAt:1,data:{hasFile:true}}]);const errors=await prepare(page,baseURL,locale,missing);await expect(page.locator('[data-pdf-history-id=missing]')).toBeVisible();await page.evaluate(()=>{window.resumeCalls=0;window.loadPDFBytes=async()=>window.resumeCalls++});await page.locator('[data-pdf-history-action=resume]').click();await expect(page.locator('#pdfHistoryError')).toContainText({en:'no saved PDF copy',fr:'pas de copie PDF',sw:'haina nakala ya PDF'}[locale]);expect(await page.evaluate(()=>window.resumeCalls)).toBe(0);expect((await snapshot(page))['recent-operations'][0].data.hasFile).toBe(false);expect(errors).toEqual([]);
 });
 test(locale+' PDF history: legacy migration preserves metadata and unindexed bytes',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale,legacy);await expect(page.locator('[data-pdf-history-id=legacy]')).toBeVisible();const state=await snapshot(page);expect(state['recent-filesKeys']).toEqual(['legacy','unindexed']);expect(state['recent-operations'][0].data.hasFile).toBe(true);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(legacy);await page.reload();await expect(page.locator('[data-pdf-history-id=legacy]')).toBeVisible();expect((await snapshot(page))['recent-operations']).toHaveLength(1);expect(errors).toEqual([]);
 });
 test(locale+' PDF history: corrupt metadata never trims PDF bytes or marks migration complete',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale,'{broken');await expect(page.locator('#pdfHistoryError')).toBeVisible();expect(await page.evaluate(()=>window.pdfSaveOp('Synthetic.pdf','Synthetic',new Uint8Array([7])))).toBeNull();const state=await snapshot(page);expect(state['recent-filesKeys']).toEqual(['legacy','unindexed']);expect(state['recent-operations']).toEqual([]);expect(state['history-state']).toEqual([]);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe('{broken');expect(errors).toEqual([]);
 });
 for(const store of ['recent-files','recent-operations'])test(locale+' PDF history: '+store+' write failure rolls back both stores',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale,legacy);await page.evaluate(()=>window.AfroPdfHistory.list());const before=await snapshot(page);await fault(page,store,'put');expect(await page.evaluate(()=>window.pdfSaveOp('Synthetic new.pdf','Synthetic',new Uint8Array([7,8,9])))).toBeNull();await expect(page.locator('#pdfHistoryError')).toBeVisible();expect(await snapshot(page)).toEqual(before);await page.evaluate(()=>window.restoreDatabase());expect(await page.evaluate(async()=>!!await window.pdfSaveOp('Synthetic new.pdf','Synthetic',new Uint8Array([7,8,9])))).toBe(true);expect((await snapshot(page))['recent-operations']).toHaveLength(2);expect(errors).toEqual([]);
 });
 test(locale+' PDF history: deletion failure rolls back file bytes and metadata',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale,legacy);await expect(page.locator('[data-pdf-history-action=delete]')).toBeVisible();const before=await snapshot(page);await fault(page,'recent-operations','delete');expect(await page.evaluate(()=>window.pdfDelSaved('legacy'))).toBe(false);expect(await snapshot(page)).toEqual(before);await expect(page.locator('[data-pdf-history-id=legacy]')).toBeVisible();await page.evaluate(()=>window.restoreDatabase());await page.locator('[data-pdf-history-action=delete]').click();await expect(page.locator('[data-pdf-history-id]')).toHaveCount(0);await expect(page.locator('[data-pdf-history-status]')).toBeFocused();const after=await snapshot(page);expect(after['recent-filesKeys']).toEqual(['unindexed']);expect(after['recent-operations']).toEqual([]);await page.reload();await page.evaluate(()=>window.AfroPdfHistory.list());expect((await snapshot(page))['recent-operations']).toEqual([]);expect(errors).toEqual([]);
 });
 test(locale+' PDF history: committed real PDF resumes after reload',async({page,baseURL})=>{
  const errors=await prepare(page,baseURL,locale);const id=await page.evaluate(async()=>{await window.ensurePDFRuntime();const doc=await PDFLib.PDFDocument.create();doc.addPage([200,300]);return (await window.pdfSaveOp('Synthetic recovery.pdf','Synthetic download',await doc.save())).id});await page.reload();await page.locator('[data-pdf-history-id="'+id+'"] [data-pdf-history-action=resume]').click();await expect(page.locator('#tbFn')).toHaveText('Synthetic recovery.pdf');await expect(page.locator('#ws')).toHaveClass(/on/);expect(errors).toEqual([]);
 });
}
test('PDF history: concurrent saves enforce capacity without eviction',async({page,baseURL})=>{
 const errors=await prepare(page,baseURL,'en');const result=await page.evaluate(async()=>{const result=await Promise.allSettled(Array.from({length:11},(_,i)=>window.AfroPdfHistory.save('Synthetic '+i+'.pdf','Synthetic',new Uint8Array([i]))));return {saved:result.filter(r=>r.status==='fulfilled').length,failed:result.filter(r=>r.status==='rejected').map(r=>r.reason.code)}});expect(result).toEqual({saved:10,failed:['LIMIT_REACHED']});const state=await snapshot(page);expect(state['recent-operations']).toHaveLength(10);expect(state['recent-files']).toHaveLength(12);expect(errors).toEqual([]);
});
test('PDF history: interrupted migration leaves marker unset and legacy data recoverable',async({page,baseURL})=>{
 await page.addInitScript(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='recent-operations')throw new DOMException('Synthetic migration failure','QuotaExceededError');return original.apply(this,args)};window.restoreDatabase=()=>IDBObjectStore.prototype.put=original});
 const errors=await prepare(page,baseURL,'en',legacy);await expect(page.locator('#pdfHistoryError')).toBeVisible();let state=await snapshot(page);expect(state['recent-operations']).toEqual([]);expect(state['history-state']).toEqual([]);expect(state['recent-filesKeys']).toEqual(['legacy','unindexed']);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(legacy);await page.evaluate(()=>window.restoreDatabase());expect(await page.evaluate(async()=>(await window.AfroPdfHistory.list()).length)).toBe(1);state=await snapshot(page);expect(state['history-state']).toEqual([true]);expect(errors).toEqual([]);
});
