const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
const {PDFDocument}=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');
const routes={en:'/tools/pdf-form-filler/',fr:'/fr/tools/remplir-formulaire-pdf/',sw:'/sw/zana/kujaza-fomu-pdf/'};
let fixture;
test.beforeAll(async()=>{const d=await PDFDocument.create(),p=d.addPage([400,500]),f=d.getForm();const t=f.createTextField('Applicant');t.enableRequired();t.setText('SYNTHETIC');t.addToPage(p,{x:20,y:420,width:200,height:25});const r=f.createRadioGroup('Delivery');r.addOptionToPage('Email',p,{x:20,y:370,width:20,height:20});r.addOptionToPage('Paper',p,{x:60,y:370,width:20,height:20});r.select('Paper');const o=f.createOptionList('Services');o.addOptions(['Water','Power','Road']);o.enableMultiselect();o.select(['Water','Road']);o.addToPage(p,{x:20,y:240,width:200,height:80});fixture=Buffer.from(await d.save());});
async function load(page,route){await page.setViewportSize({width:390,height:844});await page.goto(route);await page.locator('#fileInput').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:fixture});await expect(page.locator('#pdf-form-field-0')).toBeVisible();}
async function output(page){const download=page.waitForEvent('download');await page.locator('#downloadBtn').click();return PDFDocument.load(fs.readFileSync(await(await download).path()));}
for(const [locale,route]of Object.entries(routes)){
 test(`${locale} keyboard upload reset and replacement export use current file at 320px`,async({page},info)=>{
  await page.setViewportSize({width:320,height:740});await page.goto(route);
  await page.locator('#uploadZone').focus();const chooser=page.waitForEvent('filechooser');await page.keyboard.press('Enter');await(await chooser).setFiles({name:'first.pdf',mimeType:'application/pdf',buffer:fixture});
  await expect(page.locator('#pdf-form-field-0')).toHaveValue('SYNTHETIC');
  await page.locator('#pdf-form-field-0').focus();await page.keyboard.press('Tab');await expect(page.locator('input[type=radio][value=Paper]')).toBeFocused();
  await page.locator('#clearAllBtn').focus();await page.keyboard.press('Enter');await expect(page.locator('input[type=radio]:checked')).toHaveCount(0);
  await page.locator('#loadNewBtn').focus();await page.keyboard.press('Enter');await expect(page.locator('#uploadZone')).toBeFocused();await expect(page.locator('#workspace')).toBeHidden();
  const next=await PDFDocument.create(),p=next.addPage([400,500]);const f=next.getForm().createTextField('Replacement');f.setText('CURRENT ONLY');f.addToPage(p,{x:20,y:420,width:200,height:25});
  await page.locator('#fileInput').setInputFiles({name:'second.pdf',mimeType:'application/pdf',buffer:Buffer.from(await next.save())});await expect(page.locator('#pdf-form-field-0')).toHaveValue('CURRENT ONLY');await expect(page.locator('#fieldsPanel input')).toHaveCount(1);
  const saved=await output(page);expect(saved.getForm().getFields().map(f=>f.getName())).toEqual(['Replacement']);expect(saved.getForm().getTextField('Replacement').getText()).toBe('CURRENT ONLY');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`form-${locale}-320.png`)});
 });
 test(`${locale} seeded multiselect preserves both original selections`,async({page})=>{await load(page,route);expect(await page.locator('#pdf-form-field-2').evaluate(el=>Array.from(el.selectedOptions,o=>o.value))).toEqual(['Water','Road']);const d=await output(page);expect(d.getForm().getOptionList('Services').getSelected()).toEqual(['Water','Road']);});
 test(`${locale} required field blocks incomplete final export and focuses field`,async({page})=>{await load(page,route);const downloads=[];page.on('download',d=>downloads.push(d));await page.locator('#pdf-form-field-0').fill('');await page.locator('#downloadBtn').click();await expect(page.locator('#pdf-form-field-0')).toBeFocused();await expect(page.locator('#statusMsg')).toContainText({en:'required',fr:'obligatoires',sw:'lazima'}[locale]);expect(downloads).toHaveLength(0);});
 test(`${locale} clear radio exports empty and multiselect retains exact values`,async({page})=>{await load(page,route);await page.locator('#clearAllBtn').click();await page.locator('#pdf-form-field-0').fill('RESET SYNTHETIC');const cleared=await output(page);expect(cleared.getForm().getRadioGroup('Delivery').getSelected()).toBeUndefined();await page.locator('#pdf-form-field-2').selectOption(['Water','Road']);const saved=await output(page);expect(saved.getForm().getOptionList('Services').getSelected()).toEqual(['Water','Road']);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
 test(`${locale} replacement invalid PDF invalidates old form and shows usable error`,async({page})=>{await load(page,route);await page.locator('#fileInput').setInputFiles({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a PDF')});await expect(page.locator('#uploadStatus')).toBeVisible();await expect(page.locator('#workspace')).toBeHidden();await expect(page.locator('#downloadBtn')).toBeDisabled();await expect(page.locator('#uploadStatus')).not.toContainText('No PDF header');await expect(page.locator('#uploadStatus')).toContainText({en:'could not be opened',fr:'ne peut pas être ouvert',sw:'haiwezi kufunguliwa'}[locale]);await page.locator('#fileInput').setInputFiles({name:'recovered.pdf',mimeType:'application/pdf',buffer:fixture});await expect(page.locator('#pdf-form-field-0')).toHaveValue('SYNTHETIC');const recovered=await output(page);expect(recovered.getForm().getRadioGroup('Delivery').getSelected()).toBe('Paper');});
}
