const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
const path=require('node:path');
const {PDFDocument,PDFName}=require('../../assets/vendor/pdf-lib/pdf-lib.min.js');
const routes={en:'/tools/receipt-generator/',fr:'/fr/tools/generateur-recu/',sw:'/sw/zana/kizalishaji-risiti/'};
for(const locale of Object.keys(routes))for(const template of ['modern','tax','thermal','compact'])test(`${locale}: receipt ${template} keeps native exports and user values`,async({page},info)=>{
 const count=1;
 test.setTimeout(90000);await page.setViewportSize({width:390,height:844});await page.goto(routes[locale]);
 const defaults={en:{business:'Business Name',customer:'Walk-in customer',item:'Product or service',notes:'Thank you for your business.',terms:'Goods and services received in good condition. Keep this receipt for your records.'},fr:{business:'Nom de l’entreprise',customer:'Client de passage',item:'Produit ou service',notes:'Merci pour votre confiance.',terms:'Biens et services reçus en bon état. Conservez ce reçu dans vos dossiers.'},sw:{business:'Jina la biashara',customer:'Mteja wa dukani',item:'Bidhaa au huduma',notes:'Asante kwa kufanya biashara nasi.',terms:'Bidhaa na huduma zimepokelewa katika hali nzuri. Hifadhi risiti hii kwa kumbukumbu zako.'}}[locale];
 await expect(page.locator('#receiptPreview .r-biz')).toHaveText(defaults.business);
 await expect(page.locator('#receiptPreview .r-grid .r-value').first()).toHaveText(defaults.customer);
 await expect(page.locator('[data-item-field="desc"]').first()).toHaveValue(defaults.item);
 await expect(page.locator('[data-bind="notes"]')).toHaveValue(defaults.notes);
 await expect(page.locator('[data-bind="terms"]')).toHaveValue(defaults.terms);
 await page.locator('#businessName').fill('SYNTHETIC RECEIPT LAB');
 await expect.poll(()=>page.evaluate(()=>localStorage.getItem('afrotools-receipt-current-v2'))).toContain('SYNTHETIC RECEIPT LAB');
 const backup=await page.evaluate(count=>{const data=JSON.parse(localStorage.getItem('afrotools-receipt-current-v2'));data.business.name='Revenue';data.customer.name='Year 1';data.notes='Year 1';data.terms='Customer';data.receipt.number='VISUAL-2026';data.receipt.date='2026-09-16';data.payment.reference='Revenue';data.items=Array.from({length:count},(_,i)=>({...data.items[0],desc:'Marketing',qty:1,rate:25,discount:10}));Object.assign(data.totals,{taxRate:20,discount:0,serviceCharge:0,shipping:0,rounding:0});if(count>1){const canvas=document.createElement('canvas');canvas.width=120;canvas.height=40;const ctx=canvas.getContext('2d');ctx.fillStyle='#005bbb';ctx.fillRect(0,0,120,40);ctx.fillStyle='#fff';ctx.font='bold 24px Arial';ctx.fillText('TEST',26,29);data.business.logo=canvas.toDataURL('image/png');}return data;},count);
 await page.locator('#importJson').setInputFiles({name:'visual.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:2,data:backup}))});
 await page.locator('#template').selectOption(template);
 await page.locator('#paymentReference').fill('Revenue');await page.locator('h1').first().click();
 await expect(page.locator('#receiptPreview')).toContainText('Marketing');
 await expect(page.locator('#receiptPreview .r-grid .r-value').first()).toHaveText('Year 1');
 await expect(page.locator('#receiptPreview .r-payment')).toContainText('Revenue');
 await expect(page.locator('#receiptPreview')).toContainText('Year 1');await expect(page.locator('#receiptPreview')).toContainText('Customer');
 await expect(page.locator('#receiptPreview .r-grid .r-label').first()).toHaveText({en:'Customer',fr:'Client',sw:'Mteja'}[locale]);
 await expect(page.locator('#receiptPreview .r-grid .r-value').nth(1)).toHaveText({en:'PAID',fr:'PAYÉ',sw:'IMELIPWA'}[locale]);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('afrotools-receipt-current-v2')).status)).toBe('PAID');
 await expect(page.locator('#metricTotal')).toContainText((count*27).toLocaleString('en-US',{minimumFractionDigits:2}));
 await page.evaluate(()=>{const original=window.html2canvas;window.html2canvas=async function(...args){const clone=args[1].onclone;args[1].onclone=function(doc){clone(doc);const table=doc.querySelector("#receiptPreview .r-table");window.__receiptGeometry={width:table.getBoundingClientRect().width,rows:Array.from(table.querySelectorAll("tr")).map(row=>{const rect=row.getBoundingClientRect(),top=doc.getElementById("receiptPreview").getBoundingClientRect().top;return {top:Math.floor((rect.top-top)*2),bottom:Math.ceil((rect.bottom-top)*2)};}),cells:Array.from(table.querySelectorAll("tbody tr:first-child td")).map(cell=>({width:cell.clientWidth,scroll:cell.scrollWidth}))};};const canvas=await original.apply(this,args);window.__receiptCanvas=canvas;return canvas;};});
 await page.locator('#receiptReviewConfirm').check();
 const native={en:{receipt:'Receipt',status:'PAID',subtotal:'Subtotal',line:'Line total',footer:'Generated with AfroTools.com'},fr:{receipt:'Reçu',status:'PAYÉ',subtotal:'Sous-total',line:'Total de ligne',footer:'Créé avec AfroTools.com'},sw:{receipt:'Risiti',status:'IMELIPWA',subtotal:'Jumla ndogo',line:'Jumla ya mstari',footer:'Imetengenezwa kwa AfroTools.com'}}[locale];
 await expect(page.locator('#receiptPreview .r-footer')).toContainText(native.footer);
 for(const [format,selector]of [['txt','#txtBtn'],['csv','#csvBtn'],['json','#jsonBtn']]){const [file]=await Promise.all([page.waitForEvent('download'),page.locator(selector).click()]);const content=fs.readFileSync(await file.path(),'utf8');await info.attach('receipt.'+format,{body:Buffer.from(content),contentType:'text/plain'});for(const value of ['Revenue','Year 1','Marketing'])expect(content).toContain(value);if(format==='json'){const data=JSON.parse(content).data;expect(data.template).toBe(template);expect(data.status).toBe('PAID');expect(data.customer.name).toBe('Year 1');expect(data.notes).toBe('Year 1');}else{expect(content).toContain(native.receipt);expect(content).toContain(native.subtotal);expect(content).toContain('22.50');expect(content).toContain('27.00');if(format==='txt')expect(content).toContain(native.status);else expect(content).toContain(native.line);}}
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#downloadPdfBtn').click()]);const bytes=fs.readFileSync(await download.path());
 await info.attach('receipt.pdf',{body:bytes,contentType:'application/pdf'});
 const result=await page.evaluate(async values=>{await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/assets/vendor/pdfjs/pdf.min.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script);});pdfjsLib.GlobalWorkerOptions.workerSrc='/assets/vendor/pdfjs/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:new Uint8Array(values)}).promise;const renders=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),viewport=page.getViewport({scale:1.5});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;renders.push(canvas.toDataURL());}return {pages:pdf.numPages,renders,height:window.__receiptCanvas.height,source:window.__receiptCanvas.toDataURL()};},Array.from(bytes));
 if(count===1)expect(result.pages).toBe(1);else expect(result.pages).toBeGreaterThan(1);const geometry=await page.evaluate(()=>window.__receiptGeometry);expect(geometry.width).toBeGreaterThan(700);for(const cell of geometry.cells)expect(cell.scroll).toBeLessThanOrEqual(cell.width+1);const parsed=await PDFDocument.load(bytes);let covered=0;const seen=new Set();const slices=[];for(const pdfPage of parsed.getPages()){const objects=pdfPage.node.Resources().lookup(PDFName.of("XObject"));const images=objects.entries().map(([,ref])=>parsed.context.lookup(ref)).filter(obj=>obj.dict.get(PDFName.of("Subtype")).toString()==="/Image");for(const image of images)if(!seen.has(image)){seen.add(image);slices.push(image);}}expect(slices).toHaveLength(result.pages);for(const image of slices){covered+=image.dict.get(PDFName.of("Height")).asNumber();if(covered<result.height)expect(geometry.rows.some(row=>row.top+1<covered&&row.bottom-1>covered)).toBe(false);}expect(covered).toBe(result.height);
 const folder=path.resolve(__dirname,'../../../receipt-template-evidence',locale+'-'+template);fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'receipt.pdf'),bytes);
 for(const [index,url]of [result.source,...result.renders].entries()){const name=index===0?'source.png':`page-${index}.png`;const image=Buffer.from(url.split(',')[1],'base64');fs.writeFileSync(path.join(folder,name),image);await info.attach(name,{body:image,contentType:'image/png'});}
 console.log(`${locale}/${template}: ${result.pages} pages saved ${folder}`);
});


