const {test,expect}=require('@playwright/test');const key='afro_sars_efiling_preparation_v1';
for(const v of [{lang:'en',route:'/tools/sars-efiling/',unsaved:'session'},{lang:'sw',route:'/sw/zana/mwongozo-wa-sars-efiling/',unsaved:'kipindi'}]){
 test(`${v.lang} preserves unreadable saved checklist through edits`,async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'{broken'),key);await page.goto(v.route);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe('{broken');await page.locator('[data-sars-task=domain]').click();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe('{broken');await expect(page.locator('#sarsWorkflowStatus')).toContainText(v.unsaved);});
 test(`${v.lang} reports a denied save and preserves failed reset state`,async({page})=>{await page.goto(v.route);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('synthetic')}});await page.locator('[data-sars-task=domain]').click();await expect(page.locator('#sarsWorkflowStatus')).toContainText(v.unsaved);await page.locator('#sarsReset').click();await expect(page.locator('[data-sars-task=domain]')).toHaveAttribute('aria-checked','true');});
}
const fs=require('node:fs');
for(const v of [{lang:'en',route:'/tools/sars-efiling/',portal:'Official portal'},{lang:'sw',route:'/sw/zana/mwongozo-wa-sars-efiling/',portal:'Tovuti rasmi'}]){
 test(`${v.lang} unreadable schema is preserved until explicit reset`,async({page})=>{await page.addInitScript(k=>{if(!sessionStorage.getItem('sars-fixture-set')){localStorage.setItem(k,JSON.stringify({version:9,tasks:{domain:true}}));sessionStorage.setItem('sars-fixture-set','1')}},key);await page.goto(v.route);expect(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).version).toBe(9);await page.locator('#sarsReset').click();await expect(page.locator('[data-sars-task=domain]')).toHaveAttribute('aria-checked','false');await expect(page.locator('[data-sars-task=domain]')).toBeFocused();expect(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).version).toBe(1);await page.locator('[data-sars-task=domain]').click();await page.reload();await expect(page.locator('[data-sars-task=domain]')).toHaveAttribute('aria-checked','true');});
 test(`${v.lang} storage read denial stays usable without unhandled errors`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(k=>{const original=Storage.prototype.getItem;Storage.prototype.getItem=function(name){if(name===k)throw Error('synthetic');return original.call(this,name)}},key);await page.goto(v.route);await page.locator('[data-sars-task=domain]').click();await expect(page.locator('[data-sars-task=domain]')).toHaveAttribute('aria-checked','true');expect(errors).toEqual([]);});
 test(`${v.lang} unsaved choices remain in local JSON TXT and PDF exports`,async({page},testInfo)=>{await page.goto(v.route);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('synthetic')}});await page.locator('[data-sars-task=domain]').click();async function download(format){const pending=page.waitForEvent('download');await page.locator(`[data-sars-export=${format}]`).click();return fs.readFileSync(await (await pending).path())}const json=JSON.parse(await download('json'));expect(json.tasks.find(t=>t.id==='domain').complete).toBe(true);expect(json.tasks).toHaveLength(6);const txt=(await download('txt')).toString('utf8');expect(txt).toContain(v.portal+': https://secure.sarsefiling.co.za/');expect(txt).toContain('[x] '+json.tasks[0].label);const pdfBytes=await download('pdf');fs.mkdirSync(testInfo.outputDir,{recursive:true});fs.writeFileSync(testInfo.outputPath(v.lang+'-preparation.pdf'),pdfBytes);await page.addScriptTag({url:'/assets/vendor/pdfjs/pdf.min.js'});const pdf=await page.evaluate(async base64=>{pdfjsLib.GlobalWorkerOptions.workerSrc='/assets/vendor/pdfjs/pdf.worker.min.js';const doc=await pdfjsLib.getDocument({data:Uint8Array.from(atob(base64),c=>c.charCodeAt(0))}).promise;const first=await doc.getPage(1);const content=await first.getTextContent();const result={text:content.items.map(item=>item.str).join(' '),numpages:doc.numPages};await doc.destroy();return result},pdfBytes.toString('base64'));expect(pdf.text).toContain('[x]');expect(pdf.text.replace(/\s+/g,' ')).toContain(json.disclaimer);expect(pdf.numpages).toBe(1);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBeNull();});
}
