const {test,expect}=require('@playwright/test'),fs=require('node:fs');
function eventsFromICS(text){const events=[];let event=null;for(const line of text.replace(/\r\n[ \t]/g,'').split(/\r?\n/)){if(line==='BEGIN:VEVENT'){expect(event).toBeNull();event={};}else if(line==='END:VEVENT'){expect(event).not.toBeNull();events.push(event);event=null;}else if(event){const colon=line.indexOf(':');expect(colon).toBeGreaterThan(0);event[line.slice(0,colon)]=line.slice(colon+1);}}expect(event).toBeNull();return events;}
for(const [locale,route]of [['en','/tools/leave-calculator/'],['fr','/fr/tools/calculateur-conges-pto/'],['sw','/sw/zana/kikokotoo-likizo/']])test(`${locale}: Senegal conditional annual allowance and native exports`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(route);const card=page.locator('#senegal-child-leave');await expect(card).toBeVisible();
 await card.locator('[name=assessment]').fill('2026-09-16');await card.locator('[name=children]').fill('2');await card.locator('[name=taken]').fill('3.5');
 for(const k of ['mother','service','age'])await card.locator('[name='+k+']').check();await card.locator('button[type=submit]').first().click();await expect(card.locator('[data-sn-result]')).not.toContainText(': 26');
 await card.locator('[name=rule]').check();await expect(card.locator('[data-sn-export=txt]')).toBeDisabled();await card.locator('button[type=submit]').first().focus();await page.keyboard.press('Enter');
 await expect(card.locator('[data-sn-result]')).toContainText(': 26');await expect(card.locator('[data-sn-result]')).toContainText(': 22.5');
 await card.locator('[name=start]').fill('2026-09-18');await card.locator('[name=days]').fill('3');await card.locator('[name=schedule]').selectOption('five');await card.locator('[name=exclusions]').fill('2026-09-21');await card.locator('[name=confirmed]').check();await card.locator('button[type=submit]').last().click();await expect(card.locator('[data-sn-calendar-result]')).toContainText('2026-09-23');await expect(card.locator('[data-sn-calendar-result]')).toContainText('2026-09-24');
 const calendar=page.waitForEvent('download');await card.locator('[data-sn-calendar-download]').click();const ics=fs.readFileSync(await(await calendar).path(),'utf8').replace(/\r\n /g,'');const events=eventsFromICS(ics);expect(events).toHaveLength(2);expect(events[0]['DTSTART;VALUE=DATE']).toBe('20260918');expect(events[0]['DTEND;VALUE=DATE']).toBe('20260924');expect(events[1]['DTSTART;VALUE=DATE']).toBe('20260924');expect(events[1]['DTEND;VALUE=DATE']).toBe('20260925');expect(events[0].UID).not.toBe(events[1].UID);expect(events[0].DESCRIPTION).toContain('L.148');expect(events[0].DESCRIPTION).toContain('22.5');expect(events[0].SUMMARY).toContain(locale==='fr'?'Sénégal':'Senegal');
 for(const ext of ['txt','csv','json','pdf']){const download=page.waitForEvent('download');await card.locator('[data-sn-export='+ext+']').click();const bytes=fs.readFileSync(await(await download).path());if(ext==='pdf'){const path=require('node:path').resolve(__dirname,'../../../leave-workflow-evidence/senegal-'+locale+'.pdf');fs.mkdirSync(require('node:path').dirname(path),{recursive:true});fs.writeFileSync(path,bytes);}const body=ext==='pdf'?(await require('pdf-parse')(bytes)).text:bytes.toString('utf8');expect(body).toContain('2026-09-16');expect(body).toContain('2026-09-24');expect(body).toContain('19.5');expect(body).toContain('22.5');expect(body).toContain('L.148');expect(body).toContain(locale==='fr'?'entrée en vigueur n’est pas vérifiée':locale==='sw'?'kuanza kwake kutumika hakujathibitishwa':'commencement has not been verified');if(ext==='json'){const data=JSON.parse(body);expect(data.result.inputs.children).toBe(2);expect(data.result.inputs.rule).toBe(true);expect(data.result.totalDays).toBe(26);}}
 const path=require('node:path').resolve(__dirname,'../../../leave-workflow-evidence/senegal-'+locale+'-mobile.png');fs.mkdirSync(require('node:path').dirname(path),{recursive:true});await card.screenshot({path});
 await card.locator('[name=days]').fill('24');await expect(card.locator('[data-sn-calendar-download]')).toBeDisabled();await card.locator('button[type=submit]').last().click();await expect(card.locator('[data-sn-calendar-download]')).toBeDisabled();
 await card.locator('[name=children]').fill('0');await card.locator('[name=taken]').fill('0');await card.locator('button[type=submit]').first().click();await expect(card.locator('[data-sn-result]')).toContainText(': 24');
 await card.locator('[name=children]').fill('-1');await expect(card.locator('[data-sn-result]')).toBeEmpty();await card.locator('button[type=submit]').first().click();await expect(card.locator('[data-sn-export=txt]')).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});expect(await page.evaluate(async()=> (await axe.run(document.querySelector('#senegal-child-leave'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}})).violations.map(v=>v.id))).toEqual([]);
});
test('Senegal PDF loading cannot export a stale allowance',async({page})=>{
 let release,arrived;const seen=new Promise(resolve=>arrived=resolve),gate=new Promise(resolve=>release=resolve);
 await page.route('**/assets/fonts/noto-sans/NotoSans-Regular.ttf',async route=>{arrived();await gate;await route.continue();});
 await page.goto('/fr/tools/calculateur-conges-pto/');const card=page.locator('#senegal-child-leave');await card.locator('[name=assessment]').fill('2026-09-16');for(const key of ['rule','service','age'])await card.locator('[name='+key+']').check();await card.locator('button[type=submit]').first().click();
 let downloads=0;page.on('download',()=>downloads++);await page.evaluate(()=>{const original=AfroTools.senegalLeaveReports.pdf;AfroTools.senegalLeaveReports.pdf=async options=>{try{return await original(options);}finally{window.snPdfFinished=true;}};});
 await card.locator('[data-sn-export=pdf]').click();await seen;await card.locator('[name=children]').fill('2');release();await expect.poll(()=>page.evaluate(()=>window.snPdfFinished)).toBe(true);expect(downloads).toBe(0);await expect(card.locator('[data-sn-export=pdf]')).toBeDisabled();await expect(card.locator('[data-sn-result]')).toBeEmpty();
});
