const chartFixture = process.env.AFROTOOLS_TEST_CHART_JS || require('node:path').resolve(__dirname, '../fixtures/chart-4.4.1-test-fixture.js');
const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),acorn=require('acorn');
test.use({trace:'off',video:'off',screenshot:'off'});
const root=path.resolve(__dirname,'../..'),bundleSource=fs.readFileSync(path.join(root,'scripts/bundle.js'),'utf8');
const declaration=acorn.parse(bundleSource,{ecmaVersion:'latest'}).body.find(node=>node.type==='VariableDeclaration'&&node.declarations.some(d=>d.id.name==='BUNDLE_DEFS')).declarations.find(d=>d.id.name==='BUNDLE_DEFS');
const files=vm.runInNewContext('('+bundleSource.slice(declaration.init.start,declaration.init.end)+')')['tool-page'];
// Source preview uses the bundle owner inputs. Artifact mode deliberately loads
// the served hashed bundle; production acceptance remains a separate gate.
const bundle=files.map(file=>fs.readFileSync(path.join(root,file),'utf8').replace(/;\s*export\s*\{[^}]*\}\s*;?/g,';').replace(/export\s*\{[^}]*\}\s*;?/g,'')).join(';\n');


for(const fault of ['missing-label','after-result'])test(`South Africa restore recovery: ${fault}`,async({page,baseURL})=>{
 test.setTimeout(45000);const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.name+': '+e.message.slice(0,100)));
 await page.route('**/*',r=>{if(!['GET','HEAD'].includes(r.request().method())){writes.push('write');return r.abort()}return new URL(r.request().url()).origin===new URL(baseURL).origin?r.continue():r.abort()});
 if (process.env.AFROTOOLS_TEST_PUBLISH_ARTIFACT !== '1') await page.route('**/assets/js/bundles/tool-page.*',r=>r.fulfill({contentType:'application/javascript',body:bundle}));
 await page.route('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js',r=>chartFixture?r.fulfill({contentType:'application/javascript',body:fs.readFileSync(chartFixture)}):r.continue());
 await page.goto('/south-africa/za-paye.html');const salary=page.locator('#salaryInput');await page.locator('#modeNet').click();await salary.focus();await salary.fill('123456');await page.locator('#ageGroup').selectOption('65to74');await page.locator('#retirementAmt').fill('4000');await page.locator('[data-tog=medical]').click();await page.locator('#medMembers').selectOption('3');await page.locator('.calc-btn').first().click();await page.locator('.per-btn').nth(1).click();await page.waitForTimeout(350);
 const original=await page.evaluate(()=>window.PAYE_CALC_SYNC_ADAPTER.buildPayload());expect(original.inputs.mode).toBe('net');expect(original.inputs.period).toBe('annual');expect(original.inputs.medMembers).toBe(3);
 await page.locator('#calcSaveName').fill('Synthetic original');await page.locator('#calcSaveBtn').click();await expect(page.locator('[data-action=load]')).toHaveCount(1);
 await page.locator('#modeGross').click();await salary.focus();await salary.fill('234567');await page.locator('#ageGroup').selectOption('75plus');await page.locator('#retirementAmt').focus();await page.locator('#retirementAmt').fill('5000');await page.locator('[data-tog=medical]').click();await page.locator('[data-tog=uif]').click();await page.locator('.calc-btn').first().click();await page.locator('.per-btn').first().click();await page.locator('#calcSaveName').fill('Synthetic unsaved');await page.locator('#calcSaveName').blur();await page.waitForTimeout(350);
 const snapshot=()=>({fields:['salaryInput','salarySlider','ageGroup','retirementAmt','medMembers','calcSaveName'].map(id=>document.getElementById(id).value),mode:MODE,period:PERIOD,medical:document.querySelector('[data-tog=medical]').className,uif:document.querySelector('[data-tog=uif]').className,medicalField:document.getElementById('medicalField').className,label:document.getElementById('inputLabel').textContent,rows:localStorage.getItem('afrotools-saved-'+window.PAYE_CALC_SYNC_CONFIG.storageSlug)});
 const before=await page.evaluate(snapshot);
 await page.evaluate(fault=>{window.__exports=0;window.AfroTools.pdf={generate:()=>window.__exports++};if(fault==='missing-label'){const node=document.getElementById('sliderVal'),marker=document.createComment('test');node.replaceWith(marker);window.__undoFault=()=>marker.replaceWith(node)}else{const node=document.getElementById('resAmount');Object.defineProperty(node,'textContent',{configurable:true,set(){throw Error('Synthetic rendering interruption')}});window.__undoFault=()=>{delete node.textContent}}},fault);
 await page.locator('[data-action=load]').click();await expect(page.locator('#calcSaveStatus')).toHaveAttribute('data-tone','warning');await page.evaluate(()=>window.__undoFault());expect(await page.evaluate(snapshot)).toEqual(before);
 expect(await page.evaluate(()=>window.PAYE_CALC_SYNC_ADAPTER.hasResult())).toBe(false);expect(await page.evaluate(()=>window.PAYE_CALC_SYNC_ADAPTER.buildPayload())).toBeNull();await expect(page.locator('#calcSaveBtn')).toBeDisabled();await expect(page.locator('#aiBtn')).toBeDisabled();await expect(page.locator('#resultsCard')).toBeHidden();await page.evaluate(()=>window.downloadPdf());expect(await page.evaluate(()=>window.__exports)).toBe(0);
 await page.locator('.calc-btn').first().click();await expect(page.locator('#calcSaveBtn')).toBeEnabled();const draft=await page.evaluate(()=>window.PAYE_CALC_SYNC_ADAPTER.buildPayload());expect(draft.inputs.salaryValue).toBe(234567);expect(draft.inputs.mode).toBe('gross');expect(draft.inputs.period).toBe('monthly');expect(draft.inputs.ageGroup).toBe('75plus');expect(draft.inputs.retirementAmount).toBe(5000);expect(draft.inputs.toggles.medical).toBe(false);
 await page.locator('[data-action=load]').click();await expect(page.locator('#calcSaveStatus')).toHaveAttribute('data-tone','info');const reopened=await page.evaluate(()=>window.PAYE_CALC_SYNC_ADAPTER.buildPayload());expect(reopened.inputs).toEqual(original.inputs);await expect(page.locator('#medicalField')).toBeVisible();expect(writes).toEqual([]);expect(errors).toEqual([]);
});
