const{test,expect}=require("@playwright/test");
const fs=require("node:fs"),path=require("node:path"),{execFileSync}=require("node:child_process");
async function artifact(page,kind){const[d]=await Promise.all([page.waitForEvent("download"),page.locator(`[data-swb-export="${kind}"]`).click()]),file=await d.path();return{file,buffer:fs.readFileSync(file)}}
test("native Swahili borehole flow proves legacy oracle exports and privacy",async({page})=>{
  const errors=[],requests=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error"&&!/ERR_FAILED/.test(m.text()))errors.push(m.text())});page.on("request",r=>requests.push(r.url()+" "+(r.postData()||"")));
  await page.route(/^https?:\/\/(?!127\.0\.0\.1:43157)/,r=>r.abort());await page.goto("/sw/zana/gharama-za-kisima/");
  for(const[width,size]of[[320,"100%"],[375,"100%"],[640,"200%"]]){await page.setViewportSize({width,height:900});await page.evaluate(s=>document.documentElement.style.fontSize=s,size);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)}
  await page.evaluate(()=>document.documentElement.style.fontSize="");await page.getByRole("button",{name:"Kokotoa makisio"}).click();await expect(page.locator("#swbMetrics")).toContainText("NGN 1,732,000");
  const json=await artifact(page,"json"),record=JSON.parse(json.buffer.toString("utf8"));expect(record.result.stale).toBe(true);await page.locator("#swbImport").setInputFiles({name:"borehole.json",mimeType:"application/json",buffer:json.buffer});await expect(page.locator("#swbStatus")).toContainText("imefunguliwa");
  expect((await artifact(page,"csv")).buffer.toString("utf8")).toContain('"jumla","1732000","NGN"');expect((await artifact(page,"txt")).buffer.toString("utf8")).toContain("uhakika ni mdogo");const pdf=await artifact(page,"pdf");expect(pdf.buffer.subarray(0,4).toString()).toBe("%PDF");expect(JSON.parse(execFileSync(process.execPath,[path.resolve(__dirname,"../support/parse-pdf-download.js"),pdf.file],{encoding:"utf8"})).numpages).toBeGreaterThan(0);
  await page.getByRole("button",{name:"Weka upya"}).click();await page.locator("#swbDepth").fill("0");await page.getByRole("button",{name:"Kokotoa makisio"}).click();await expect(page.locator("#swbError")).toBeVisible();await expect(page.locator("#swbResult")).toBeHidden();const light=await page.locator("body").evaluate(el=>getComputedStyle(el).backgroundColor);await page.evaluate(()=>document.documentElement.classList.add("dark"));expect(await page.locator("body").evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(light);await page.locator("#swbCountry").focus();await page.keyboard.press("Tab");await expect(page.locator("#swbDepth")).toBeFocused();expect(errors).toEqual([]);expect(requests.join(" ")).not.toContain("borehole.json")
});
test("English route shares the exact legacy engine",async({page})=>{const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.route(/^https?:\/\/(?!127\.0\.0\.1:43157)/,r=>r.abort());page.on("dialog",d=>d.accept());await page.goto("/tools/borehole-cost/");expect(await page.evaluate(()=>Boolean(window.BoreholeCostEngine&&window.BoreholeCostEngine.estimate))).toBe(true);await page.getByRole("button",{name:"Estimate Cost"}).click();await expect(page.locator("#resultCard")).toBeVisible();await expect(page.locator("#resultGrid")).toContainText("NGN 1,732,000");expect(errors).toEqual([])});
test("metadata artwork and reciprocal hreflang are exact",async({page})=>{for(const route of["/tools/borehole-cost/","/fr/tools/cout-forage/","/sw/zana/gharama-za-kisima/"]){await page.goto(route);await expect(page.locator('link[rel="alternate"][hreflang="sw"]')).toHaveAttribute("href","https://afrotools.com/sw/zana/gharama-za-kisima/")}await page.goto("/sw/zana/gharama-za-kisima/");await expect(page.locator('meta[property="og:image"]')).toHaveAttribute("content",/borehole-cost\.webp$/);expect(await page.locator('script[type="application/ld+json"]').evaluateAll(nodes=>nodes.map(n=>JSON.parse(n.textContent)).some(x=>x["@type"]==="WebApplication"&&x.inLanguage==="sw"))).toBe(true)});
