const {test,expect}=require('@playwright/test'),fs=require('fs');
test('SW fuel kg workflow, exact reports, stale references and mobile layout',async({page,baseURL},info)=>{
 const today=new Date().toISOString().slice(0,10),row=(code,date)=>({code,name:code,currency:'TZS',last_updated:date,source_url:'https://example.org/source',official_verified:false,petrol:{price:2500,usd:1},diesel:{price:2400,usd:1},lpg:{price:2500,usd:1}});
 await page.route('**/data/fuel/latest.json',r=>r.fulfill({json:{countries:[row('TZ',today),row('TN','2000-01-01'),row('KE','2999-01-01'),{...row('UG',today),source_url:''}]}}));
 await page.setViewportSize({width:390,height:844});await page.goto('/sw/zana/ufuatiliaji-bei-za-mafuta/');
 await page.locator('#fuelType').selectOption('LPG');await expect(page.getByLabel('Kilogramu kwa mwezi')).toBeVisible();await expect(page.locator('#currentPrice')).toHaveValue('');
 await page.locator('#snapshot-country').selectOption('TN');await expect(page.locator('#snapshot-use')).toBeDisabled();await expect(page.locator('#snapshot-status')).not.toContainText('2500');
 for(const code of ['KE','UG']){await page.locator('#snapshot-country').selectOption(code);await expect(page.locator('#snapshot-use')).toBeDisabled();}
 await page.locator('#snapshot-country').selectOption('TZ');await page.locator('#snapshot-use').click();await expect(page.locator('#currency')).toHaveValue('TZS');await page.locator('#previousPrice').fill('2400');await page.locator('#litresMonth').fill('12.5');await page.locator('#officialLag').fill('3');await page.locator('#sw-fuel-form button[type=submit]').focus();await page.keyboard.press('Enter');await expect(page.locator('#fuel-result')).toContainText('31,250');
 for(const kind of ['txt','json']){const pending=page.waitForEvent('download');await page.locator('#fuel-'+kind).click();const text=fs.readFileSync(await(await pending).path(),'utf8');if(kind==='json'){const d=JSON.parse(text);expect(d.result.monthlyCost).toBe(31250);expect(d.result.monthlyChange).toBe(1250);expect(d.result.unit).toBe('kg');expect(d.result.inputs.litresMonth).toBe(12.5);}else{expect(text).toContain('Kipimo: kg');expect(text).toContain('31,250');expect(text).not.toContain('Lita');}}
 await page.locator('#currentPrice').fill('0');await expect(page.locator('#fuel-json')).toBeDisabled();await page.locator('#sw-fuel-form button[type=submit]').click();await expect(page.locator('#fuel-result')).toContainText('0 TZS');await page.locator('#currentPrice').fill('-1');await expect(page.locator('#fuel-json')).toBeDisabled();await page.locator('#fuelType').selectOption('Diesel');await expect(page.getByLabel('Lita kwa mwezi')).toBeVisible();await expect(page.locator('#litresMonth')).toHaveValue('');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('sw-fuel-390.png')});
});
