'use strict';
const assert = require('assert');
const authPath = require.resolve('../netlify/functions/_shared/api-auth');
const apiPath = require.resolve('../netlify/functions/_shared/market-data-api');
const functionPath = require.resolve('../netlify/functions/api-salary-intelligence');
const calls = [];
require.cache[authPath] = { id:authPath, filename:authPath, loaded:true, exports:{ validateApiKey:async()=>({tier:'free'}) } };
require.cache[apiPath] = { id:apiPath, filename:apiPath, loaded:true, exports:{ buildHeaders:()=>({'Content-Type':'application/json'}), jsonResponse:(statusCode,body,headers)=>({statusCode,headers,body:JSON.stringify(body)}), queryRows:async path=>{calls.push(path);return[{country_code:'KE',city:'Nairobi',monthly_gross:100000,observed_at:'2026-07-20'}];} } };
delete require.cache[functionPath];
const handler = require(functionPath).handler;
(async function(){
  assert.equal((await handler({httpMethod:'OPTIONS'})).statusCode,204);
  assert.equal((await handler({httpMethod:'POST'})).statusCode,405);
  const response=await handler({httpMethod:'GET',queryStringParameters:{country:'ke',freshness_days:'90',limit:'500'}});
  const body=JSON.parse(response.body);
  assert.equal(response.statusCode,200);
  assert.equal(body.filters.country,'KE');
  assert.equal(body.filters.freshness_days,90);
  assert.equal(body.benchmarks_withheld,true);
  assert.equal(body.amounts_withheld,true);
  assert.deepEqual(body.benchmarks,[]);
  assert.equal(body.reports.length,1);
  assert.equal(calls.length,1);
  assert.ok(calls[0].includes('select=country_code,city,observed_at'));
  assert.ok(calls[0].includes('verification_state=eq.verified'));
  assert.ok(calls[0].includes('review_status=eq.approved'));
  assert.ok(calls[0].includes('confidence_score=gte.0.6'));
  assert.ok(calls[0].includes('observed_at=gte.'));
  assert.ok(!/proof_url|photo_url|payload|user_id|contribution_id/.test(calls[0]));
  assert.ok(!/monthly_gross|monthly_net|total_cash_comp/.test(calls[0]));
  assert.ok(!calls[0].includes('limit=500'));
  console.log('api-salary-intelligence-safety: 18 assertions passed');
})().catch(error=>{console.error(error);process.exit(1);});
