const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const fixture=require('./fixtures/cv-complete-form');
function runtime(lang){const document={documentElement:{lang},readyState:'loading',addEventListener(){},getElementById(){return null;},querySelector(){return null;}};const ctx={document,console,CVApp:{esc:s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;')}};ctx.window={...ctx,CVTemplates:{}};vm.createContext(ctx);vm.runInContext('const CVTemplates={slate:()=>"LEGACY_FALLBACK"};',ctx);for(const f of ['cv-pdf-templates','cv-template-registry','cv-template-expanded-renderers','cv-template-registry-expanded'])vm.runInContext(fs.readFileSync('tools/cv-builder/js/'+f+'.js','utf8'),ctx,{filename:f});return ctx;}
for(const lang of ['en','fr','sw'])test('actual load order unifies all30 bindings and preserves saved fields: '+lang,()=>{const ctx=runtime(lang),rows=ctx.window.CVTemplateRegistry.all(),before=JSON.stringify(fixture);assert.equal(rows.length,30);for(const row of rows){assert.equal(ctx.window.CVTemplates[row.id],row.previewRenderer,row.id);assert.equal(vm.runInContext('CVTemplates',ctx),ctx.window.CVTemplates);const html=row.previewRenderer(fixture,'NG');for(const marker of ['QZAltX','QZWebX','QZGitX','QZPortfolioX','QZEduDetailX','QZGradeX','QZProjectX','QZProjectURLX','QZTechX','QZProjectDetailX','QZCertX','QZIssuerX','QZLanguageX','QZLevelX','QZRefX','QZRelationshipX','QZHobbyX','QZMemberX','QZCustomContentX','QZSkill29X'])assert.ok(html.includes(marker),row.id+' '+marker);assert.ok(!html.includes('LEGACY_FALLBACK'));const hidden=row.previewRenderer({...fixture,showProjs:false,showRefs:false,showPhoto:false,sp:false},'NG');for(const marker of ['QZProjectX','QZRefX','QZNationalityX'])assert.ok(!hidden.includes(marker),row.id+' hidden '+marker);assert.ok(!hidden.includes('<img'));}assert.equal(JSON.stringify(fixture),before);});
test('native headings and current dates preserve user content',()=>{for(const[lang,heading,current]of [['en','Work Experience','Present'],['fr','Expérience professionnelle','Aujourd’hui'],['sw','Uzoefu wa kazi','Sasa']]){const ctx=runtime(lang),data={...fixture,exps:[{t:'Profile',c:'Experience',cur:true,d:'Education'}]};const html=ctx.window.CVTemplates['ats-plain'](data,'KE');assert.ok(html.includes('>'+heading+'</h2>'));assert.ok(html.includes(current));assert.ok(html.includes('>Profile</strong>'));assert.ok(html.includes('>Education</li>'));}});

test('partial rows and independent legacy hobbies survive normalization',()=>{const ctx=runtime('en'),data={showProjs:true,showRefs:true,edus:[{d:'OnlyEducationDetail'}],projs:[{url:'OnlyProjectURL'}],certs:[{i:'OnlyIssuer'}],langs:[{lv:'OnlyLevel'}],refs:[{e:'OnlyReferenceEmail'}],extras:{hobbies:'CurrentHobbies',interests:'LegacyInterests'}};for(const row of ctx.window.CVTemplateRegistry.all()){const html=row.previewRenderer(data,'KE','#123456');for(const value of ['OnlyEducationDetail','OnlyProjectURL','OnlyIssuer','OnlyLevel','OnlyReferenceEmail','CurrentHobbies','LegacyInterests'])assert.ok(html.includes(value),row.id+' '+value);if(html.includes('cv-expanded-template'))assert.ok(html.includes('--cvx-accent:#123456;'),row.id+' accent');}});

test('all advertised renderers own native generated section headings',()=>{const en=runtime('en');for(const lang of ['fr','sw']){const ctx=runtime(lang);for(const row of ctx.window.CVTemplateRegistry.all()){const headings=html=>[...html.matchAll(/<h2[^>]*>([^<]+)<\/h2>/g)].map(m=>m[1]);const english=new Set(headings(en.window.CVTemplates[row.id](fixture,'NG'))),native=headings(row.previewRenderer(fixture,'NG'));assert.ok(native.length>3,row.id);const allowed=new Set(lang==='fr'?['Certifications','Service','Profil professionnel','Formation','Projets','QZCustomTitleX']:['QZCustomTitleX']);for(const text of native)assert.ok(!english.has(text)||allowed.has(text),lang+' '+row.id+' '+text);}}});

test('semantic section identity covers all templates and excludes user headings',()=>{for(const lang of ['en','fr','sw']){const ctx=runtime(lang);for(const row of ctx.window.CVTemplateRegistry.all()){const html=row.previewRenderer({...fixture,customSections:[{title:'Education',content:'USERCUSTOMBREAKMARKER'}]},'NG');for(const kind of ['experience','education','projects','references'])assert.ok(html.includes('data-cv-section="'+kind+'"'),lang+' '+row.id+' '+kind);assert.match(html,/<section[^>]*data-cv-section="custom"[^>]*>[\s\S]*?USERCUSTOMBREAKMARKER/);}}});

test('Nairobi static decoration is native while user literal stays unchanged',()=>{for(const [lang,decoration]of [['en','candidate.profile'],['fr','profil.candidat'],['sw','wasifu.wa.mwombaji']]){const ctx=runtime(lang),html=ctx.window.CVTemplates['nairobi-tech']({...fixture,customSections:[{title:'candidate.profile',content:'USERDECORATIONBOUNDARY'}]},'NG');const header=html.match(/<header[\s\S]*?<\/header>/)[0];assert.ok(header.includes(decoration));assert.ok(html.includes('candidate.profile'));assert.ok(html.includes('USERDECORATIONBOUNDARY'));}});
