const {test}=require('node:test'),assert=require('node:assert/strict');const api=require('../tools/cv-builder/js/cv-json-backup');
const backup={version:1,source:'afrotools-cv-builder',country:'KE',template:'lagos-corporate',accentHex:'#123456',accentColor:'#123456',data:{fn:'Élodie',ln:'François Łukasz',skills:{h:'Évaluation'},exps:[{t:'Mhandisi',cur:true}],edus:[{deg:'Maîtrise'}],langs:[{l:'Kiswahili',lv:'Fasaha'}],refs:[{n:'Asha Mwang’ombe'}]}};
function env(fail){const map=new Map([['afro_cv_data','old draft']]);return{state:{data:{fn:'Old'},country:'NG',template:'ats-plain'},storage:{getItem:k=>map.has(k)?map.get(k):null,setItem(k,v){if(k===fail)throw Error('quota');map.set(k,v);},removeItem:k=>map.delete(k)},hasTemplate:id=>id==='lagos-corporate',id:'synthetic',title:'Restored',clearTimer(){},map};}
test('backup restores exact content as separate local version',()=>{const e=env(),old=e.state.data;api.restore(backup,e);assert.deepEqual(e.state.data,backup.data);assert.equal(e.state.accentHex,backup.accentHex);assert.equal(old.fn,'Old');const store=JSON.parse(e.map.get('afro_cv_master_versions_v1'));assert.equal(store.master.data.fn,'Old');assert.deepEqual(store.versions[0].data,backup.data);assert.deepEqual(JSON.parse(e.map.get('afro_cv_data')).data,backup.data);});
for(const [name,text]of [['syntax','{'],['version',JSON.stringify({...backup,version:2})],['source',JSON.stringify({...backup,source:'other'})],['prototype',JSON.stringify(backup).replace('"fn":"Élodie"','"__proto__":{"polluted":true}')],['constructor',JSON.stringify(backup).replace('"fn":"Élodie"','"constructor":{}')],['array',JSON.stringify({...backup,data:{...backup.data,exps:{}}})],['remote photo',JSON.stringify({...backup,data:{...backup.data,photo:'https://example.test/photo.jpg'}})]])test('rejects '+name+' before mutation',()=>{const e=env(),before=JSON.stringify(e.state);assert.throws(()=>api.restore(api.validate(text),e));assert.equal(JSON.stringify(e.state),before);assert.equal(e.map.get('afro_cv_data'),'old draft');assert.equal({}.polluted,undefined);});
test('storage failure rolls back and preserves current state',()=>{const e=env('afro_cv_master_versions_v1');assert.throws(()=>api.restore(backup,e),/STORAGE/);assert.equal(e.state.data.fn,'Old');assert.equal(e.map.get('afro_cv_data'),'old draft');});
test('rejects wrong field types and unknown metadata before mutation',()=>{for(const data of [{...backup.data,fn:{}},{...backup.data,skills:{h:{}}},{...backup.data,exps:[{d:{}}]}])assert.throws(()=>api.validate(JSON.stringify({...backup,data})));const e=env();e.hasCountry=()=>false;assert.throws(()=>api.restore(backup,e));assert.equal(e.state.data.fn,'Old');});
test('keeps existing named versions on restore',()=>{const e=env();e.map.set('afro_cv_master_versions_v1',JSON.stringify({schema:1,master:{id:'master',data:{fn:'Master'}},versions:[{id:'existing',data:{fn:'Existing'}}]}));api.restore(backup,e);const store=JSON.parse(e.map.get('afro_cv_master_versions_v1'));assert.equal(store.master.data.fn,'Master');assert.equal(store.versions[1].data.fn,'Existing');});
test('French backup guidance preserves accents',()=>{assert.equal(api.labels('fr').review,'Vérifier la sauvegarde JSON');assert.equal(api.labels('fr').invalid,'Cette sauvegarde de CV n’est pas prise en charge. Vérifiez le fichier et réessayez.');});
