"use strict";
const assert=require("assert");
const engine=require("../engines/src/forex-profit-statement-engine.js");
const base={baseCurrency:"AAA",quoteCurrency:"BBB",reportingCurrencyUnit:"CCC",direction:"buy",entryPrice:1.2,exitPrice:1.21,baseUnits:10000,pipSize:.0001,quoteToReportingRate:2,transactionCostsQuote:5};
const near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);
const buy=engine.calculate(base);
near(buy.signedPriceMoveQuotePerBase,.01);
near(buy.signedPips,100);
near(buy.pipValueQuote,1);
near(buy.grossPnlQuote,100);
near(buy.netPnlQuote,95);
near(buy.netPnlReporting,190);
near(buy.transactionCostsReporting,10);
near(buy.openingNotionalQuote,12000);
const sell=engine.calculate({...base,direction:"sell",exitPrice:1.19});
near(sell.grossPnlQuote,100);
const losing=engine.calculate({...base,exitPrice:1.19});
near(losing.grossPnlQuote,-100);
near(losing.netPnlQuote,-105);
assert.ok(losing.netPnlReporting<0);
const breakEven=engine.calculate({...base,exitPrice:1.2,transactionCostsQuote:0});
near(breakEven.netPnlQuote,0);
const conversion=engine.calculate({...base,quoteToReportingRate:.5});
near(conversion.netPnlReporting,47.5);
assert.throws(()=>engine.calculate({...base,transactionCostsQuote:-1}),/INVALID_NUMBER/);
assert.throws(()=>engine.calculate({...base,pipSize:0}),/INVALID_NUMBER/);
assert.throws(()=>engine.calculate({...base,quoteToReportingRate:0}),/INVALID_NUMBER/);
assert.throws(()=>engine.calculate({...base,baseUnits:1e308}),/INVALID_NUMBER/);
assert.throws(()=>engine.calculate({...base,baseCurrency:"=BAD"}),/BASE_REQUIRED|INVALID/);
assert.throws(()=>engine.calculate({...base,direction:"hold"}),/INVALID_DIRECTION/);
console.log("forex-profit-statement-engine: ok");
