'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const manifest=require('../data/localization/fr-agriculture-parity-manifest.json'),ai=require('../assets/js/ai/french-route-map.generated.js'),engine=require('../engines/src/pesticide-dosage-engine');
const{ROOT,assertNativeFrenchOutput}=require('../scripts/lib/fr-agriculture-parity-manifest');
const row=manifest.rows.find(item=>item.english.id==='pesticide-dosage-calculator');assert.ok(row);assertNativeFrenchOutput(manifest,[row.french.route]);
const html=fs.readFileSync(path.join(ROOT,row.french.file),'utf8');assert.doesNotMatch(html,/<iframe\b/i);assert.doesNotMatch(html,/\bfetch\s*\(/i);assert.match(html,/<html\b[^>]*\blang="fr"/);assert.match(html,/pesticide-data\.js/);assert.match(html,/pesticide-dosage-engine\.js/);assert.match(html,/Exporter en PDF/);assert.match(html,/aucune saisie envoyée à un serveur/i);assert.equal(ai.routes[row.english.routeKey],row.french.routeKey);
const context={window:{}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'data/agriculture/pesticide-data.js'),'utf8'),context);const data=context.window.PesticideData,profiles=[];
for(const [type,products] of Object.entries({herbicide:data.herbicides,insecticide:data.insecticides,fungicide:data.fungicides})){for(const product of products){for(const sprayerKey of Object.keys(data.sprayers)){const input={kind:'spray',rate:(product.rateMin+product.rateMax)/2,unitLabel:product.unit+'/ha',areaHa:2.75,sprayerKey,sprayerDefaults:{knapsack:{water:250},motorized:{water:175},boom:{water:150}},waterPerHa:0,pricePerUnit:1500,currency:'XOF',reentryHours:product.reentryHours,preHarvestDays:product.phiDays},output=engine.calculate(input,data);assert.equal(output.ok,true);profiles.push({type,productId:product.id,sprayerKey,input,output})}}}
for(const product of data.seedTreatments){const input={kind:'seed-treatment',rate:(product.rateMin+product.rateMax)/2,unit:product.unit,seedKg:125,reentryHours:product.reentryHours,preHarvestDays:product.phiDays},output=engine.calculate(input,data);assert.equal(output.ok,true);profiles.push({type:'seed_treatment',productId:product.id,input,output})}
const oracle={schemaVersion:1,family:'singleton:pesticide-dosage-calculator',products:data.herbicides.length+data.insecticides.length+data.fungicides.length+data.seedTreatments.length,profiles};if(process.env.FR_AGRI_ORACLE_OUTPUT)fs.writeFileSync(path.resolve(ROOT,process.env.FR_AGRI_ORACLE_OUTPUT),JSON.stringify(oracle,null,2)+'\n','utf8');console.log(JSON.stringify({family:oracle.family,rows:1,products:oracle.products,profiles:profiles.length},null,2));
