'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const manifest=require('../data/localization/fr-agriculture-parity-manifest.json'),ai=require('../assets/js/ai/french-route-map.generated.js');
const{ROOT,assertNativeFrenchOutput}=require('../scripts/lib/fr-agriculture-parity-manifest');
const row=manifest.rows.find(item=>item.english.id==='coffee-calculator');assert.ok(row);assertNativeFrenchOutput(manifest,[row.french.route]);const html=fs.readFileSync(path.join(ROOT,row.french.file),'utf8');assert.doesNotMatch(html,/<iframe\b/i);assert.doesNotMatch(html,/\bfetch\s*\(/i);assert.match(html,/<html\b[^>]*\blang="fr"/);assert.match(html,/coffee-data\.js/);assert.match(html,/coffee-engine\.js/);assert.match(html,/Exporter en PDF/);assert.match(html,/aucune saisie envoyée à un serveur/i);assert.equal(ai.routes[row.english.routeKey],row.french.routeKey);
const context={window:{}};vm.createContext(context);for(const file of['data/agriculture/coffee-data.js','engines/src/coffee-engine.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context,{filename:file});const data=context.COFFEE_DATA,engine=context.window.AfroTools.CoffeeEngine,profiles=[];
for(const[countryCode,country]of Object.entries(data.gradingSystems)){for(const grade of country.grades){assert.ok(engine.gradeInfo(countryCode,grade.grade));for(const species of country.species)for(const yieldLevel of Object.keys(data.agronomy[species].yieldPerTree_kg_cherry))for(const processingMethod of Object.keys(data.processingCosts)){const input={countryCode,species,treesPerHa:data.agronomy[species].treesPerHa.semi_intensive,yieldLevel,processingMethod,gradeId:grade.grade,farmHa:2.5,regionIdx:0},output=engine.calcYield(input);assert.ok(output);profiles.push({mode:'yield',input,output})}}for(const current of country.grades)for(const target of country.grades){const output=engine.qualityImprovement(countryCode,current.grade,target.grade,2);assert.ok(output);profiles.push({mode:'quality',input:{countryCode,current:current.grade,target:target.grade,farmHa:2},output})}}
for(const species of Object.keys(data.agronomy))for(const method of Object.keys(data.processingCosts))for(const cherryKg of[10,5000,1000000]){const output=engine.processingCost(cherryKg,method,species);assert.ok(output);profiles.push({mode:'processing',input:{cherryKg,method,species},output})}
const oracle={schemaVersion:1,family:'singleton:coffee-calculator',countries:Object.keys(data.gradingSystems),profiles};if(process.env.FR_AGRI_ORACLE_OUTPUT)fs.writeFileSync(path.resolve(ROOT,process.env.FR_AGRI_ORACLE_OUTPUT),JSON.stringify(oracle,null,2)+'\n','utf8');console.log(JSON.stringify({family:oracle.family,rows:1,countries:oracle.countries.length,profiles:profiles.length},null,2));
