'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const checker=require('../ops/jamb/verification/check-english-2023-1001.cjs');
const importer=require('../ops/nigeria-exams/import-jamb-english-2023-batch-01.cjs');
const trust=require('../scripts/lib/jamb-content-trust.js');
const root=path.resolve(__dirname,'..');
function fixture(){const bytes=Object.fromEntries([['manifest',checker.manifestPath],['snapshot',checker.snapshotPath],['review',checker.reviewPath]].map(([k,p])=>[k,fs.readFileSync(path.join(root,p))]));return {m:JSON.parse(bytes.manifest),s:JSON.parse(bytes.snapshot),r:JSON.parse(bytes.review),p:JSON.parse(fs.readFileSync(path.join(root,'ops/jamb/source-pool.json'))),l:JSON.parse(fs.readFileSync(path.join(root,'data/jamb/review-ledger.json'))),receipt:JSON.parse(fs.readFileSync(path.join(root,checker.receiptPath))),bytes};}
function verify(f){return checker.verify(f.m,f.s,f.r,f.p,f.l,f.receipt,f.bytes);}
test('actual frozen 13 records independently verified, eligible, with unknown sitting and numbering',()=>{const f=fixture();assert.equal(verify(f).accepted,13);for(const id of checker.ACCEPTED){const q=f.p.questions.find(q=>q.id==='english-2023-myschool-'+id);assert.equal(q.num,null);assert.equal(trust.assessQuestion(q,f.l).state,'eligible');assert.equal(Object.keys(q.options).length,4);}});
test('native preparation is idempotent and preserves every existing record and review',()=>{const f=fixture(),p=JSON.stringify(f.p),l=JSON.stringify(f.l);const a=importer.prepareBatch(f.m,f.s,f.r,f.p,f.l,{bytes:f.bytes,implementationBase:f.receipt.implementation_base_sha});assert.equal(JSON.stringify(a.pool),p);assert.equal(JSON.stringify(a.ledger),l);assert.equal(JSON.stringify(f.p),p);assert.equal(JSON.stringify(f.l),l);});
test('changed source prompt, ordered choices, target, year, or independent answer reject even with resealed input bytes',()=>{for(const mutate of [f=>f.s.records[0].question_text+=' changed',f=>f.m.records[0].choices.reverse(),f=>f.s.records[1].targeted_text=[],f=>f.s.records[0].collection_metadata.exam_year=2024,f=>f.r.records[0].answer='A']){const f=fixture();mutate(f);f.bytes={manifest:Buffer.from(JSON.stringify(f.m)),snapshot:Buffer.from(JSON.stringify(f.s)),review:Buffer.from(JSON.stringify(f.r))};assert.throws(()=>verify(f));}});
test('changed installed answer rejects even if pool, ledger and receipt question digests are recomputed',()=>{const f=fixture(),q=f.p.questions.find(q=>q.id==='english-2023-myschool-67322');q.answer='A';const h=trust.questionFingerprint(q);f.l.questions[q.id].content_sha256=h;const row=f.receipt.records.find(r=>r.id===q.id);row.content_sha256=h;row.answer='A';assert.throws(()=>verify(f));});
test('exact duplicate and substantive stem duplicates remain rejected; short choice-dependent instructions distinguish tasks',()=>{const a={question:'Choose the word that does not have the same vowel sound as the others',options:{A:'a',B:'b',C:'c',D:'d'}};assert(importer.duplicateQuestion(a,structuredClone(a)));assert(importer.duplicateQuestion(a,{...a,options:{A:'d',B:'c',C:'b',D:'a'}}));const b={question:'Pick the word',options:a.options},c={question:b.question,options:{A:'e',B:'f',C:'g',D:'h'}};assert.equal(importer.duplicateQuestion(b,c),false);assert.equal(importer.duplicateQuestion(a,{...a,options:c.options}),false);const spelling={question:'Choose the option with the correct spelling from the options lettered A-E',options:{A:'interpret',B:'interprate',C:'interprite',D:'interpritt',E:'interprat'}};assert.equal(importer.duplicateQuestion(spelling,{...spelling,options:{A:'successful',B:'succesful',C:'sucessful',D:'successfull',E:'sucessfull'}}),false);assert(importer.duplicateQuestion(spelling,{...spelling,options:{A:'interprat',B:'interpritt',C:'interprite',D:'interprate',E:'interpret'}}));const long={question:'A substantive sentence with sufficient context to remain a real duplicate despite different choices',options:a.options};assert(importer.duplicateQuestion(long,{...long,options:c.options}));});
