'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const checker=require('../ops/jamb/verification/check-english-2024-904.cjs');
const referenceRoot=process.env.AFROTOOLS_REFERENCE_REPO || path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(referenceRoot,p)));
const pool=read('ops/jamb/source-pool.json'),ledger=read('data/jamb/review-ledger.json');
const bytes=Object.fromEntries([['manifest',checker.manifestPath],['snapshot',checker.snapshotPath],['review',checker.reviewPath]].map(([key,p])=>[key,fs.readFileSync(path.join(referenceRoot,p))]));
const [m,s,r]=['manifest','snapshot','review'].map(k=>JSON.parse(bytes[k]));const receipt=read(checker.receiptPath);
function historical(p=pool,l=ledger,root=referenceRoot){return checker.verify(m,s,r,p,l,receipt,bytes,{referenceRoot:root});}
function fixture(change){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'afrotools-held-recovery-'));const later=require(path.join(referenceRoot,'ops/jamb/verification/check-english-2024-1001.cjs'));const paths=[later.manifestPath,later.snapshotPath,later.reviewPath,later.receiptPath,'ops/jamb/verification/check-english-2024-1001.cjs','scripts/lib/jamb-content-trust.js','scripts/lib/jamb-visual-assets.js'];for(const p of paths){fs.mkdirSync(path.dirname(path.join(dir,p)),{recursive:true});fs.copyFileSync(path.join(referenceRoot,p),path.join(dir,p));}try{return change(dir,later);}finally{assert(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));assert(path.basename(dir).startsWith('afrotools-held-recovery-'));fs.rmSync(dir,{recursive:true,force:true});}}
test('all five genuine later recoveries verify and historical nine accepted are unchanged',()=>{assert.deepEqual(checker.verifyLaterRecoveries(pool,ledger,{referenceRoot}),[70064,70066,70067,70070,70083]);const result=historical();assert.equal(result.accepted,9);assert.deepEqual(result.question_ids,checker.ACCEPTED.map(id=>'english-2024-myschool-'+id));assert.equal(result.held_or_excluded,checker.HELD.length);});
test('historical baseline without recoveries needs no later artifacts',()=>{const p=structuredClone(pool);p.questions=p.questions.filter(q=>!checker.LATER_RECOVERIES.some(id=>q.id==='english-2024-myschool-'+id));assert.deepEqual(checker.verifyLaterRecoveries(p,ledger,{referenceRoot:path.join(os.tmpdir(),'nonexistent-later-artifacts')}),[]);assert.equal(historical(p).accepted,9);});
test('unlisted historical held source item still rejects',()=>{const p=structuredClone(pool);p.questions.push({...p.questions.find(q=>q.id==='english-2024-myschool-70064'),id:'english-2024-myschool-70056'});assert.throws(()=>historical(p),/unlisted historical held/);});
test('wrong later key rejects even if question fingerprints are resealed',()=>{const p=structuredClone(pool),l=structuredClone(ledger),id='english-2024-myschool-70064';p.questions.find(q=>q.id===id).answer='B';const trust=checker.trustFor(referenceRoot);l.questions[id].content_sha256=trust.questionFingerprint(p.questions.find(q=>q.id===id));assert.throws(()=>historical(p,l),/independently selected answer/);});
test('modified later review cannot pass by recomputing its receipt hash',()=>fixture((dir,later)=>{let j=JSON.parse(fs.readFileSync(path.join(dir,later.reviewPath)));j.records[0].distractor_review.B='guessed';let b=Buffer.from(JSON.stringify(j,null,2)+'\n');fs.writeFileSync(path.join(dir,later.reviewPath),b);let t=JSON.parse(fs.readFileSync(path.join(dir,later.receiptPath)));t.independent_review_sha256=crypto.createHash('sha256').update(b).digest('hex');fs.writeFileSync(path.join(dir,later.receiptPath),JSON.stringify(t,null,2)+'\n');assert.throws(()=>historical(pool,ledger,dir),/frozen/);}));
test('missing later snapshot or receipt rejects',()=>{for(const field of ['snapshotPath','receiptPath'])fixture((dir,later)=>{fs.unlinkSync(path.join(dir,later[field]));assert.throws(()=>historical(pool,ledger,dir),/ENOENT/);});});
test('noneligible and relabelled later source owner reject',()=>{const id='english-2024-myschool-70064';let l=structuredClone(ledger);l.questions[id].answer_review.status='held';assert.throws(()=>historical(pool,l),/eligible/);l=structuredClone(ledger);const sourceId=l.questions[id].source_id;l.sources['other-owner']={...l.sources[sourceId]};l.questions[id].source_id='other-owner';assert.throws(()=>historical(pool,l),/exact recovered source owner identity/);});
