'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),engine=require('../engines/src/storage-loss-engine');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../data/agriculture/storage-data.js'),'utf8'),context);const data=context.STORAGE_DATA;let count=0;
for(const crop of Object.keys(data.lossRates))for(const methodKey of Object.keys(data.lossRates[crop].methods))for(const countryCode of Object.keys(data.countries).filter(code=>data.countries[code]))for(const quantityTonnes of[.1,1,25,1000])for(const durationMonths of[1,6,12,18]){const prices=data.harvestPrices[countryCode]||data.harvestPrices.ALL,pricePerTonne=(prices[crop]||data.harvestPrices.ALL[crop])*1.37,result=engine.calculate({crop,countryCode,methodKey,quantityTonnes,durationMonths,pricePerTonne},data);assert.equal(result.ok,true);assert.equal(result.input.crop,crop);count+=1}
assert.equal(engine.calculate({crop:'',countryCode:'ALL',methodKey:'',quantityTonnes:0,durationMonths:6,pricePerTonne:0},data).ok,false);console.log(`PASS ${count} Storage Loss engine scenarios`);

const sample={crop:'maize',countryCode:'KE',methodKey:'traditional_granary',quantityTonnes:1,durationMonths:6,pricePerTonne:40000};
let rejected=0;for(const key of ['quantityTonnes','durationMonths','pricePerTonne'])for(const value of [0,-1,null,true,false,[],{},NaN,Infinity,'6months','']){assert.equal(engine.calculate({...sample,[key]:value},data).ok,false);rejected++;}
for(const value of [.5,1.5,'1.5']){assert.equal(engine.calculate({...sample,durationMonths:value},data).ok,false);rejected++;}
for(const key of ['crop','countryCode','methodKey'])for(const value of ['constructor','__proto__','toString','unknown',[],{}]){assert.equal(engine.calculate({...sample,[key]:value},data).ok,false);rejected++;}
assert.equal(engine.calculate({...sample,countryCode:'GH_extra'},data).ok,false);rejected++;
assert.equal(engine.calculate({...sample,countryCode:undefined,durationMonths:undefined},data).input.countryCode,'ALL');assert.equal(engine.calculate({...sample,durationMonths:undefined},data).input.durationMonths,6);assert.equal(engine.calculate({...sample,durationMonths:'12',quantityTonnes:'1e-3'},data).input.quantityTonnes,.001);assert.equal(engine.calculate({...sample,quantityTonnes:1e308},data).status,'out-of-range');console.log(JSON.stringify({rejected,omittedDefaultsPreserved:true,scientificNumericStrings:true,overflowRejected:true}));

let periodCases=0;for(const durationMonths of [1,6,12,18,24])for(const quantityTonnes of [.1,1,2.4]){const r=engine.calculate({...sample,durationMonths,quantityTonnes},data);assert(Math.abs(r.siloPeriodCost-r.siloAnnualCost*durationMonths/12)<1e-9);assert.equal(r.siloNetSave,r.siloValSaved-r.siloPeriodCost);assert.equal(r.siloROI,(r.siloValSaved-r.siloPeriodCost)/r.siloPeriodCost*100);periodCases++;}
const lossCase=engine.calculate({...sample,methodKey:'metal_silo'},data);assert.equal(lossCase.siloValSaved,0);assert.equal(lossCase.siloNetSave,-lossCase.siloPeriodCost);assert.equal(lossCase.siloROI,-100);console.log(JSON.stringify({periodCases,negativeSavingsPreserved:true}));
