"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const ROOT=path.resolve(__dirname,"..");
const context={console,URLSearchParams,fetch:async()=>{throw new Error("network forbidden")},localStorage:{getItem(){return null},setItem(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,"engines/src/creator-calendar-engine.js"),"utf8"),context);const engine=context.CreatorCalendarEngine;
const sw=fs.readFileSync(path.join(ROOT,"sw/zana/kalenda-ya-mtayarishi/app.html"),"utf8"),index=fs.readFileSync(path.join(ROOT,"sw/zana/kalenda-ya-mtayarishi/index.html"),"utf8");
assert.match(index,/href="\/sw\/zana\/kalenda-ya-mtayarishi\/app"/);assert.match(sw,/<html lang="sw">/);assert.match(sw,/afrotools-sw-native-owner" content="creator-calendar"/);assert.match(sw,/afrotools-sw-source-owner" content="engines\/src\/creator-calendar-engine\.js"/);assert.doesNotMatch(sw,/<iframe\b/i);assert.ok(fs.existsSync(path.join(ROOT,"assets/img/tools/creator-calendar.webp")));
for(const file of ["tools/creator-calendar/app.html","fr/tools/calendrier-createur/app.html"]){assert.match(fs.readFileSync(path.join(ROOT,file),"utf8"),/hreflang="sw" href="https:\/\/afrotools\.com\/sw\/zana\/kalenda-ya-mtayarishi\/app"/)}
const plan=engine.buildLocalPlan({topic:"Biashara za ubunifu",startDate:"2026-08-01",days:5,country:"TZ",platforms:["instagram","tiktok"]});assert.equal(plan.posts.length,5);assert.deepEqual(JSON.parse(JSON.stringify(plan.posts.map(p=>[p.day,p.date,p.platform,p.time,p.angle]))),[[1,"2026-08-01","instagram","06:30","educate"],[2,"2026-08-02","tiktok","15:00","engage"],[3,"2026-08-03","instagram","19:00","showcase"],[4,"2026-08-04","tiktok","09:00","educate"],[5,"2026-08-05","instagram","12:00","engage"]]);assert.equal(JSON.parse(JSON.stringify(plan)).topic,"Biashara za ubunifu");
for(const bad of [{topic:"",startDate:"2026-08-01",days:2,platforms:["instagram"]},{topic:"x",startDate:"bad",days:2,platforms:["instagram"]},{topic:"x",startDate:"2026-08-01",days:0,platforms:["instagram"]},{topic:"x",startDate:"2026-08-01",days:2,platforms:[]}])assert.throws(()=>engine.buildLocalPlan(bad));
console.log("Swahili creator calendar static and engine parity passed.");
