#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const ROOT = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(ROOT, file), 'utf8');
const english = read('tools/image-to-text/index.html');
const swahili = read('sw/zana/kutoa-maandishi-kwenye-picha/index.html');
const studio = read('assets/js/lib/image-to-text-studio.js');
const local = read('assets/js/lib/image-to-text-ocr-local.js');
const adapter = read('assets/js/lib/image-to-text-studio-sw.js');
const registry = read('assets/js/components/tool-registry.js');
const manifest = JSON.parse(read('data/localization/sw-image-design-parity.json'));
const built = spawnSync(process.execPath, ['scripts/build-sw-image-to-text.js', '--check'], { cwd: ROOT, encoding: 'utf8' });
assert.strictEqual(built.status, 0, built.stderr || built.stdout);
assert.match(swahili, /<html\b[^>]*lang="sw"/);
assert.ok(swahili.includes('Source owner: scripts/build-sw-image-to-text.js'));
for (const owner of ['image-to-text-ocr-local.js', 'image-to-text-studio.js', 'image-to-text-studio-sw.js']) assert.ok(swahili.includes(owner));
for (const id of ['ocrInput', 'ocrQueue', 'ocrLanguage', 'ocrPreparedCanvas', 'ocrRunBtn', 'ocrBatchBtn', 'ocrTextArea', 'ocrDownloadTxtBtn', 'ocrDownloadMdBtn', 'ocrDownloadJsonBtn', 'ocrDownloadCsvBtn', 'ocrCopyBriefBtn']) assert.ok(swahili.includes(`id="${id}"`), `missing ${id}`);
assert.ok(english.includes('/assets/js/lib/image-to-text-studio.js'));
assert.ok(!/<iframe\b/i.test(swahili));
assert.ok(!/<script\b[^>]+src="https?:\/\//i.test(swahili));
assert.ok(!/\b(?:fetch|XMLHttpRequest|WebSocket|sendBeacon)\s*\(/.test(studio));
assert.ok(!/\b(?:fetch|XMLHttpRequest|WebSocket|sendBeacon)\s*\(/.test(adapter));
for (const token of ['workerPath:', 'corePath:', 'langPath:', 'workerBlobURL: false']) assert.ok(local.includes(token));
for (const token of ['Tesseract.recognize', 'toDataURL("image/png")', 'D("txt")', 'D("md")', 'application/json', 'text/csv', 'Process queue']) assert.ok(studio.includes(token), `studio missing ${token}`);
assert.ok(swahili.includes('<link rel="canonical" href="https://afrotools.com/sw/zana/kutoa-maandishi-kwenye-picha/">'));
for (const [lang, route] of [['en', '/tools/image-to-text/'], ['fr', '/fr/tools/image-en-texte/'], ['sw', '/sw/zana/kutoa-maandishi-kwenye-picha/']]) assert.ok(swahili.includes(`hreflang="${lang}" href="https://afrotools.com${route}"`));
assert.ok(english.includes('hreflang="sw" href="https://afrotools.com/sw/zana/kutoa-maandishi-kwenye-picha/"'));
assert.ok(read('fr/tools/image-en-texte/index.html').includes('hreflang="sw" href="https://afrotools.com/sw/zana/kutoa-maandishi-kwenye-picha/"'));
assert.ok(swahili.includes('https://afrotools.com/assets/img/tools/image-to-text.webp'));
assert.ok(fs.existsSync(path.join(ROOT, 'assets/img/tools/image-to-text.webp')));
for (const match of swahili.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) JSON.parse(match[1]);
assert.ok(swahili.includes('"inLanguage":"sw"'));
assert.ok(swahili.includes('<meta property="og:locale" content="sw_TZ">'));
assert.ok(swahili.includes('content="OCR ya picha, kutoa maandishi kwenye picha'));
for (const leak of ['Loading editor...', 'Choose images', 'Process queue', 'Result summary', 'Session history', 'Are my images uploaded?']) assert.ok(!swahili.includes(`>${leak}<`), `visible English leak: ${leak}`);
assert.ok(registry.includes("sourceId: 'image-to-text', imageId: 'image-to-text'"));
assert.strictEqual(manifest.rows.find(row => row.id === 'image-to-text').status, 'accepted-candidate');
console.log('Swahili image-to-text static parity: shared local OCR owner, native UI, exports, privacy, SEO, artwork and discovery passed.');
