// 54 African countries with economic data for idea generation
// costMult = cost multiplier relative to Nigeria (1.0)
// revMult = revenue multiplier relative to Nigeria (1.0)
module.exports = [
{code:"NG",name:"Nigeria",currency:"NGN",costMult:1,revMult:1,cities:["Lagos","Abuja","Port Harcourt","Ibadan","Kano","Enugu","Benin City","Kaduna","Onitsha","Abeokuta"],region:"west"},
{code:"KE",name:"Kenya",currency:"KES",costMult:0.45,revMult:0.5,cities:["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika","Malindi","Nyeri"],region:"east"},
{code:"ZA",name:"South Africa",currency:"ZAR",costMult:0.85,revMult:1.1,cities:["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth","Bloemfontein","Soweto","Sandton"],region:"southern"},
{code:"GH",name:"Ghana",currency:"GHS",costMult:0.35,revMult:0.4,cities:["Accra","Kumasi","Tamale","Takoradi","Cape Coast","Tema","Sunyani","Ho"],region:"west"},
{code:"ET",name:"Ethiopia",currency:"ETB",costMult:0.3,revMult:0.35,cities:["Addis Ababa","Dire Dawa","Hawassa","Bahir Dar","Mekelle","Adama","Jimma","Gondar"],region:"east"},
{code:"EG",name:"Egypt",currency:"EGP",costMult:0.6,revMult:0.75,cities:["Cairo","Alexandria","Giza","Sharm El-Sheikh","Luxor","Aswan","Hurghada","Mansoura"],region:"north"},
{code:"TZ",name:"Tanzania",currency:"TZS",costMult:0.35,revMult:0.38,cities:["Dar es Salaam","Dodoma","Arusha","Mwanza","Zanzibar","Mbeya","Morogoro","Tanga"],region:"east"},
{code:"UG",name:"Uganda",currency:"UGX",costMult:0.3,revMult:0.32,cities:["Kampala","Entebbe","Jinja","Gulu","Mbarara","Fort Portal","Lira","Masaka"],region:"east"},
{code:"RW",name:"Rwanda",currency:"RWF",costMult:0.28,revMult:0.3,cities:["Kigali","Butare","Gisenyi","Ruhengeri","Gitarama","Byumba","Cyangugu"],region:"east"},
{code:"SN",name:"Senegal",currency:"XOF",costMult:0.4,revMult:0.42,cities:["Dakar","Thies","Saint-Louis","Kaolack","Ziguinchor","Touba","Mbour","Rufisque"],region:"west"},
{code:"CI",name:"Cote d'Ivoire",currency:"XOF",costMult:0.42,revMult:0.45,cities:["Abidjan","Bouake","Yamoussoukro","Daloa","San-Pedro","Korhogo","Man","Divo"],region:"west"},
{code:"CM",name:"Cameroon",currency:"XAF",costMult:0.38,revMult:0.4,cities:["Douala","Yaounde","Bamenda","Bafoussam","Garoua","Maroua","Ngaoundere","Bertoua"],region:"central"},
{code:"CD",name:"DR Congo",currency:"CDF",costMult:0.25,revMult:0.22,cities:["Kinshasa","Lubumbashi","Mbuji-Mayi","Kisangani","Kananga","Bukavu","Goma","Kolwezi"],region:"central"},
{code:"MZ",name:"Mozambique",currency:"MZN",costMult:0.28,revMult:0.25,cities:["Maputo","Beira","Nampula","Matola","Chimoio","Nacala","Quelimane","Tete"],region:"southern"},
{code:"MA",name:"Morocco",currency:"MAD",costMult:0.65,revMult:0.7,cities:["Casablanca","Marrakech","Rabat","Fez","Tangier","Agadir","Meknes","Oujda"],region:"north"},
{code:"AO",name:"Angola",currency:"AOA",costMult:0.7,revMult:0.6,cities:["Luanda","Huambo","Lobito","Benguela","Lubango","Cabinda","Malanje","Namibe"],region:"central"},
{code:"MG",name:"Madagascar",currency:"MGA",costMult:0.2,revMult:0.18,cities:["Antananarivo","Toamasina","Antsirabe","Mahajanga","Fianarantsoa","Toliara"],region:"east"},
{code:"MW",name:"Malawi",currency:"MWK",costMult:0.18,revMult:0.15,cities:["Lilongwe","Blantyre","Mzuzu","Zomba","Kasungu","Mangochi"],region:"southern"},
{code:"ZM",name:"Zambia",currency:"ZMW",costMult:0.32,revMult:0.3,cities:["Lusaka","Kitwe","Ndola","Kabwe","Livingstone","Chipata","Solwezi"],region:"southern"},
{code:"ZW",name:"Zimbabwe",currency:"ZWL",costMult:0.25,revMult:0.22,cities:["Harare","Bulawayo","Chitungwiza","Mutare","Gweru","Masvingo","Kwekwe"],region:"southern"},
{code:"ML",name:"Mali",currency:"XOF",costMult:0.3,revMult:0.25,cities:["Bamako","Sikasso","Mopti","Segou","Koutiala","Kayes"],region:"west"},
{code:"BF",name:"Burkina Faso",currency:"XOF",costMult:0.25,revMult:0.22,cities:["Ouagadougou","Bobo-Dioulasso","Koudougou","Banfora","Ouahigouya"],region:"west"},
{code:"NE",name:"Niger",currency:"XOF",costMult:0.22,revMult:0.18,cities:["Niamey","Zinder","Maradi","Agadez","Tahoua"],region:"west"},
{code:"TD",name:"Chad",currency:"XAF",costMult:0.28,revMult:0.2,cities:["N'Djamena","Moundou","Sarh","Abeche","Kelo"],region:"central"},
{code:"GN",name:"Guinea",currency:"GNF",costMult:0.22,revMult:0.2,cities:["Conakry","Nzerekore","Kankan","Kindia","Labe"],region:"west"},
{code:"BJ",name:"Benin",currency:"XOF",costMult:0.28,revMult:0.25,cities:["Cotonou","Porto-Novo","Parakou","Djougou","Abomey-Calavi"],region:"west"},
{code:"TG",name:"Togo",currency:"XOF",costMult:0.25,revMult:0.22,cities:["Lome","Kara","Sokode","Kpalime","Atakpame"],region:"west"},
{code:"SL",name:"Sierra Leone",currency:"SLE",costMult:0.2,revMult:0.18,cities:["Freetown","Bo","Kenema","Makeni","Koidu"],region:"west"},
{code:"LR",name:"Liberia",currency:"LRD",costMult:0.2,revMult:0.18,cities:["Monrovia","Gbarnga","Kakata","Buchanan","Voinjama"],region:"west"},
{code:"MR",name:"Mauritania",currency:"MRU",costMult:0.3,revMult:0.25,cities:["Nouakchott","Nouadhibou","Kaedi","Rosso","Atar"],region:"west"},
{code:"ER",name:"Eritrea",currency:"ERN",costMult:0.2,revMult:0.15,cities:["Asmara","Keren","Massawa","Assab","Mendefera"],region:"east"},
{code:"GM",name:"Gambia",currency:"GMD",costMult:0.18,revMult:0.15,cities:["Banjul","Serekunda","Brikama","Bakau","Farafenni"],region:"west"},
{code:"BW",name:"Botswana",currency:"BWP",costMult:0.55,revMult:0.6,cities:["Gaborone","Francistown","Maun","Kasane","Selebi-Phikwe"],region:"southern"},
{code:"NA",name:"Namibia",currency:"NAD",costMult:0.5,revMult:0.55,cities:["Windhoek","Walvis Bay","Swakopmund","Oshakati","Rundu"],region:"southern"},
{code:"GA",name:"Gabon",currency:"XAF",costMult:0.6,revMult:0.55,cities:["Libreville","Port-Gentil","Franceville","Oyem","Moanda"],region:"central"},
{code:"LS",name:"Lesotho",currency:"LSL",costMult:0.22,revMult:0.2,cities:["Maseru","Teyateyaneng","Mafeteng","Hlotse","Mohales Hoek"],region:"southern"},
{code:"GW",name:"Guinea-Bissau",currency:"XOF",costMult:0.18,revMult:0.15,cities:["Bissau","Bafata","Gabu","Bissorã","Bolama"],region:"west"},
{code:"GQ",name:"Equatorial Guinea",currency:"XAF",costMult:0.65,revMult:0.5,cities:["Malabo","Bata","Ebebiyin","Aconibe","Mongomo"],region:"central"},
{code:"MU",name:"Mauritius",currency:"MUR",costMult:0.55,revMult:0.65,cities:["Port Louis","Beau Bassin-Rose Hill","Vacoas-Phoenix","Curepipe","Quatre Bornes"],region:"east"},
{code:"SZ",name:"Eswatini",currency:"SZL",costMult:0.25,revMult:0.22,cities:["Mbabane","Manzini","Siteki","Big Bend","Nhlangano"],region:"southern"},
{code:"DJ",name:"Djibouti",currency:"DJF",costMult:0.4,revMult:0.35,cities:["Djibouti City","Ali Sabieh","Tadjoura","Obock","Dikhil"],region:"east"},
{code:"CV",name:"Cape Verde",currency:"CVE",costMult:0.35,revMult:0.3,cities:["Praia","Mindelo","Santa Maria","Espargos","Assomada"],region:"west"},
{code:"CF",name:"Central African Republic",currency:"XAF",costMult:0.2,revMult:0.15,cities:["Bangui","Bimbo","Berbérati","Carnot","Bambari"],region:"central"},
{code:"CG",name:"Republic of Congo",currency:"XAF",costMult:0.4,revMult:0.35,cities:["Brazzaville","Pointe-Noire","Dolisie","Nkayi","Ouesso"],region:"central"},
{code:"KM",name:"Comoros",currency:"KMF",costMult:0.2,revMult:0.18,cities:["Moroni","Mutsamudu","Fomboni","Domoni"],region:"east"},
{code:"ST",name:"Sao Tome and Principe",currency:"STN",costMult:0.22,revMult:0.18,cities:["São Tomé","Santo Amaro","Neves","Trindade"],region:"central"},
{code:"SC",name:"Seychelles",currency:"SCR",costMult:0.7,revMult:0.8,cities:["Victoria","Anse Boileau","Beau Vallon","Anse Royale"],region:"east"},
{code:"SD",name:"Sudan",currency:"SDG",costMult:0.25,revMult:0.2,cities:["Khartoum","Omdurman","Port Sudan","Kassala","El Obeid","Nyala"],region:"north"},
{code:"SS",name:"South Sudan",currency:"SSP",costMult:0.2,revMult:0.15,cities:["Juba","Malakal","Wau","Bor","Yei"],region:"east"},
{code:"SO",name:"Somalia",currency:"SOS",costMult:0.2,revMult:0.18,cities:["Mogadishu","Hargeisa","Kismayo","Marka","Berbera"],region:"east"},
{code:"LY",name:"Libya",currency:"LYD",costMult:0.5,revMult:0.45,cities:["Tripoli","Benghazi","Misrata","Tarhuna","Zawiya"],region:"north"},
{code:"TN",name:"Tunisia",currency:"TND",costMult:0.5,revMult:0.55,cities:["Tunis","Sfax","Sousse","Kairouan","Bizerte","Gabes"],region:"north"},
{code:"DZ",name:"Algeria",currency:"DZD",costMult:0.5,revMult:0.5,cities:["Algiers","Oran","Constantine","Annaba","Blida","Batna","Setif"],region:"north"},
{code:"BI",name:"Burundi",currency:"BIF",costMult:0.15,revMult:0.12,cities:["Bujumbura","Gitega","Muyinga","Ngozi","Rumonge"],region:"east"},
];
