module.exports = [
  {id:"transportation",name:"Transportation & Logistics",icon:"truck"},
  {id:"agriculture",name:"Agriculture & Agribusiness",icon:"wheat"},
  {id:"food",name:"Food & Beverage",icon:"utensils"},
  {id:"technology",name:"Technology & Digital Services",icon:"laptop"},
  {id:"retail",name:"Retail & E-commerce",icon:"cart"},
  {id:"fintech",name:"Financial Services & Fintech",icon:"credit-card"},
  {id:"construction",name:"Construction & Real Estate",icon:"building"},
  {id:"health",name:"Healthcare & Wellness",icon:"hospital"},
  {id:"education",name:"Education & Training",icon:"graduation"},
  {id:"energy",name:"Energy & Utilities",icon:"bolt"},
  {id:"fashion",name:"Fashion & Textiles",icon:"dress"},
  {id:"tourism",name:"Tourism & Hospitality",icon:"hotel"},
  {id:"media",name:"Media & Creative",icon:"camera"},
  {id:"manufacturing",name:"Manufacturing & Processing",icon:"factory"},
  {id:"services",name:"Professional Services",icon:"briefcase"},
  {id:"mining",name:"Mining & Natural Resources",icon:"pickaxe"},
  {id:"beauty",name:"Beauty & Personal Care",icon:"sparkles"},
  {id:"logistics",name:"Warehousing & Supply Chain",icon:"warehouse"},
  {id:"waste",name:"Waste Management & Recycling",icon:"recycle"},
  {id:"telecom",name:"Telecommunications",icon:"signal"},
];
