const assert = require('assert');
const engine = require('../../assets/js/engines/dj-paye');
const server = require('../../netlify/functions/_engines/dj-paye');
function near(actual, expected, label) { assert.ok(Math.abs(actual - expected) < 0.01, `${label}: expected ${expected}, received ${actual}`); }
near(engine.taxMonthly(50000).tax, 0, 'taxable exemption boundary');
near(engine.taxMonthly(50001).tax, 3000, 'taxable income floors to DJF 5,000 step');
near(engine.taxMonthly(54999).tax, 3000, 'same statutory DJF 5,000 bucket');
near(engine.taxMonthly(55000).tax, 3750, 'next statutory bucket');
near(engine.taxMonthly(150000).tax, 18000, 'third boundary');
near(engine.taxMonthly(300000).tax, 51000, 'fourth boundary');
near(engine.taxMonthly(600000).tax, 126000, 'fifth boundary');
near(engine.taxMonthly(1000000).tax, 246000, 'sixth boundary');
near(engine.taxMonthly(2000000).tax, 596000, 'seventh boundary');
near(engine.taxMonthly(2500000).tax, 821000, 'top band');
const standard = engine.calculate({ grossMonthly: 200000, employmentType: 'professional' });
near(standard.employeeCnssMonthly, 12000, 'employee CNSS includes retirement and health');
near(standard.employerCnssMonthly, 31400, 'employer CNSS');
near(standard.taxableIncome, 188000, 'mandatory CNSS deducted from ITS base');
near(standard.roundedTaxableIncome, 185000, 'statutory taxable-income floor');
near(standard.itsMonthly, 25700, 'monthly ITS');
near(standard.netMonthly, 162300, 'monthly take-home');
near(standard.employerCostMonthly, 231400, 'employer cost');
near(engine.calculate({ grossMonthly: 10000, employmentType: 'professional' }).contributionBase, 20000, 'professional contribution floor');
near(engine.calculate({ grossMonthly: 10000, employmentType: 'domestic' }).contributionBase, 15850, 'domestic contribution floor');
assert.strictEqual(engine.formulaParameters.cnssDeductibleFromItsBase, true);
assert.strictEqual(engine.sourceCheckedOn, '2026-07-22');
const serverResult = server.calculate({ grossMonthly: 200000, employmentType: 'professional' });
near(serverResult.result.netMonthly, 162300, 'server net parity');
near(serverResult.employer.totalCostMonthly, 231400, 'server employer parity');
console.log('Djibouti ITS and CNSS official fixtures passed.');
