import sys

content = open('C:/Users/Oza/Documents/afrotools/assets/js/components/tool-registry.min.js', 'r', encoding='utf-8').read()

# Build new entries as a list then join
entries = [
    '{id:"student-budget",name:"Student Budget Planner",icon:"\U0001f4b8",desc:"Budget your student life in 13 African cities. Pre-filled costs for accommodation, food, transport, data and books.",href:"/tools/student-budget/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Ads",estTraffic:5000,estRevenue:80,priority:79,isNew:true}',
    '{id:"scholarship-check",name:"Scholarship Eligibility Checker",icon:"\U0001f3c6",desc:"Check your eligibility for 15 major African and international scholarships. Scored match across 5 dimensions.",href:"/tools/scholarship-check/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Ads",estTraffic:7000,estRevenue:110,priority:78,isNew:true}',
    '{id:"study-abroad-cost",name:"Study Abroad Cost Calculator",icon:"\u2708\ufe0f",desc:"Calculate total cost of studying in UK, Canada, Australia, USA or Germany. Tuition, living, visa, health insurance.",href:"/tools/study-abroad-cost/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Affiliate",estTraffic:9000,estRevenue:160,priority:77,isNew:true}',
    '{id:"kcse-calculator",name:"KCSE Grade Calculator",icon:"\U0001f1f0\U0001f1ea",desc:"Calculate your Kenya Certificate of Secondary Education grade. Best 7 of 8 subjects, mean grade, university cut-off comparison.",href:"/tools/kcse-calculator/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["KE"],revenue:"Ads",estTraffic:6000,estRevenue:90,priority:76,isNew:true}',
    '{id:"university-admission",name:"University Admission Points Calculator",icon:"\U0001f393",desc:"Check admission points for Nigeria JAMB, Kenya KCSE, South Africa APS, Ghana WASSCE and Zimbabwe A-Level.",href:"/tools/university-admission/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA","GH","ZW"],revenue:"Ads",estTraffic:8000,estRevenue:120,priority:75,isNew:true}',
    '{id:"student-loan-repay",name:"Student Loan Repayment Calculator",icon:"\U0001f4b0",desc:"Calculate student loan repayment for NELFUND, HELB, NSFAS, Ghana SLTF and Uganda schemes.",href:"/tools/student-loan-repay/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA","GH","UG"],revenue:"Affiliate",estTraffic:5500,estRevenue:90,priority:74,isNew:true}',
    '{id:"helb-repayment",name:"HELB Repayment Calculator",icon:"\U0001f1f0\U0001f1ea",desc:"Kenya HELB loan repayment: official 10% of salary rule, grace period interest, payoff timeline, 12-month schedule.",href:"/tools/helb-repayment/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["KE"],revenue:"Ads",estTraffic:4500,estRevenue:70,priority:73,isNew:true}',
    '{id:"nysc-allowance",name:"NYSC Allowance Calculator",icon:"\U0001f1f3\U0001f1ec",desc:"Calculate total NYSC monthly income: federal allawee, state top-up, side income and savings potential.",href:"/tools/nysc-allowance/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG"],revenue:"Ads",estTraffic:5000,estRevenue:75,priority:72,isNew:true}',
    '{id:"national-service-gh",name:"Ghana NSS Allowance Calculator",icon:"\U0001f1ec\U0001f1ed",desc:"Calculate Ghana National Service Scheme allowance by sector and region. Compare against graduate starting salaries.",href:"/tools/national-service-gh/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["GH"],revenue:"Ads",estTraffic:3000,estRevenue:45,priority:71,isNew:true}',
    '{id:"classroom-size",name:"Classroom Size Calculator",icon:"\U0001f3eb",desc:"Calculate classroom capacity by floor area. Compare against Nigerian, Kenyan and South African educational standards.",href:"/tools/classroom-size/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA"],revenue:"Ads",estTraffic:2500,estRevenue:35,priority:70,isNew:true}',
    '{id:"teacher-salary",name:"Teacher Salary Scale Lookup",icon:"\U0001f468\u200d\U0001f3eb",desc:"Look up teacher salary scales across 9 African countries by level, school type and experience band.",href:"/tools/teacher-salary/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA","GH","ET","TZ","UG","RW","EG"],revenue:"Ads",estTraffic:4000,estRevenue:60,priority:69,isNew:true}',
    '{id:"exam-timetable",name:"Exam Timetable Generator",icon:"\U0001f4c5",desc:"Generate a personalised exam study timetable. Add subjects, set weeks, get a colour-coded weekly schedule.",href:"/tools/exam-timetable/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Ads",estTraffic:4500,estRevenue:65,priority:68,isNew:true}',
    '{id:"plagiarism-pct",name:"Plagiarism Self-Check Tool",icon:"\U0001f50d",desc:"Self-check your essay for generic phrases and originality issues before submitting. Educational use, no database check.",href:"/tools/plagiarism-pct/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Ads",estTraffic:6000,estRevenue:90,priority:67,isNew:true}',
    '{id:"course-load",name:"Course Load and Credit Hour Planner",icon:"\U0001f4da",desc:"Plan your university credit hours, project graduation timeline and get warnings if you are overloaded.",href:"/tools/course-load/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Ads",estTraffic:3500,estRevenue:50,priority:66,isNew:true}',
    '{id:"boarding-school",name:"Boarding School Cost Calculator",icon:"\U0001f3e0",desc:"Compare boarding school costs across 6 African countries. Termly fees, meals, extras vs day school comparison.",href:"/tools/boarding-school/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA","GH","UG","TZ"],revenue:"Affiliate",estTraffic:3500,estRevenue:60,priority:65,isNew:true}',
    '{id:"tutoring-rate",name:"Tutoring Rate Calculator",icon:"\U0001f4d6",desc:"Find fair tutoring rates across Nigeria, Kenya, South Africa and Ghana by subject, level and experience.",href:"/tools/tutoring-rate/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["NG","KE","ZA","GH"],revenue:"Ads",estTraffic:3000,estRevenue:45,priority:64,isNew:true}',
    '{id:"cert-roi",name:"Professional Certification ROI Calculator",icon:"\U0001f4dc",desc:"Calculate the return on investment for ACCA, CFA, AWS, PMP and other professional certifications in Africa.",href:"/tools/cert-roi/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Affiliate",estTraffic:5000,estRevenue:85,priority:63,isNew:true}',
    '{id:"coding-bootcamp",name:"African Coding Bootcamp Comparator",icon:"\U0001f4bb",desc:"Compare 9 top African coding bootcamps: ALX, Andela, Decagon, MEST, Gebeya. Filter by region, level and budget.",href:"/tools/coding-bootcamp/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Affiliate",estTraffic:4000,estRevenue:70,priority:62,isNew:true}',
    '{id:"edu-savings",name:"Education Savings Plan Calculator",icon:"\U0001f393",desc:"Plan your child or personal education savings. Monthly contribution, target, gap analysis and milestone table.",href:"/tools/edu-savings/",category:"education",tier:"T2",status:"new",phase:"LIVE",countries:["ALL"],revenue:"Affiliate",estTraffic:4500,estRevenue:75,priority:61,isNew:true}',
]

new_block = ',' + ','.join(entries)

# Insert after school-fees entry at position 60868
new_content = content[:60868] + new_block + content[60868:]

with open('C:/Users/Oza/Documents/afrotools/assets/js/components/tool-registry.min.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done. Original length:', len(content), '-> New length:', len(new_content))
