(function initHaLivestock(root){'use strict';var core=root.Ha04,app=root.AfroTools||{},data=app.LivestockFeedData,engine=app.LivestockFeedEngine,prices=null,latest=null;
var animals={cattle:'Shanu',goat:'Awaki',sheep:'Tumaki'};var classes={dairy_lactating_high:'Saniya mai yawan nono',dairy_lactating_medium:'Saniya mai matsakaicin nono',dairy_lactating_low:'Saniya mai ƙarancin nono',dairy_dry:'Saniya da ba ta shayarwa',dairy_dry_late:'Saniya mai kusa da haihuwa',beef_growing_young:'Maraƙi mai girma',beef_growing_older:'Saniya/sa mai girma',beef_fattening:'Kiba don nama',beef_maintenance:'Kula da nauyi',calf_pre_weaning:'Maraƙi kafin yaye',bull_breeding:'Sa na kiwo',doe_lactating:'Akuya mai shayarwa',doe_dry:'Akuya da ba ta shayarwa',doe_pregnant_late:'Akuya mai kusa da haihuwa',buck_breeding:'Akuya namiji na kiwo',kid_growing:'Ɗan akuya mai girma',ewe_lactating:'Tunkiya mai shayarwa',ewe_dry:'Tunkiya da ba ta shayarwa',ewe_pregnant_late:'Tunkiya mai kusa da haihuwa',ram_breeding:'Rago na kiwo',lamb_growing:'Ɗan tunkiya mai girma',fattening:'Kiba',maintenance:'Kula da nauyi'};
var ingredientNames={maize_grain:'Masara',maize_bran:'Dutsen masara',wheat_bran:'Dutsen alkama',rice_bran:'Dutsen shinkafa',sorghum_grain:'Dawa',millet_grain:'Gero',cassava_chips:'Yankan rogo',cassava_peel:'Bawon rogo',molasses:'Molasses',brewers_grain:'Ragowar giya',cottonseed_cake:'Biredin auduga',groundnut_cake:'Biredin gyada',soybean_meal:'Garin waken soya',palm_kernel_cake:'Biredin ɗan dabino',fish_meal:'Garin kifi',blood_meal:'Garin jini',leucaena_leaf:'Ganyen leucaena',moringa_leaf:'Ganyen zogale',napier_grass:'Ciyawar Napier',maize_stover:'Ragowar masara',rice_straw:'Buhun shinkafa',cowpea_haulm:'Ragowar wake',groundnut_haulm:'Ragowar gyada',bone_meal:'Garin ƙashi',limestone:'Limestone',dcp:'DCP',salt:'Gishiri',urea:'Urea'};var category={energy:'Makamashi',protein:'Furotin',roughage:'Ciyawa',mineral:'Ma’adanai',additive:'Ƙari'};
var config={sourceId:'livestock-feed-nigeria',route:'/ha/kayan-aiki/abincin-dabbobi/',formId:'feedForm',filename:'afrotools-abincin-dabbobi-ng.json',sourceLabel:'FAO AFRIS, ka’idojin NRC da farashin sinadaran AfroTools',sourceLinks:['https://www.fao.org/4/x6512e/x6512e00.htm'],dataReviewed:'2026-08-08',confidence:'Matsakaici don kasafin farko',assumptions:['Ingancin sinadari matsakaici','Buƙata bisa ajin dabba da nauyin rai']};
function populateClasses(){var animal=data[core.byId('animal').value],select=core.byId('animalClass');select.innerHTML='';Object.keys(animal.classes).forEach(function(key){select.appendChild(core.option(key,classes[key]||key));});}
function available(){return Object.keys(data.ingredients).filter(function(key){var x=data.ingredients[key];return(x.avail.indexOf('NG')>=0||x.avail.indexOf('ALL')>=0)&&prices[key]!==undefined;});}
function populateIngredients(){var box=core.byId('ingredients');box.innerHTML='';available().forEach(function(key){var x=data.ingredients[key],wrap=document.createElement('div'),input=document.createElement('input'),label=document.createElement('label');input.type='checkbox';input.id='ingredient-'+key;input.value=key;input.checked=true;input.className='ingredient';label.htmlFor=input.id;label.textContent=(ingredientNames[key]||key)+' — '+(category[x.cat]||x.cat)+' — '+(prices[key]===0?'ba kuɗin saya':core.money(prices[key],prices.currency)+'/kg');wrap.className='ha04-check';wrap.appendChild(input);wrap.appendChild(label);box.appendChild(wrap);});}
function initialise(){if(!data||!engine||!data.prices||!data.prices.NG)return core.fail('Injin ko bayanan abincin dabbobi ba su samu ba.',core.byId('animal'));prices=data.prices.NG;core.byId('animal').value='cattle';core.byId('weight').value='300';core.byId('number').value='1';core.byId('budget').value='0';populateClasses();populateIngredients();}
function input(){return{animalType:core.byId('animal').value,animalClass:core.byId('animalClass').value,bodyWeight:Number(core.byId('weight').value),numAnimals:Number(core.byId('number').value),selectedFeeds:Array.from(document.querySelectorAll('.ingredient:checked')).map(function(n){return n.value;}),maxBudget:Number(core.byId('budget').value),countryCode:'NG'};}
function validate(v){if(!data[v.animalType])return core.fail('Zaɓi ingantacciyar dabba.',core.byId('animal'));if(!data[v.animalType].classes[v.animalClass])return core.fail('Zaɓi ingantaccen matakin dabba.',core.byId('animalClass'));if(!Number.isFinite(v.bodyWeight)||v.bodyWeight<1||v.bodyWeight>2000)return core.fail('Saka nauyi tsakanin kg 1 da 2,000.',core.byId('weight'));if(!Number.isInteger(v.numAnimals)||v.numAnimals<1||v.numAnimals>10000)return core.fail('Saka cikakken adadi tsakanin 1 da 10,000.',core.byId('number'));if(!Number.isFinite(v.maxBudget)||v.maxBudget<0)return core.fail('Kasafi ba zai zama ƙasa da sifili ba.',core.byId('budget'));if(!v.selectedFeeds.length)return core.fail('Zaɓi aƙalla sinadari ɗaya.',document.querySelector('.ingredient'));return true;}
function render(r){core.byId('dailyCost').textContent=core.money(r.costs.dailyPerAnimal,r.currency);core.byId('dmi').textContent=core.number(r.dmi)+' kg';core.byId('protein').textContent=core.number(r.prov.cp_g,0)+' / '+core.number(r.req.cp_g,0)+' g';core.byId('tdn').textContent=core.number(r.prov.tdn_g,0)+' / '+core.number(r.req.tdn_g,0)+' g';core.byId('monthly').textContent=core.money(r.costs.monthlyTotal,r.currency);core.byId('annual').textContent=core.money(r.costs.annualTotal,r.currency);core.byId('alternative').textContent='Kwatancen wani rabo a rana: '+core.money(r.alt.dailyCost,r.currency);var list=core.byId('ration');list.innerHTML='';r.ration.forEach(function(item){var li=document.createElement('li');li.textContent=(ingredientNames[item.id]||item.id)+': '+core.number(item.freshKg)+' kg; '+core.money(item.cost,r.currency);list.appendChild(li);});core.byId('balance').textContent='Daidaito — furotin: '+(r.balance.cp_ok?'an kai buƙata':'akwai gibi')+'; TDN: '+(r.balance.tdn_ok?'an kai buƙata':'akwai gibi')+'.';core.showResult();core.setStatus(r.overBudget?'An tsara rabo amma ya wuce kasafin da ka saka.':'An tsara rabo a wannan burauzar.');}
function calculate(){var v=input();if(!validate(v))return null;var r=engine.calculate(v,data);if(!r||r.error)return core.fail('Ba a iya tsara rabo ba. Duba sinadarai da nauyi.',core.byId('weight'));latest={input:v,result:r};api.latest=latest;render(r);return r;}
function report(){return core.baseReport(config,latest.input,latest.result);}function onChange(event){if(event.target.id==='animal')populateClasses();}var api={calculate:calculate,report:report,latest:null,initialise:initialise,onChange:onChange,engine:engine,data:data};document.addEventListener('DOMContentLoaded',function(){initialise();core.bind(config,api);});})(window);
