-- AfroStream ranking integrity
-- Keeps creator score snapshots replayable so week/month rankings are truthful.

CREATE TABLE IF NOT EXISTS public.as_creator_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id BIGINT REFERENCES public.as_creators(id) ON DELETE CASCADE,
  total_followers BIGINT DEFAULT 0,
  yt_subscribers BIGINT DEFAULT 0,
  twitch_followers BIGINT DEFAULT 0,
  kick_followers BIGINT DEFAULT 0,
  tiktok_followers BIGINT DEFAULT 0,
  ig_followers BIGINT DEFAULT 0,
  total_views BIGINT DEFAULT 0,
  afro_score SMALLINT DEFAULT 0,
  snapshot_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'as_creator_snapshots'
      AND a.attname = 'id'
      AND a.attidentity = ''
  ) THEN
    ALTER TABLE public.as_creator_snapshots
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS as_creator_snapshots_creator_date_uidx
  ON public.as_creator_snapshots (creator_id, snapshot_date);

CREATE INDEX IF NOT EXISTS as_creator_snapshots_date_idx
  ON public.as_creator_snapshots (snapshot_date DESC);

CREATE INDEX IF NOT EXISTS as_streams_creator_name_date_idx
  ON public.as_streams (lower(creator_name), stream_date DESC);

ALTER TABLE public.as_creator_snapshots ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'as_creator_snapshots'
      AND policyname = 'Public read snapshots'
  ) THEN
    CREATE POLICY "Public read snapshots"
      ON public.as_creator_snapshots
      FOR SELECT
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'as_creator_snapshots'
      AND policyname = 'Service full snapshots'
  ) THEN
    CREATE POLICY "Service full snapshots"
      ON public.as_creator_snapshots
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
