'use strict';

function getFunctionReleaseMetadata() {
  try {
    // Generated by build-dist before Netlify bundles functions. Keep this
    // literal path so the JSON is included in the deployed function bundle.
    const metadata = require('./generated-release.json');
    return {
      commit: /^[0-9a-f]{40}$/i.test(metadata.commit || '') ? metadata.commit.toLowerCase() : null
    };
  } catch {
    // Source-only tests and local invocations may have no deploy artifact.
    return { commit: null };
  }
}

module.exports = { getFunctionReleaseMetadata };
